import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
const origin='http://127.0.0.1:8787';
// Only the loopback built-Worker test harness accepts these fixture headers.
// Hosted Sites' dispatcher supplies trusted identity and strips client attempts.
const admin='local_seedy',member1='test-member-one',member2='test-member-two',invite='fictional-test-invite-2026';let revision=0;
async function get(user=admin){const r=await fetch(origin+'/api/club',{headers:user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.invalid'}:{}});return {status:r.status,data:await r.json()}}
async function post(action,payload,user=admin,key=crypto.randomUUID(),rev=revision){const r=await fetch(origin+'/api/club',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','oai-authenticated-user-id':user,'oai-authenticated-user-email':user+'@example.invalid'},body:JSON.stringify({action,payload,requestId:key,revision:rev})});const data=await r.json();if(data.revision)revision=data.revision;return {status:r.status,data}}
async function ok(action,payload,user=admin,key){const r=await post(action,payload,user,key);assert.equal(r.status,200,JSON.stringify(r));revision=(await get()).data.revision;return r}
const results=[];const record=name=>{results.push({name,passed:true});console.log('PASS '+name)};
assert.equal((await get(null)).status,401);record('未登录不能读取私有群组');
let initial=await get();if(initial.data.setup)await ok('initialize',{name:'虚构验收管理员',invite});else throw new Error('此验收脚本需要空的本地数据库，不应覆盖已有数据');
await ok('join',{name:'虚构会话甲',invite},member1);await ok('join',{name:'虚构会话乙',invite},member2);record('独立已验证账号加入群组，邀请码仅授予普通成员');
let s=(await get()).data;const start=Date.now()-3600000,end=Date.now()+7200000;
await ok('event',{title:'虚构验收 · 全流程测试',start,end,venue:'模拟球馆',address:'',capacity:4,signupDeadline:end,cancelDeadline:end,note:'仅本地测试数据，不上传生产数据库',status:'open',bookings:[{name:'1号场',start,end,pricing:'hourly',cents:1200},{name:'2号场',start,end,pricing:'total',cents:0}]});
s=(await get()).data;const e=s.events[0];const my=s.me.playerId;
await ok('friend',{name:'虚构朋友甲'});await ok('friend',{name:'虚构朋友乙'});s=(await get()).data;
for(const p of s.players.filter(p=>p.ownerId===admin))await ok('register',{eventId:e.id,playerId:p.id,arrival:start,departure:end,note:''});
const p1=(await get(member1)).data.me.playerId,p2=(await get(member2)).data.me.playerId;
const race=await Promise.all([post('register',{eventId:e.id,playerId:p1,arrival:start,departure:end,note:''},member1),post('register',{eventId:e.id,playerId:p2,arrival:start,departure:end,note:''},member2)]);assert.ok(race.every(x=>x.status===200),JSON.stringify(race));s=(await get()).data;revision=s.revision;assert.equal(s.registrations.filter(r=>r.status==='confirmed').length,4);assert.equal(s.registrations.filter(r=>r.status==='waitlist').length,1);record('两人并发抢最后名额：一人正式、一人候补，事务无超员');
const queued=s.registrations.find(r=>r.status==='waitlist').playerId;const cancelKey=crypto.randomUUID();await ok('cancel',{eventId:e.id,playerId:my,reason:'测试退出'},admin,cancelKey);await ok('cancel',{eventId:e.id,playerId:my,reason:'重发'},admin,cancelKey);s=(await get()).data;assert.equal(s.registrations.find(r=>r.playerId===queued).status,'confirmed');assert.equal(s.registrations.filter(r=>r.status==='confirmed').length,4);record('正式成员取消后有效候补仅递补一次，重复请求幂等');
const registration={eventId:e.id,playerId:p1,arrival:start,departure:end,note:''};await ok('register',registration,member1);await ok('register',registration,member1);assert.equal((await get()).data.registrations.filter(r=>r.playerId===p1).length,1);record('重复点击报名不重复创建记录');
const denied=await post('generate',{eventId:e.id,at:Date.now(),duration:20,seed:42},member1);assert.equal(denied.status,403);record('普通成员直接请求管理员接口被403拒绝');
const spoof=await post('register',{eventId:e.id,playerId:my,arrival:start,departure:end,note:''},member1);assert.equal(spoof.status,403);record('普通成员不能冒充其他参赛者');
s=(await get()).data;revision=s.revision;await ok('eventStatus',{eventId:e.id,status:'live'});for(const r of s.registrations.filter(r=>r.status==='confirmed'))await ok('attendance',{eventId:e.id,playerId:r.playerId,at:start,state:'ready'});
const at=Date.now()-1200000;await ok('generate',{eventId:e.id,at,duration:20,seed:42});s=(await get()).data;const round=s.rounds[0];assert.equal(s.matches.length,1);await ok('publish',{roundId:round.id});await ok('start',{roundId:round.id,at,monthly:true,elo:true});
s=(await get()).data;const match=s.matches[0],scoreKey=crypto.randomUUID();await ok('score',{matchId:match.id,a:21,b:15,end:Date.now()-60000,reason:'虚构终局比分'},admin,scoreKey);const ratings=(await get()).data.players.map(p=>p.rating);await ok('score',{matchId:match.id,a:21,b:15,end:Date.now()-60000,reason:'重复提交'},admin,scoreKey);s=(await get()).data;assert.deepEqual(s.players.map(p=>p.rating),ratings);assert.equal(s.leaderboard.filter(r=>r.points===3).length,2);record('签到→排场→发布→开赛→比分→月积分与Rating打通，重复提交不加分');
await ok('cost',{eventId:e.id,type:'ball',name:'测试型号甲',pricing:'tube',cents:2400,tubeCount:12,used:6,start:null,end:null,bearer:'members',reason:'测试耗球'});await ok('cost',{eventId:e.id,type:'ball',name:'测试型号乙',pricing:'tube',cents:1800,tubeCount:12,used:4,start:null,end:null,bearer:'members',reason:'测试耗球'});
s=(await get()).data;for(const a of s.attendance)await ok('attendanceEdit',{attendanceId:a.id,start,end,reason:'虚构完整出勤'});
await ok('settle',{eventId:e.id,confirmed:true,reason:'虚构正式结算'});s=(await get()).data;const settlement=s.settlements[0];assert.equal(settlement.unallocated,0);assert.equal(settlement.total,settlement.bills.reduce((a,b)=>a+b.total,0)+settlement.subsidy);assert.equal(settlement.bills.reduce((a,b)=>a+b.ball,0),1800);record('混合耗球、场地费、实际出勤与正式结算严格对账');
const removedPayment=await post('payment',{eventId:e.id,playerId:p1,cents:500,method:'Bizum',reason:'已停用流程'});assert.equal(removedPayment.status,400);await ok('settle',{eventId:e.id,confirmed:true,reason:'第二版费用分摊'});s=(await get()).data;assert.equal(s.settlements.length,1);assert.equal('payments' in s,false);record('已移除付款接口与付款数据展示，分摊结果保留版本');
const memberData=(await get(member2)).data;assert.equal('payments' in memberData,false);assert.equal(memberData.settlements.at(-1).bills.length,4);assert.equal(memberData.settlements.at(-1).bills.reduce((n,b)=>n+b.total,0),settlement.total);record('普通成员可看到每个人的分摊金额与明细');
const sessionA=(await get(member1)).data,sessionB=(await get(member2)).data;assert.equal(sessionA.matches[0].scoreA,sessionB.matches[0].scoreA);assert.equal(sessionA.revision,sessionB.revision);record('两个独立身份会话读取共享最新数据');
const conflict=await post('eventStatus',{eventId:e.id,status:'ended'},admin,crypto.randomUUID(),0);assert.equal(conflict.status,409);record('管理员过期版本写入被409拒绝，避免互相覆盖');
await ok('score',{matchId:match.id,a:15,b:21,end:match.start+60000,reason:'历史比分修正'});s=(await get()).data;assert.equal(s.leaderboard.find(r=>r.playerId===match.a[0]).points,0);assert.equal(s.leaderboard.find(r=>r.playerId===match.b[0]).points,3);record('历史比分修正重建积分与Rating');
mkdirSync('.test-output',{recursive:true});writeFileSync('.test-output/api-results.json',JSON.stringify({at:new Date().toISOString(),results,expectedAfterRestart:{eventId:e.id,revision:s.revision,matchId:match.id,scoreA:15,settlements:1}},null,2));console.log(JSON.stringify({passed:results.length,failed:0,eventId:e.id,revision:s.revision}));
