import {test} from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,type Event} from '../lib/domain/types';
import {mergeUpcomingActivities,upgradeActivitySignups} from '../lib/domain/event-merge';
import {bookingRows} from '../lib/domain/booking-signups';
import {attendanceForEvent} from '../lib/domain/attendance';
import {calculateSettlement} from '../lib/domain/money';
import {apply} from '../lib/domain/commands';
import {projectClubState} from '../lib/club-view';
const hour=3600000,start=Date.parse('2030-10-12T13:00:00Z'),now=start-3*86400000;
function fixture(){
 const s=emptyState();s.settings.initialized=true;s.settings.ownerAccountId='owner';s.accounts.push({id:'owner',playerId:'p0',role:'admin',email:''},{id:'other-admin',playerId:'p9',role:'admin',email:''});
 const common={title:'周末双打局',start,venue:'模拟球馆',address:'模拟地址',capacity:6,signupDeadline:start,cancelDeadline:start-86400000,note:'',status:'open' as const,courtMode:'interval' as const,ballMode:'interval' as const,creatorId:'owner',attendanceMode:'automatic' as const};
 const target:Event={...common,id:'target',end:start+4*hour,pointsPlan:{start,end:start+3.5*hour,roundMinutes:15}},source:Event={...common,id:'source',end:start+2*hour};s.events.push(target,source,{...source,id:'previously-deleted',deletedAt:now-1000,deletedBy:'owner'});
 s.bookings.push({id:'b2',eventId:target.id,name:'2号场',start,end:target.end,pricing:'hourly',cents:690},{id:'b1',eventId:source.id,name:'1号场',start,end:source.end,pricing:'hourly',cents:690});
 for(let i=0;i<10;i++){const playerId='p'+i,e=i<5?target:source;s.players.push({id:playerId,name:'虚构球友'+i,ownerId:i===0?'owner':'member'+i,initialRating:1000,rating:1000,ratedGames:0,enabled:true,ratingReason:''});s.registrations.push({id:'r'+i,eventId:e.id,playerId,sequence:i%5+1,status:'confirmed',arrival:e.start,departure:e.end,note:'虚构备注'+i,registeredAt:now-i*100,joinedAsWaitlist:false,cancelRequested:false,courtExempt:{mode:'none',reason:''},ballExempt:{mode:'none',reason:''}})}
 return {s,target,source};
}
test('同日两场合一，10人转入各自场地；时间、序号、备注、报名时间原样保留',()=>{const {s,target,source}=fixture(),original=structuredClone(s);mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'群主要求');const e=s.events.find(e=>e.id==='target')!;assert.equal(e.end,start+4*hour);assert.equal(e.pointsPlan!.end,start+3.5*hour);assert.equal(s.events.filter(e=>e.deletedAt===undefined).length,1);assert.equal(s.registrations.filter(r=>r.eventId===target.id&&r.status==='confirmed').length,10);for(const b of s.bookings.filter(b=>b.eventId===target.id)){const rows=bookingRows(s,b.id);assert.equal(rows.length,5);assert.equal(b.signupCapacity,6);for(const row of rows){const before=original.registrations.find(r=>r.playerId===row.playerId)!;assert.equal(row.arrival,before.arrival);assert.equal(row.departure,before.departure);assert.equal(row.sequence,before.sequence);assert.equal(row.note,before.note);assert.equal(row.registeredAt,before.registeredAt)}}assert.equal(s.audits.at(-1)!.action,'mergeEvents')});
test('来源原记录留作恢复备份；早先已删除活动及其状态不变',()=>{const {s,target,source}=fixture();const old=structuredClone(s.registrations.filter(r=>r.eventId===source.id)),deleted=structuredClone(s.events[2]);mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移');assert.deepEqual(s.registrations.filter(r=>r.eventId===source.id),old);assert.deepEqual(s.events[2],deleted);assert.equal(s.events.find(e=>e.id===source.id)!.mergedInto,target.id);assert.equal(s.events.find(e=>e.id===source.id)!.deletedAt,now)});
test('合并前后每人场费不变，短场不会参加长场；费用预览与结算一致',()=>{const {s,target,source}=fixture();const amounts=new Map([...calculateSettlement(s,target,target.end).bills,...calculateSettlement(s,source,source.end).bills].map(b=>[b.playerId,b.court]));mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移');const e=s.events.find(e=>e.id===target.id)!,result=calculateSettlement(s,e,e.end);assert.equal(result.bills.length,10);for(const b of result.bills)assert.equal(b.court,amounts.get(b.playerId));for(const a of attendanceForEvent(s,e).filter(a=>Number(a.playerId.slice(1))>=5))assert.equal(a.end,start+2*hour);const view=projectClubState(s,s.accounts[0],'2030-10',2030,e.end);assert.equal(view.events.length,1);assert.deepEqual(view.drafts[0],result)});
test('候补、取消申请和递补时间保留，不会重新排队或自动晋升',()=>{const {s,target,source}=fixture();const r=s.registrations[9];r.status='waitlist';r.joinedAsWaitlist=true;r.cancelRequested=true;r.promotedAt=now-500;mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移');const row=s.registrations.find(r=>r.eventId===target.id&&r.playerId==='p9')!.bookingSignups![0];assert.equal(row.status,'waitlist');assert.equal(row.cancelRequested,true);assert.equal(row.promotedAt,now-500);assert.equal(row.sequence,5)});
test('仅群主可合并；管理员、不同日期、重复场地、重叠报名、已开始活动均拒绝且不改数据',()=>{for(const kind of ['admin','date','court','overlap','started']){const {s,target,source}=fixture();if(kind==='date')source.start+=86400000;if(kind==='court')s.bookings[1].name='2号场';if(kind==='overlap')s.registrations[5].playerId='p0';if(kind==='started')source.start=now;const before=structuredClone(s);assert.throws(()=>mergeUpcomingActivities(s,s.accounts[kind==='admin'?1:0],target.id,[source.id],now,'迁移'));assert.deepEqual(s,before)}});
test('活动有结算或已完成比赛时保留历史，不允许合并',()=>{for(const kind of ['settlement','match']){const {s,target,source}=fixture();if(kind==='settlement')s.settlements.push({eventId:target.id} as any);else s.matches.push({eventId:source.id,status:'complete'} as any);const before=structuredClone(s);assert.throws(()=>mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移'),/比赛|结算/);assert.deepEqual(s,before)}});
test('原名单不能唯一对应场地时拒绝，避免猜测分配',()=>{const {s,source}=fixture();s.bookings.push({...s.bookings[1],id:'ambiguous',name:'3号场'});assert.throws(()=>upgradeActivitySignups(s,source),/唯一对应/)});
test('同一人在两个不相交时段可合并为一个档案报名；整体人数去重',()=>{const {s,target,source}=fixture();source.start=start+4*hour;source.end=start+6*hour;s.bookings[1].start=source.start;s.bookings[1].end=source.end;for(const r of s.registrations.filter(r=>r.eventId===source.id)){r.arrival=source.start;r.departure=source.end} s.registrations[5].playerId='p0';mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移');const rows=s.registrations.filter(r=>r.eventId===target.id&&r.playerId==='p0');assert.equal(rows.length,1);assert.equal(rows[0].bookingSignups!.length,2);assert.equal(s.registrations.filter(r=>r.eventId===target.id&&r.status==='confirmed').length,9)});
test('恢复合并前来源备份时原报名转为场地名单，合并后的活动保持不变',async()=>{const {s,target,source}=fixture();mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移');const merged=structuredClone(s.registrations.filter(r=>r.eventId===target.id));await apply(s,s.accounts[0],'restoreEvent',{eventId:source.id,reason:'恢复备份'},now+1000);assert.equal(s.events.find(e=>e.id===source.id)!.deletedAt,undefined);assert.ok(s.registrations.filter(r=>r.eventId===source.id).every(r=>r.bookingSignups?.length===1));assert.deepEqual(s.registrations.filter(r=>r.eventId===target.id),merged)});
test('原活动链接指向已合并活动，恢复备份后不再重定向',async()=>{const {s,target,source}=fixture();mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移');let view=projectClubState(s,s.accounts[0],'2030-10',2030,now);assert.equal(view.mergedEventTargets[source.id],target.id);assert.equal(view.deletedEvents.find(e=>e.id===source.id)!.mergedInto,target.id);await apply(s,s.accounts[0],'restoreEvent',{eventId:source.id,reason:'恢复备份'},now+1);view=projectClubState(s,s.accounts[0],'2030-10',2030,now);assert.equal(view.mergedEventTargets[source.id],undefined)});
test('附加费用或分摊模式不同不合并，拒绝时原记录完整保留',()=>{for(const kind of ['cost','mode']){const {s,target,source}=fixture();if(kind==='cost')s.costs.push({eventId:source.id} as any);else source.ballMode='equal';const before=structuredClone(s);assert.throws(()=>mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移'),/费用/);assert.deepEqual(s,before)}});
test('来源预排轮次与比赛原样保留在可恢复备份中',()=>{const {s,target,source}=fixture();s.rounds.push({id:'source-round',eventId:source.id,status:'draft'} as any);s.matches.push({id:'source-match',roundId:'source-round',eventId:source.id,status:'draft'} as any);const rounds=structuredClone(s.rounds),matches=structuredClone(s.matches);mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移');assert.deepEqual(s.rounds,rounds);assert.deepEqual(s.matches,matches)});
test('两场原首位报名者的快速报名统计在场地接龙中保留，不因活动顺序重排丢失',()=>{const {s,target,source}=fixture();mergeUpcomingActivities(s,s.accounts[0],target.id,[source.id],now,'迁移');const view=projectClubState(s,s.accounts[0],'2030-10',2030,now);assert.equal(view.social.personality.find(p=>p.playerId==='p0')!.fastSignup,1);assert.equal(view.social.personality.find(p=>p.playerId==='p5')!.fastSignup,1)});
