import {test} from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,type Event} from '../lib/domain/types';
import {apply} from '../lib/domain/commands';
import {propose,validateRound,readyIds} from '../lib/domain/grouping';
import {bookingAllowsPlayer,venueParticipation} from '../lib/domain/booking-signups';
import {pointsPhases,pointsRoundWindows} from '../lib/domain/points-phases';
import {fixedPartnerTeams,proposeFixed} from '../lib/domain/fixed-partners';
import {rotationPlan} from '../lib/domain/play';
import {calculateSettlement} from '../lib/domain/money';
import {projectClubState} from '../lib/club-view';
const minute=60000,start=Date.parse('2030-10-12T13:00:00Z'),boundary=start+120*minute,end=start+240*minute,now=start-86400000;
function fixture(short=4,long=5){
 const s=emptyState(),e:Event={id:'mixed',creatorId:'host',title:'混合积分赛',start,end,venue:'同一测试球馆',address:'',capacity:6,signupDeadline:start,cancelDeadline:now,note:'',status:'open',courtMode:'interval',ballMode:'interval',attendanceMode:'automatic'};s.events.push(e);s.accounts.push({id:'host',playerId:'s0',role:'member',email:''});
 s.bookings.push({id:'short',eventId:e.id,name:'1号场',start,end:boundary,pricing:'hourly',cents:690,signupCapacity:6},{id:'long',eventId:e.id,name:'2号场',start,end,pricing:'hourly',cents:690,signupCapacity:6});
 for(const [prefix,count,court,departure]of [['s',short,'short',boundary],['l',long,'long',end]] as const)for(let i=0;i<count;i++){const id=prefix+i;s.players.push({id,name:id,ownerId:'host',rating:1000,initialRating:1000,ratedGames:0,enabled:true,ratingReason:''});s.registrations.push({id:'r'+id,eventId:e.id,playerId:id,sequence:i+1,status:'confirmed',arrival:start,departure,note:'',cancelRequested:false,registeredAt:now,joinedAsWaitlist:false,courtExempt:{mode:'none',reason:''},ballExempt:{mode:'none',reason:''},bookingSignups:[{bookingId:court,status:'confirmed',arrival:start,departure,sequence:i+1,note:'',registeredAt:now,joinedAsWaitlist:false,cancelRequested:false}]})}
 const plan=(pairing='rotate',overrides={})=>apply(s,s.accounts[0],'planPoints',{eventId:e.id,at:start,pointsMinutes:210,roundMinutes:25,pairing,seed:7,...overrides},now);
 return {s,e,plan};
}
test('两种报名时段共同9人池，长场成员可到短场；17点后仅5人一场',()=>{const {s,e}=fixture();assert.ok(bookingAllowsPlayer(s,e.id,'short','l0',start,start+25*minute));const p=propose(s,e,start,25,7);assert.equal(p.eligible.length,9);assert.equal(p.courts.length,2);assert.equal(p.rest.length,1);assert.ok(p.courts.some(m=>new Set([...m.a,...m.b].map(id=>id[0])).size===2));validateRound(s,e.id,start,25,p.courts as any);const later=propose(s,e,boundary,25,7);assert.equal(later.eligible.length,5);assert.equal(later.courts.length,1);assert.equal(later.courts[0].courtId,'long');assert.equal(later.rest.length,1);assert.ok(later.eligible.every(id=>id.startsWith('l')))});
test('每场只有3人时共同6人仍能排一场双打，无重复球友',()=>{const {s,e}=fixture(3,3),p=propose(s,e,start,20,3);assert.equal(p.courts.length,1);assert.equal(p.rest.length,2);assert.equal(new Set(p.courts.flatMap(m=>[...m.a,...m.b])).size,4)});
test('25分钟赛程在16:40–17:00缩为20分钟，然后17点重新起轮',async()=>{const {s,e,plan}=fixture();await plan();const before=s.rounds.filter(r=>r.start<boundary),after=s.rounds.filter(r=>r.start>=boundary);assert.deepEqual(before.map(r=>r.duration),[25,25,25,25,20]);assert.equal(after[0].start,boundary);for(const r of s.rounds){assert.ok(r.start+r.duration*minute<=e.pointsPlan!.end);assert.ok(!(r.start<boundary&&r.start+r.duration*minute>boundary));assert.equal(s.matches.filter(m=>m.roundId===r.id).length,r.start<boundary?2:1);assert.equal(r.eligible.length,r.start<boundary?9:5)}});
test('15:10开始每轮20分钟，16:50–17:00只安排10分钟，不提前减少人数与场地',async()=>{const {s,plan}=fixture();await plan('rotate',{at:start+10*minute,pointsMinutes:200,roundMinutes:20});const last=s.rounds.find(r=>r.start===boundary-10*minute)!;assert.equal(last.duration,10);assert.equal(last.eligible.length,9);assert.equal(s.matches.filter(m=>m.roundId===last.id).length,2);assert.ok(s.rounds.some(r=>r.start===boundary))});
test('不足5分钟尾段只合到本区段前一轮，不越17点边界',()=>{const {s,e}=fixture();const windows=pointsRoundWindows(s,e,start,boundary+92*minute,30);assert.deepEqual(windows.filter(r=>r.start>=boundary).map(r=>r.duration),[30,30,32]);assert.ok(windows.every(r=>!(r.start<boundary&&r.start+r.duration*minute>boundary)))});
test('中途到场人数变化单独切轮，晚到、候补、停用不提前进池',async()=>{const {s,e,plan}=fixture();const late=s.registrations.find(r=>r.playerId==='l0')!;late.arrival=start+30*minute;late.bookingSignups![0].arrival=late.arrival;s.registrations.find(r=>r.playerId==='l1')!.bookingSignups![0].status='waitlist';s.registrations.find(r=>r.playerId==='l1')!.status='waitlist';s.players.find(p=>p.id==='l2')!.enabled=false;await plan('rotate',{roundMinutes:20,pointsMinutes:120});for(const r of s.rounds){assert.ok(!r.eligible.includes('l1')&&!r.eligible.includes('l2'));if(r.start<late.arrival){assert.ok(!r.eligible.includes('l0'));assert.ok(r.start+r.duration*minute<=late.arrival)}}assert.ok(!readyIds(s,e.id,start).includes('l0'))});
test('发布、跨场调整与开赛均接受同球馆混合成员，但离场后不能继续用短场',async()=>{const {s,e,plan}=fixture();await plan('rotate',{pointsMinutes:30,roundMinutes:15});const r=s.rounds[0],ms=s.matches.filter(m=>m.roundId===r.id);await apply(s,s.accounts[0],'swap',{roundId:r.id,p1:ms[0].a[0],p2:ms[1].a[0]},now);await apply(s,s.accounts[0],'publishPoints',{eventId:e.id},now);await apply(s,s.accounts[0],'start',{roundId:r.id,at:r.start,monthly:true,elo:true},now);assert.equal(r.status,'playing');const bad={...ms[0],courtId:'short'};assert.throws(()=>validateRound(s,e.id,boundary,15,[bad] as any),/参加时段|场地/)});
test('固定搭档优先相近参加时间，短场结束后仍至少有两队完整长时搭档',async()=>{const {s,e,plan}=fixture();for(const p of s.players)p.rating=p.id.startsWith('s')?2000:500;const teams=fixedPartnerTeams(s,e);assert.ok(teams.filter(t=>t.every(id=>id.startsWith('l'))).length>=2);const later=proposeFixed(s,e,boundary,25,7,teams);assert.equal(later.courts.length,1);await plan('fixed');for(const r of s.rounds.filter(r=>r.start>=boundary))assert.equal(s.matches.filter(m=>m.roundId===r.id).length,1)});
test('同球馆相接报名区间可完整覆盖一轮，真正空档或跨球馆不能拼接',()=>{const {s,e}=fixture();const r=s.registrations.find(r=>r.playerId==='s0')!;r.bookingSignups![0].departure=start+60*minute;r.bookingSignups!.push({...r.bookingSignups![0],bookingId:'long',arrival:start+60*minute,departure:boundary});assert.ok(bookingAllowsPlayer(s,e.id,'long',r.playerId,start+50*minute,start+70*minute));assert.equal(venueParticipation(s,e,r).length,1);r.bookingSignups![1].arrival=start+65*minute;assert.ok(!bookingAllowsPlayer(s,e.id,'long',r.playerId,start+50*minute,start+70*minute));r.bookingSignups![1].arrival=start+60*minute;s.bookings[1].venue='另外一个球馆';assert.ok(!bookingAllowsPlayer(s,e.id,'short',r.playerId,start+50*minute,start+70*minute));assert.equal(venueParticipation(s,e,r).length,2)});
test('多球馆同名场地不混排，轮转可用场地计数与排场一致',()=>{const {s,e}=fixture();s.bookings[1].venue='第二测试球馆';s.bookings[1].name='1号场';const p=propose(s,e,start,20,7);assert.equal(p.courts.length,2);for(const m of p.courts)assert.ok([...m.a,...m.b].every(id=>m.courtId==='short'?id.startsWith('s'):id.startsWith('l')));assert.equal(rotationPlan(s,e,start,20).availableCourts,2)});
test('阶段说明准确显示9人两场到5人一场，费用与报名记录不因混排改变',async()=>{const {s,e,plan}=fixture();const before=structuredClone(s.registrations),fees=calculateSettlement(s,e,end);const phases=pointsPhases(s,e,start,end);assert.deepEqual(phases.map(p=>[p.start,p.end,p.players.length,p.courts.length,p.playing,p.rest]),[[start,boundary,9,2,8,1],[boundary,end,5,1,4,1]]);await plan();assert.deepEqual(s.registrations,before);assert.deepEqual(calculateSettlement(s,e,end),fees)});
test('不可排的短区段或场地缺失不保存半份赛程，48轮限制保持有界',async()=>{const {s,e,plan}=fixture();await plan();const previous=structuredClone(s);await assert.rejects(()=>plan('rotate',{at:boundary-3*minute,pointsMinutes:60}),/不足5分钟/);assert.deepEqual(s,previous);s.bookings[1].end=boundary;const old=structuredClone(s);await assert.rejects(()=>plan(),/无法安排/);assert.deepEqual(s,old);e.end=start+365*24*60*minute;assert.throws(()=>pointsRoundWindows(s,e,start,e.end,5),/最多预排48轮/)});
test('未来赛程预览9人两场，不冒充已到场；17点后实时5人一场',()=>{const {s,e}=fixture();const data=projectClubState(s,s.accounts[0],'2030-10',2030,now);assert.equal(data.rotationPlans[e.id].players,0);const phase=pointsPhases(data as any,e,start,end)[0];assert.equal(phase.players.length,9);assert.equal(phase.usedCourts,2);const live=projectClubState(s,s.accounts[0],'2030-10',2030,boundary).rotationPlans[e.id];assert.equal(live.players,5);assert.equal(live.usedCourts,1)});
