// Isolated SQLite/D1 + real WebCrypto integration; never contacts a push vendor.
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
mkdirSync('.test-output',{recursive:true});
globalThis.__pushTest={env:{},user:null};
const fixture=globalThis.__pushTest;
writeFileSync('.test-output/push-entry.ts',`export {GET,POST} from '../app/api/notifications/route';export {POST as logout} from '../app/api/auth/route';export {signupPushStatements,flushPushOutbox} from '../lib/push-outbox';export {load,save} from '../lib/store';export {clubReminderStatements} from '../lib/reminder-store';export {pushSubscriptionId} from '../lib/push-subscriptions';`);
await build({entryPoints:['.test-output/push-entry.ts'],bundle:true,platform:'node',format:'esm',outfile:'.test-output/push-api-bundle.mjs',plugins:[{name:'isolated-push',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'push-fixture'}));b.onResolve({filter:/(?:^|\/)auth$/},()=>({path:'auth',namespace:'push-fixture'}));b.onLoad({filter:/.*/,namespace:'push-fixture'},a=>({contents:a.path==='env'?'export const env=globalThis.__pushTest.env;':"export const getAppUser=async()=>globalThis.__pushTest.user;export const hashToken=async()=> 'fixture-hash';export const passwordEnabled=async()=>false;export const sessionCookie='fixture_session';",loader:'js'}))}}]});
const api=await import(pathToFileURL(resolve('.test-output/push-api-bundle.mjs')).href);
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+name,'utf8'));
function statement(query,parameters=[]){return {query,parameters,bind(...args){return statement(query,args)},async first(){return sql.prepare(query).get(...parameters)??null},async all(){return {results:sql.prepare(query).all(...parameters)}},async run(){const result=sql.prepare(query).run(...parameters);return {meta:{changes:Number(result.changes)},results:[]}}}}
const db={prepare:statement,async batch(list){sql.exec('BEGIN');try{const values=[];for(const s of list)values.push(/^SELECT/i.test(s.query.trim())?await s.all():await s.run());sql.exec('COMMIT');return values}catch(e){sql.exec('ROLLBACK');throw e}}};
fixture.env.DB=db;
const encode=bytes=>Buffer.from(bytes).toString('base64url'),decode=value=>new Uint8Array(Buffer.from(value,'base64url'));
const vapid=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']),vapidJwk=await crypto.subtle.exportKey('jwk',vapid.privateKey);
fixture.env.PUSH_VAPID_PUBLIC_KEY=encode(await crypto.subtle.exportKey('raw',vapid.publicKey));fixture.env.PUSH_VAPID_PRIVATE_KEY=vapidJwk.d;fixture.env.PUSH_VAPID_SUBJECT='https://club.example';
const receiver=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),clientPublic=new Uint8Array(await crypto.subtle.exportKey('raw',receiver.publicKey)),auth=crypto.getRandomValues(new Uint8Array(16));
const subscription=token=>({endpoint:'https://fcm.googleapis.com/fcm/send/'+token,expirationTime:null,keys:{p256dh:encode(clientPublic),auth:encode(auth)}});
function user(id){fixture.user=id?{userId:id,displayName:id,method:'password'}:null}
function insert(table,id,payload,extra={}){const values={id,...extra,payload:JSON.stringify(payload)},keys=Object.keys(values);sql.prepare(`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).run(...Object.values(values))}
const rules={win:3,loss:0,minimum:0,cap:12,target:21,ceiling:30,lead:2,k:32,algorithm:'doubles-elo-v1'};
insert('settings','club',{name:'虚构通知群',initialized:true,inviteHash:'',rules,ownerAccountId:'a'});
for(const id of ['a','b','c','d']){insert('players','p'+id,{id:'p'+id,name:id,enabled:true,ownerId:id,initialRating:1000,rating:1000,ratedGames:0,ratingReason:''},{owner_id:id});insert('accounts',id,{id,email:'',role:id==='a'?'admin':'member',playerId:'p'+id},{email:'',role:id==='a'?'admin':'member',player_id:'p'+id})}
const post=(owner,action,detail={},origin='https://club.example')=>api.POST(new Request('https://club.example/api/notifications',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({accountId:owner,action,...detail})}));
let captures=[],deliveryStatus=201;const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,request)=>{captures.push({url,request});return new Response(null,{status:deliveryStatus})};
async function hkdf(ikm,salt,info,length){const key=await crypto.subtle.importKey('raw',ikm,'HKDF',false,['deriveBits']);return new Uint8Array(await crypto.subtle.deriveBits({name:'HKDF',hash:'SHA-256',salt,info},key,length*8))}
async function decrypt(request){
 const bytes=new Uint8Array(request.body),salt=bytes.slice(0,16),serverPublic=bytes.slice(21,21+bytes[20]);
 const serverKey=await crypto.subtle.importKey('raw',serverPublic,{name:'ECDH',namedCurve:'P-256'},false,[]),secret=await crypto.subtle.deriveBits({name:'ECDH',public:serverKey},receiver.privateKey,256),utf8=s=>new TextEncoder().encode(s);
 const info=new Uint8Array([...utf8('WebPush: info\0'),...clientPublic,...serverPublic]),ikm=await hkdf(secret,auth,info,32),cek=await hkdf(ikm,salt,utf8('Content-Encoding: aes128gcm\0'),16),nonce=await hkdf(ikm,salt,utf8('Content-Encoding: nonce\0'),12);
 const key=await crypto.subtle.importKey('raw',cek,'AES-GCM',false,['decrypt']),plaintext=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:nonce},key,bytes.slice(21+bytes[20])));let end=plaintext.length-1;while(plaintext[end]===0)end--;assert.equal(plaintext[end],2);return JSON.parse(new TextDecoder().decode(plaintext.slice(0,end)));
}
try{
 user(null);assert.equal((await api.GET()).status,401);user('outside');assert.equal((await api.GET()).status,403);user('a');
 const publicResponse=await api.GET(),publicData=await publicResponse.json();assert.equal(publicData.configured,true);assert.equal(publicData.publicKey,fixture.env.PUSH_VAPID_PUBLIC_KEY);assert.ok(!JSON.stringify(publicData).includes(fixture.env.PUSH_VAPID_PRIVATE_KEY));assert.equal(publicResponse.headers.get('Cache-Control'),'no-store');
 assert.equal((await post('a','subscribe',{subscription:subscription('a')},'https://evil.example')).status,403);assert.equal((await post('b','subscribe',{subscription:subscription('a')})).status,409);
 assert.equal((await post('a','subscribe',{subscription:{...subscription('a'),endpoint:'https://localhost/private'}})).status,400);
 assert.equal((await post('a','subscribe',{subscription:{...subscription('a'),keys:{...subscription('a').keys,p256dh:'A'.repeat(87)}}})).status,400);
 assert.equal((await post('a','subscribe',{subscription:subscription('a')})).status,200);for(let i=1;i<5;i++)assert.equal((await post('a','subscribe',{subscription:subscription('a'+i)})).status,200);assert.equal((await post('a','subscribe',{subscription:subscription('too-many')})).status,409);
 user('b');assert.equal((await post('b','subscribe',{subscription:subscription('b')})).status,200);assert.equal((await post('b','subscribe',{subscription:subscription('a')})).status,409);
 user('a');assert.equal((await post('a','status',{endpoint:subscription('b').endpoint})).status,200);assert.deepEqual(await (await post('a','status',{endpoint:subscription('b').endpoint})).json(),{enabled:false,resetDevice:true});
 assert.equal((await post('a','unsubscribe',{endpoint:subscription('b').endpoint})).status,200);assert.ok(sql.prepare('SELECT id FROM push_subscriptions WHERE account_id=?').get('b'));assert.equal((await post('a','test',{endpoint:subscription('b').endpoint})).status,409);assert.equal(captures.length,0);
 user('b');assert.equal((await post('b','test',{endpoint:subscription('b').endpoint})).status,200);assert.equal(captures.length,1);const request=captures[0].request;
 assert.equal(request.redirect,'manual');assert.equal(request.headers['content-encoding'],'aes128gcm');assert.equal(request.headers.ttl,'86400');assert.equal(request.body.byteLength,4096);const text=await decrypt(request);assert.equal(text.kind,'test');assert.match(text.body,/新接龙/);
 const token=request.headers.authorization.match(/t=([^, ]+)/)[1],parts=token.split('.'),claims=JSON.parse(Buffer.from(parts[1],'base64url'));assert.equal(claims.aud,'https://fcm.googleapis.com');assert.equal(claims.sub,'https://club.example');assert.equal(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},vapid.publicKey,decode(parts[2]),new TextEncoder().encode(parts[0]+'.'+parts[1])),true);
 assert.equal((await post('b','test',{endpoint:subscription('b').endpoint})).status,200);assert.equal((await post('b','test',{endpoint:subscription('b').endpoint})).status,200);assert.equal((await post('b','test',{endpoint:subscription('b').endpoint})).status,429);
 user('c');assert.equal((await post('c','subscribe',{subscription:subscription('c')})).status,200);
 const previous=await api.load(),next=structuredClone(previous),now=Date.now();const event={id:'push-event',title:'虚构通知验收',creatorId:'a',start:now+3600000,end:now+7200000,venue:'虚构球馆',address:'',capacity:8,signupDeadline:now,cancelDeadline:now,note:'',status:'open',courtMode:'equal',ballMode:'equal'};next.events.push(event);
 await api.save(next,'first-open',previous,api.signupPushStatements(next,previous,'a','first-open','event',now));assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM push_jobs').get().n,1);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM push_deliveries').get().n,2);
 user('d');assert.equal((await post('d','subscribe',{subscription:subscription('d')})).status,200);assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM push_deliveries').get().n,2);
 const disabled={...JSON.parse(sql.prepare('SELECT payload FROM players WHERE id=?').get('pc').payload),enabled:false};sql.prepare('UPDATE players SET payload=? WHERE id=?').run(JSON.stringify(disabled),'pc');
 captures=[];await Promise.all([api.flushPushOutbox(fixture.env),api.flushPushOutbox(fixture.env)]);assert.equal(captures.length,1);assert.equal(captures[0].url,subscription('b').endpoint);assert.equal((await decrypt(captures[0].request)).eventId,'push-event');assert.equal(sql.prepare("SELECT COUNT(*) AS n FROM push_deliveries WHERE state='sent'").get().n,1);assert.equal(sql.prepare("SELECT COUNT(*) AS n FROM push_deliveries WHERE state='cancelled'").get().n,1);
 await api.flushPushOutbox(fixture.env);assert.equal(captures.length,1);
 const before=await api.load(),reopened=structuredClone(before);before.events[0].status='draft';reopened.events[0].status='open';await api.save(reopened,'reopen',before,api.signupPushStatements(reopened,before,'a','reopen','eventStatus'));assert.equal(sql.prepare('SELECT COUNT(*) AS n FROM push_deliveries').get().n,2);
 const rollbackBefore=await api.load(),rollback=structuredClone(rollbackBefore);rollback.events.push({...event,id:'must-rollback'});await assert.rejects(()=>api.save(rollback,'first-open',rollbackBefore,api.signupPushStatements(rollback,rollbackBefore,'a','rollback-key','event')),/UNIQUE/);assert.equal(sql.prepare('SELECT id FROM push_jobs WHERE id=?').get('must-rollback'),undefined);
 const expiredBefore=await api.load(),expired=structuredClone(expiredBefore);expired.events.push({...event,id:'expired-device'});await api.save(expired,'expired-open',expiredBefore,api.signupPushStatements(expired,expiredBefore,'a','expired-open','event'));deliveryStatus=410;await api.flushPushOutbox(fixture.env);assert.equal(sql.prepare('SELECT id FROM push_subscriptions WHERE account_id=?').get('b'),undefined);assert.equal(sql.prepare('SELECT id FROM push_subscriptions WHERE account_id=?').get('d'),undefined);
 user('d');assert.equal((await post('d','subscribe',{subscription:subscription('retry')})).status,200);const retryBefore=await api.load(),retry=structuredClone(retryBefore);retry.events.push({...event,id:'retry-event'});await api.save(retry,'retry-open',retryBefore,api.signupPushStatements(retry,retryBefore,'a','retry-open','event'));deliveryStatus=503;await api.flushPushOutbox(fixture.env);let pending=sql.prepare("SELECT * FROM push_deliveries WHERE job_id='retry-event' AND state='retry'").get();assert.equal(pending.attempts,1);
 sql.prepare('UPDATE push_deliveries SET next_at=0 WHERE id=?').run(pending.id);deliveryStatus=201;await api.flushPushOutbox(fixture.env);assert.equal(sql.prepare('SELECT state FROM push_deliveries WHERE id=?').get(pending.id).state,'sent');
 const cancelledBefore=await api.load(),cancelled=structuredClone(cancelledBefore);cancelled.events.push({...event,id:'unsubscribe-event'});await api.save(cancelled,'unsubscribe-open',cancelledBefore,api.signupPushStatements(cancelled,cancelledBefore,'a','unsubscribe-open','event'));assert.equal((await post('d','unsubscribe',{endpoint:subscription('retry').endpoint})).status,200);assert.equal(sql.prepare("SELECT COUNT(*) AS n FROM push_deliveries d JOIN push_subscriptions s ON s.id=d.subscription_id WHERE s.account_id='d'").get().n,0);
 assert.equal((await post('d','subscribe',{subscription:subscription('logout')})).status,200);sql.prepare('INSERT INTO auth_sessions(id,user_id,expires) VALUES(?,?,?)').run('fixture-hash','d',Date.now()+3600000);const ownEndpoint=subscription('logout').endpoint;
 const logout=await api.logout(new Request('https://club.example/api/auth',{method:'POST',headers:{origin:'https://club.example','content-type':'application/json',cookie:'fixture_session='+'x'.repeat(43)},body:JSON.stringify({action:'logout',pushEndpoint:ownEndpoint})}));assert.equal(logout.status,200);assert.equal(sql.prepare("SELECT COUNT(*) AS n FROM push_subscriptions WHERE account_id='d'").get().n,0);assert.equal(sql.prepare("SELECT COUNT(*) AS n FROM push_subscriptions WHERE account_id='a'").get().n,5);assert.equal(sql.prepare('SELECT id FROM auth_sessions WHERE id=?').get('fixture-hash'),undefined);

 user('d');assert.equal((await post('d','subscribe',{subscription:subscription('center-device')})).status,200);
 const centerBefore=await api.load(),centerBase=structuredClone(centerBefore);centerBase.events.push({...event,id:'center-event',status:'locked'});await api.save(centerBase,'center-base',centerBefore);
 const registered=structuredClone(centerBase);registered.registrations.push({id:'center-reg',eventId:'center-event',playerId:'pd',status:'confirmed',sequence:1,arrival:event.start,departure:event.end,note:'',cancelRequested:false,courtExempt:{mode:'none',reason:''},ballExempt:{mode:'none',reason:''}});
 await api.save(registered,'center-register',centerBase,api.clubReminderStatements(registered,centerBase,'d','center-register','register'));
 await assert.rejects(()=>api.save(registered,'center-register',centerBase,api.clubReminderStatements(registered,centerBase,'d','center-register','register')));
 const allOff={signup:false,registration:false,changes:false,matches:false,fees:false,awards:false,upcoming:false};
 assert.equal((await post('d','preferences',{preferences:allOff})).status,200);captures=[];await api.flushPushOutbox(fixture.env);assert.equal(captures.length,0);
 const center=await (await api.GET()).json();assert.equal(center.preferences.registration,false);assert.equal(center.items.length,1);assert.equal(center.items[0].kind,'registration');assert.ok(!('accountIds' in center.items[0]));assert.ok(!('playerId' in center.items[0]));const noticeId=center.items[0].id;
 user('a');assert.equal((await post('a','read',{id:noticeId})).status,200);assert.equal(sql.prepare('SELECT read_at FROM reminder_inbox WHERE id=?').get(noticeId).read_at,null);assert.equal((await post('d','preferences',{preferences:allOff})).status,409);
 user('d');assert.equal((await post('d','read',{id:noticeId})).status,200);assert.ok(sql.prepare('SELECT read_at FROM reminder_inbox WHERE id=?').get(noticeId).read_at);assert.equal((await post('d','preferences',{preferences:{...allOff,unknown:true}})).status,400);
 assert.equal((await post('d','preferences',{preferences:{...allOff,registration:true}})).status,200);
 const wait=structuredClone(registered);wait.registrations[0].status='waitlist';await api.save(wait,'center-wait',registered,api.clubReminderStatements(wait,registered,'d','center-wait','register'));captures=[];await api.flushPushOutbox(fixture.env);assert.equal(captures.length,1);const delivered=await decrypt(captures[0].request);assert.equal(delivered.kind,'registration');assert.equal(delivered.eventId,'center-event');
 console.log('PASS reminder center: recipient isolation, no private recipient IDs in API, same-request rollback, preference suppression and re-enable, ownership-only reads and preferences, actual encrypted personal reminder');
 console.log('PASS Web Push: authenticated opt-in, device ownership/limits, CSRF/SSRF, real aes128gcm decryption and VAPID signature, atomic recipient snapshot/rollback, concurrent claims, no reopening duplicates, disabled members and expired-device cleanup');
}finally{globalThis.fetch=originalFetch;sql.close();delete globalThis.__pushTest}
