import {test} from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,type Event,type Registration} from '../lib/domain/types';
import {remindersForChange,upcomingReminders} from '../lib/reminder-contract';
const now=Date.parse('2026-10-06T12:00:00Z');
function fixture(){const s=emptyState();s.accounts=['owner','one','two','outside'].map(id=>({id,email:'',role:id==='owner'?'admin' as const:'member' as const,playerId:'p'+id}));s.players=s.accounts.map(a=>({id:a.playerId,name:a.id,ownerId:a.id,initialRating:1000,rating:1000,ratedGames:0,enabled:true,ratingReason:''}));const e:Event={id:'event',title:'周末球局',start:now+3600000,end:now+3*3600000,creatorId:'owner',venue:'球馆',address:'地址',capacity:12,signupDeadline:now+3*3600000,cancelDeadline:now,note:'',status:'open',courtMode:'interval',ballMode:'interval'};s.events=[e];s.bookings=[{id:'court1',eventId:e.id,name:'1号场',start:e.start,end:e.end,pricing:'hourly',cents:1200}];return s;}
const registration=(status:Registration['status']='confirmed'):Registration=>({id:'reg',eventId:'event',playerId:'pone',sequence:1,status,arrival:now+3600000,departure:now+7200000,note:'',cancelRequested:false,courtExempt:{mode:'none',reason:''},ballExempt:{mode:'none',reason:''},bookingSignups:[{bookingId:'court1',status,sequence:1,arrival:now+3600000,departure:now+7200000,note:'',cancelRequested:false,registeredAt:now,joinedAsWaitlist:status==='waitlist'}]});
test('court promotion targets only its player even when aggregate registration was already confirmed',()=>{const before=fixture();before.registrations=[registration('waitlist')];before.registrations[0].status='confirmed';const after=structuredClone(before);after.registrations[0].bookingSignups![0].status='confirmed';const notices=remindersForChange(after,before,'owner','request',now);assert.equal(notices.length,1);assert.match(notices[0].title,/候补转正/);assert.deepEqual(notices[0].accountIds,['one']);assert.equal(notices[0].bookingId,'court1');assert.equal(remindersForChange(after,after,'owner','no-op',now).length,0)});
test('important booking edits and cancellation notify affected players, never onlookers or broadcast every edit',()=>{const before=fixture();before.registrations=[registration()];const after=structuredClone(before);after.bookings[0].venue='新球馆';let notices=remindersForChange(after,before,'owner','edit',now);assert.deepEqual(notices[0].accountIds,['one']);after.events[0].status='cancelled';notices=remindersForChange(after,before,'owner','cancel',now);assert.equal(notices.filter(n=>n.kind==='changes').length,1);assert.equal(remindersForChange(after,after,'owner','later',now).length,0);after.events[0].status='open';after.bookings=structuredClone(before.bookings);after.events[0].note='普通文案编辑';assert.equal(remindersForChange(after,before,'owner','note',now).length,0)});
test('new confirmed settlement alerts only people with bills and never exposes the amount on the lock screen',()=>{const before=fixture(),after=structuredClone(before);after.settlements=[{id:'bill',eventId:'event',version:1,created:now,reason:'确认',confirmed:true,total:1000,subsidy:0,unallocated:0,bills:[{playerId:'pone',court:1000,ball:0,other:0,total:1000,minutes:60}],detail:[]}];const notice=remindersForChange(after,before,'owner','settle',now)[0];assert.equal(notice.kind,'fees');assert.deepEqual(notice.accountIds,['one']);assert.equal(notice.tab,'fees');assert.doesNotMatch(notice.body,/1000/);after.settlements[0].confirmed=false;assert.equal(remindersForChange(after,before,'owner','draft',now).length,0)});
test('upcoming reminders use individual court arrival and exclude waitlist, canceled, ended and other accounts',()=>{const s=fixture();s.events[0].start=now-3600000;s.registrations=[registration()];const notices=upcomingReminders(s,'one',now);assert.equal(notices.length,1);assert.equal(notices[0].expires,now+3600000);assert.equal(upcomingReminders(s,'outside',now).length,0);assert.equal(upcomingReminders(s,'one',now+3600000).length,0);s.registrations[0].bookingSignups![0].status='waitlist';assert.equal(upcomingReminders(s,'one',now).length,0);s.registrations=[registration()];s.events[0].status='cancelled';assert.equal(upcomingReminders(s,'one',now).length,0)});
test('a new signup and all inbox identities are stable for an identical request',()=>{const before=fixture(),after=structuredClone(before);before.events=[];const n=remindersForChange(after,before,'owner','same',now)[0];assert.equal(n.kind,'signup');assert.deepEqual(n.accountIds,['one','two','outside']);after.registrations=[registration()];assert.deepEqual(remindersForChange(after,before,'owner','same',now),remindersForChange(after,before,'owner','same',now))});
