// Real API/store against isolated in-memory SQLite; no production grants.
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {build} from 'esbuild';
mkdirSync('.test-output',{recursive:true});
const fixture=globalThis.__settlementTest={env:{},user:null};
writeFileSync('.test-output/settlement-entry.ts',`export {GET,POST} from '../app/api/club/route';export {load,save,committed} from '../lib/store';export {emptyState} from '../lib/domain/types';export {settlementView} from '../lib/domain/settlement-state';`);
await build({entryPoints:['.test-output/settlement-entry.ts'],bundle:true,platform:'node',format:'esm',outfile:'.test-output/settlement-api-bundle.mjs',plugins:[{name:'isolated-grants',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'award-fixture'}));b.onResolve({filter:/(?:^|\/)auth$/},()=>({path:'auth',namespace:'award-fixture'}));b.onLoad({filter:/.*/,namespace:'award-fixture'},a=>({contents:a.path==='env'?'export const env=globalThis.__settlementTest.env;':'export const getAppUser=async()=>globalThis.__settlementTest.user;export const passwordEnabled=async()=>true;',loader:'js'}))}}]});
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(readFileSync('drizzle/'+f,'utf8'));
function statement(query,parameters=[]){return {query,parameters,bind(...args){return statement(query,args)},async first(){return sql.prepare(query).get(...parameters)??null},async all(){return {results:sql.prepare(query).all(...parameters)}},async run(){const r=sql.prepare(query).run(...parameters);return {meta:{changes:Number(r.changes)},results:[]}}}}
fixture.env.DB={prepare:statement,async batch(list){sql.exec('BEGIN');try{const values=list.map(s=>/^SELECT/i.test(s.query.trim())?{results:sql.prepare(s.query).all(...s.parameters)}:{meta:{changes:Number(sql.prepare(s.query).run(...s.parameters).changes)},results:[]});sql.exec('COMMIT');return values}catch(e){sql.exec('ROLLBACK');throw e}}};
const api=await import(pathToFileURL(resolve('.test-output/settlement-api-bundle.mjs')).href);


try{
 const empty=api.emptyState(),s=api.emptyState(),now=Date.now();s.settings.initialized=true;s.settings.ownerAccountId='owner';s.settings.progressionVersion='weekly-v2';s.settings.rankingVersion='signed-v1';s.settings.scoringPolicy='all-ranked-v1';
 s.accounts=['owner','host','member'].map((id,i)=>({id,email:'',role:i?'member':'admin',playerId:'p'+i}));s.players=s.accounts.map(a=>({id:a.playerId,name:'Fictional '+a.playerId,ownerId:a.id,initialRating:1000,rating:1000,ratedGames:0,enabled:true,ratingReason:''}));
 const e={id:'event',creatorId:'host',title:'Fictional split',start:now-10800000,end:now-3600000,venue:'Fictional',address:'',capacity:6,signupDeadline:now,cancelDeadline:now,note:'',status:'open',attendanceMode:'automatic',courtMode:'interval',ballMode:'interval'};s.events=[e];s.bookings.push({id:'court',eventId:e.id,name:'Court',start:e.start,end:e.end,pricing:'total',cents:1200});s.registrations=s.players.slice(1).map((p,i)=>({id:'r'+i,eventId:e.id,playerId:p.id,sequence:i+1,status:'confirmed',arrival:e.start,departure:e.end,note:'',cancelRequested:false,courtExempt:{mode:'none',reason:''},ballExempt:{mode:'none',reason:''}}));await api.save(s,'seed',empty);
 const origin='https://club.example',signIn=id=>fixture.user={userId:id,method:'password',displayName:id};const post=async(action,payload,id=crypto.randomUUID())=>{const state=await api.load();return api.POST(new Request(origin+'/api/club',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({action,payload,requestId:id,actor:fixture.user.userId,revision:state.revision})}))};const settle={eventId:e.id,confirmed:true,reason:'Confirmed split'};
 signIn('member');assert.equal((await post('settle',settle)).status,403);signIn('host');const requestId=crypto.randomUUID();assert.equal((await post('settle',settle,requestId)).status,200);assert.equal((await post('settle',settle,requestId)).status,200);assert.equal((await post('settle',{...settle,reason:'Repeated click'})).status,200);let state=await api.load();assert.equal(state.settlements.length,1);assert.equal(state.settlements[0].total,1200);assert.equal(state.settlements[0].bills.length,2);
 const view=await (await api.GET(new Request(origin+'/api/club?month=2026-10&year=2026'))).json();assert.equal(api.settlementView(view.drafts[0],view.settlements,true).confirmed,true);
 assert.equal((await post('cost',{eventId:e.id,type:'other',name:'Fictional added cost',pricing:'total',cents:200,tubeCount:1,used:1,start:null,end:null,bearer:'members',reason:'Actual revised cost'})).status,200);const first=structuredClone(state.settlements[0]);let updated=await (await api.GET(new Request(origin+'/api/club?month=2026-10&year=2026'))).json();assert.equal(api.settlementView(updated.drafts[0],updated.settlements,true).changed,true);assert.equal(api.settlementView(updated.drafts[0],updated.settlements,false).shown.total,1200);
 assert.equal((await post('settle',{...settle,reason:'Confirmed revision'})).status,200);state=await api.load();assert.equal(state.settlements.length,2);assert.deepEqual(state.settlements[0],first);assert.equal(state.settlements[1].total,1400);assert.equal(state.settlements[1].version,2);
 assert.equal((await post('feeRecipient',{eventId:e.id,name:'Fictional recipient',phone:'+34 610 000 000',reason:'Transfer contact'})).status,200);signIn('member');const member=await (await api.GET(new Request(origin+'/api/club?month=2026-10&year=2026'))).json();assert.equal(member.events[0].feeRecipient.phone,'+34 610 000 000');assert.equal((await post('feeRecipient',{eventId:e.id,name:'Attacker',phone:'610000000',reason:'Forbidden'})).status,403);signIn('host');
 const before=await api.load(),rollback=structuredClone(before);rollback.settlements=[];await assert.rejects(()=>api.save(rollback,'host:'+requestId,before),/UNIQUE/);assert.deepEqual((await api.load()).settlements,before.settlements);
 console.log('PASS settlement API: actual SQLite confirmation, creator/member permissions, repeated request and same-result deduplication, visible saved state, revised snapshot, preserved history and rollback');
}finally{sql.close();delete globalThis.__settlementTest}
