import {test} from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,type Event,type Cost} from '../lib/domain/types';
import {ballCents,legacyTubeUnitCents,calculateSettlement} from '../lib/domain/money';
import {apply} from '../lib/domain/commands';
const start=Date.parse('2026-10-04T13:00:00Z'),hour=3600000;
function fixture(n=4){const s=emptyState();s.settings.initialized=true;const e:Event={id:'event',title:'虚构耗球',start,end:start+3*hour,venue:'虚构球馆',address:'',capacity:20,signupDeadline:start+3*hour,cancelDeadline:start+3*hour,note:'',status:'live',courtMode:'interval',ballMode:'interval'};s.events.push(e);for(let i=0;i<n;i++){const id=String.fromCharCode(65+i);s.players.push({id,ownerId:'admin',name:id,initialRating:1000,rating:1000,ratedGames:0,enabled:true,ratingReason:'测试'});s.registrations.push({id:'reg'+id,eventId:e.id,playerId:id,sequence:i+1,status:'confirmed',arrival:start,departure:e.end,note:'',cancelRequested:false,courtExempt:{mode:'none',reason:''},ballExempt:{mode:'none',reason:''}});s.attendance.push({id:'at'+id,eventId:e.id,playerId:id,start:i===3?start+hour:start,end:e.end,state:'ready'})}s.accounts.push({id:'admin',email:'fake@test.invalid',role:'admin',playerId:'A'});s.bookings.push({id:'court1',eventId:e.id,name:'1号场',start,end:e.end,pricing:'total',cents:0});return {s,e}}
const ball=(input:Record<string,unknown>)=>({eventId:'event',type:'ball',name:'测试球',start:null,end:null,bearer:'members',reason:'测试耗球',...input});
// 旧版（按筒）原公式的独立参照实现：每筒价×颗数÷每筒颗数，不足1分按半向上。
const original=(cents:number,tubeCount:number,used:number)=>Math.floor((cents*used*2+tubeCount)/(tubeCount*2));

test('新耗球按单颗价格×消耗颗数保存，没有筒数输入',async()=>{const {s,e}=fixture();await apply(s,s.accounts[0],'cost',ball({pricing:'unit',cents:208,used:16}),start);const c=s.costs[0];assert.equal(c.pricing,'unit');assert.equal(c.tubeCount,1);assert.equal(c.used,16);assert.equal(ballCents(c),3328);const r=calculateSettlement(s,e,e.end);assert.equal(r.expenseTotal,3328);assert.equal(r.bills.reduce((a,b)=>a+b.ball,0)+r.subsidy+r.unallocated,r.total)});
test('其他费用可省略每筒颗数，金额按总额',async()=>{const {s}=fixture();await apply(s,s.accounts[0],'cost',{eventId:'event',type:'other',name:'饮水',pricing:'total',cents:500,used:0,start:null,end:null,bearer:'members',reason:'测试'},start);assert.equal(s.costs[0].tubeCount,1);assert.equal(s.costs[0].cents,500)});
test('新提交的按筒或总价球费被拒绝，旧缓存页面需刷新',async()=>{const {s}=fixture();await assert.rejects(()=>apply(s,s.accounts[0],'cost',ball({pricing:'tube',cents:2400,tubeCount:12,used:16}),start),/单颗价格/);await assert.rejects(()=>apply(s,s.accounts[0],'cost',ball({pricing:'total',cents:2400,used:0}),start),/单颗价格/);assert.equal(s.costs.length,0)});
test('回归：旧按筒记录总额与原公式逐分一致',()=>{for(const cents of [0,1,25,1799,1800,2400,2499,2500,2999])for(const tubeCount of [1,2,3,6,12,16])for(const used of [0,1,4,5,6,11,12,16,25,100])assert.equal(ballCents({pricing:'tube',cents,tubeCount,used}),original(cents,tubeCount,used),`${cents}/${tubeCount}×${used}`);
 assert.equal(ballCents({pricing:'tube',cents:2400,tubeCount:12,used:16}),3200);assert.equal(ballCents({pricing:'tube',cents:2500,tubeCount:12,used:5}),1042);assert.equal(ballCents({pricing:'tube',cents:2500,tubeCount:12,used:1}),208);assert.equal(ballCents({pricing:'tube',cents:25,tubeCount:2,used:1}),13)});
test('回归：含旧按筒记录的活动分摊结果不变',()=>{const {s,e}=fixture();const legacy:Cost[]=[{id:'old1',eventId:e.id,type:'ball',name:'旧球甲',pricing:'tube',cents:2500,tubeCount:12,used:16,start:null,end:null,bearer:'members'},{id:'old2',eventId:e.id,type:'ball',name:'旧球乙',pricing:'tube',cents:2400,tubeCount:12,used:4,start:start+hour,end:start+2*hour,bearer:'members'}];s.costs.push(...legacy);const r=calculateSettlement(s,e,e.end);assert.equal(r.expenseTotal,3333+800);assert.deepEqual(r.bills.map(b=>[b.playerId,b.ball]),[['A',1127],['B',1127],['C',1127],['D',754]]);assert.equal(r.bills.reduce((a,b)=>a+b.total,0)+r.subsidy+r.unallocated,r.total)});
test('旧按筒记录仅在可整除时折合单颗价，否则不折算',()=>{assert.equal(legacyTubeUnitCents({pricing:'tube',cents:2400,tubeCount:12}),200);assert.equal(legacyTubeUnitCents({pricing:'tube',cents:2500,tubeCount:12}),null);assert.equal(legacyTubeUnitCents({pricing:'unit',cents:200,tubeCount:1}),null);
 for(const [cents,tubeCount,used] of [[2400,12,16],[1800,12,7],[3600,6,13]]){const unit=legacyTubeUnitCents({pricing:'tube',cents,tubeCount})!;assert.equal(ballCents({pricing:'unit',cents:unit,tubeCount:1,used}),ballCents({pricing:'tube',cents,tubeCount,used}))}});
