import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
const origin='http://127.0.0.1:8787',admin='local_seedy';let revision=0;const results=[];
const headers=id=>({'oai-authenticated-user-id':id,'oai-authenticated-user-email':id+'@example.invalid'});
async function get(id=admin){const r=await fetch(origin+'/api/club',{headers:headers(id)});assert.equal(r.status,200);const s=await r.json();if(id===admin)revision=s.revision;return s}
async function post(action,payload,id=admin){const r=await fetch(origin+'/api/club',{method:'POST',headers:{...headers(id),Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({action,payload,revision,requestId:crypto.randomUUID()})}),d=await r.json();if(r.ok)await get();return {status:r.status,data:d}}
async function ok(action,payload,id=admin){const r=await post(action,payload,id);assert.equal(r.status,200,JSON.stringify(r));return r.data}
function pass(name){results.push(name);console.log('PASS '+name)}
let s=await get();assert.ok(s.events.some(e=>e.note.includes('仅本地测试数据')),'仅能在现有虚构本地验收库运行');
const old=s.matches.find(m=>m.status==='complete'&&m.scoreA<m.scoreB),loser=s.accounts.find(a=>old.a.includes(a.playerId)),target=s.accounts.find(a=>old.b.includes(a.playerId));assert.ok(loser&&target);
await ok('profileDetails',{playerId:loser.playerId,years:4,hand:'left',preference:'doubles',style:'API虚构防守',equipment:'测试球拍'},loser.id);assert.equal((await get(loser.id)).players.find(p=>p.id===loser.playerId).profile.hand,'left');assert.equal((await post('profileDetails',{playerId:target.playerId,years:1,hand:'right',preference:'all',style:'',equipment:''},loser.id)).status,403);pass('独立成员档案保存和防冒充编辑');
await ok('tagVote',{playerId:target.playerId,tag:'防守怪',active:true},loser.id);await ok('tagVote',{playerId:target.playerId,tag:'防守怪',active:true},loser.id);s=await get(loser.id);assert.equal(s.tagVotes.filter(v=>v.playerId===target.playerId&&v.tag==='防守怪'&&v.voterId===loser.id).length,1);pass('打法标签重复提交只有一票');
await ok('challenge',{targetId:target.playerId},loser.id);s=await get();const challenge=s.challenges.at(-1);await ok('challengeRespond',{challengeId:challenge.id,status:'accepted'},target.id);pass('真实失利记录→复仇挑战→对方接受，跨会话共享');
const start=Date.now()-3600000,end=Date.now()+3*3600000;await ok('event',{title:'虚构验收 · 社群扩展',start,end,venue:'模拟球馆',address:'',capacity:7,signupDeadline:end,cancelDeadline:end,note:'仅本地测试数据 · 社群功能',status:'open',bookings:[{name:'擂台场',start,end,pricing:'total',cents:0},{name:'轮转场',start,end,pricing:'total',cents:0}]});s=await get();const e=s.events.at(-1);assert.equal(e.capacity,7);assert.equal(e.creatorId,admin);pass('创建者设置并保存每场接龙上限');
await ok('friend',{name:'API虚构第三朋友'});s=await get();const players=s.players.filter(p=>p.enabled).slice(0,6);for(const p of players){await ok('register',{eventId:e.id,playerId:p.id,arrival:start,departure:end,note:'虚构'});await ok('attendance',{eventId:e.id,playerId:p.id,at:start-5*60000,state:'ready'})}await ok('eventStatus',{eventId:e.id,status:'live'});s=await get();const court=s.bookings.find(b=>b.eventId===e.id);await ok('playSettings',{eventId:e.id,playMode:'arena',identityMode:'mentor',arenaCourtId:court.id,handicap:true});await ok('generate',{eventId:e.id,at:Date.now()-30*60000,duration:20,seed:23});s=await get();const r=s.rounds.find(r=>r.eventId===e.id&&r.status==='draft');let m=s.matches.find(m=>m.roundId===r.id);assert.equal(m.identity.length,4);assert.equal(m.playMode,'arena');pass('擂台赛制与随机师徒身份真实保存');
for(const desired of [loser.playerId,target.playerId]){if(![...m.a,...m.b].includes(desired)){const replace=m.a.find(id=>id!==loser.playerId&&id!==target.playerId)??m.b.find(id=>id!==loser.playerId&&id!==target.playerId);await ok('swap',{roundId:r.id,p1:replace,p2:desired});s=await get();m=s.matches.find(x=>x.id===m.id)}}if((m.a.includes(loser.playerId)&&m.a.includes(target.playerId))||(m.b.includes(loser.playerId)&&m.b.includes(target.playerId))){const other=(m.a.includes(loser.playerId)?m.b:m.a).find(id=>id!==loser.playerId);await ok('swap',{roundId:r.id,p1:target.playerId,p2:other});s=await get();m=s.matches.find(x=>x.id===m.id)}await ok('challengeMatch',{challengeId:challenge.id,matchId:m.id});await ok('publish',{roundId:r.id});await ok('start',{roundId:r.id,at:Date.now()-30*60000,monthly:true,elo:true});await ok('score',{matchId:m.id,a:21,b:19,games:[{a:21,b:19},{a:19,b:21},{a:21,b:19}],end:Date.now()-60000,reason:'虚构三局比赛'});s=await get();assert.equal(s.matches.find(x=>x.id===m.id).games.length,3);assert.equal(s.social.funny.filter(x=>x.threeGames>0).length>=4,true);assert.equal(s.social.arenas[e.id].streak,1);pass('挑战关联、三局录入、擂主连胜和趣味数据由比分更新');
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aX3sAAAAASUVORK5CYII=','base64');
async function upload(id,kind,values,content=png,type='image/png',requestId=crypto.randomUUID()){const f=new FormData();f.set('rightsConfirmed','true');f.set('file',new Blob([content],{type}),'fictional.png');f.set('kind',kind);f.set('requestId',requestId);f.set('revision',String(revision));f.set('caption','虚构存储验收');for(const[k,v]of Object.entries(values))f.set(k,String(v));const r=await fetch(origin+'/api/photos',{method:'POST',headers:{...headers(id),Origin:origin},body:f});const d=await r.json();if(r.ok)await get();return {status:r.status,data:d}}
const photoKey=crypto.randomUUID(),photo=await upload(loser.id,'photo',{eventId:e.id,matchId:m.id},png,'image/png',photoKey);assert.equal(photo.status,200,JSON.stringify(photo));const duplicate=await upload(loser.id,'photo',{eventId:e.id,matchId:m.id},png,'image/png',photoKey);assert.equal(duplicate.status,200);assert.equal(duplicate.data.duplicate,true);s=await get();const saved=s.photos.find(p=>p.id===photo.data.id);assert.equal(saved.playerIds.length,4);assert.deepEqual(new Set(saved.playerIds),new Set([...m.a,...m.b]));const image=await fetch(origin+'/api/photos/'+photo.data.id,{headers:headers(target.id)});assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await image.arrayBuffer()),png);assert.equal((await fetch(origin+'/api/photos/'+photo.data.id)).status,401);pass('R2真实照片上传/读取、自动关联四人、重发幂等与未登录拒绝');
const avatar=await upload(loser.id,'avatar',{playerId:loser.playerId});assert.equal(avatar.status,200);assert.equal((await get()).players.find(p=>p.id===loser.playerId).avatarId,avatar.data.id);assert.equal((await upload(loser.id,'avatar',{playerId:target.playerId})).status,403);assert.equal((await upload(loser.id,'avatar',{playerId:loser.playerId},Buffer.from('<svg/>'),'image/svg+xml')).status,400);pass('头像保存、越权上传拒绝及SVG格式拒绝');
await ok('eventStatus',{eventId:e.id,status:'ended'});await ok('awardVote',{eventId:e.id,playerId:target.playerId,category:'mvp'},loser.id);await ok('awardVote',{eventId:e.id,playerId:target.playerId,category:'mvp'},loser.id);s=await get();assert.equal(s.awardVotes.filter(v=>v.eventId===e.id&&v.category==='mvp'&&v.playerId===target.playerId).length,1);pass('赛后MVP跨会话共享且重复投票不重复计数');
s=await get(loser.id);assert.equal(s.players.find(p=>p.id===loser.playerId).rating,null);assert.equal(s.ratingHistory.length,0);assert.ok(s.social.stats.find(p=>p.playerId===loser.playerId).tier);assert.ok(s.social.annual.find(p=>p.playerId===loser.playerId).games>=2);assert.equal(s.social.personality.find(p=>p.playerId===loser.playerId).early>=1,true);pass('段位展示、隐藏内部Elo、早到人格和年度总结真实计算');
writeFileSync('.test-output/social-api-results.json',JSON.stringify({passed:results.length,results,photoId:photo.data.id,avatarId:avatar.data.id,eventId:e.id,at:new Date().toISOString()},null,2));console.log(JSON.stringify({passed:results.length,failed:0}));
