import {readPhotoForm} from '../../../lib/request-body';
import {publicApiError} from '../../../lib/api-error';
import {fail} from '../../../lib/domain/types';
import {env} from 'cloudflare:workers';
import {getAppUser} from '../../../lib/auth';
import {load,save,committed} from '../../../lib/store';
import {z} from 'zod';
import {canManageEvent} from '../../../lib/domain/permissions';
export const dynamic='force-dynamic';
export async function POST(req:Request){let uploadedKey:string|null=null;try{const u=await getAppUser();if(!u)return Response.json({error:'请先登录'},{status:401});if(req.headers.get('origin')!==new URL(req.url).origin)return Response.json({error:'请求来源不允许'},{status:403});if(!env.BUCKET)return Response.json({error:'照片存储暂不可用，请稍后重试'},{status:503});const s=await load(),a=s.accounts.find(a=>a.id===u.userId);if(!a)return Response.json({error:'请先加入群组'},{status:403});const f=await readPhotoForm(req),requestId=z.string().uuid().parse(f.get('requestId')),key=a.id+':'+requestId;if(await committed(key))return Response.json({ok:true,duplicate:true});if(Number(f.get('revision'))!==s.revision)return Response.json({error:'数据已更新，请刷新后重新上传'},{status:409});const file=f.get('file');if(!(file instanceof File)||!file.size||file.size>5*1024*1024)fail('请选择不超过5MB的JPEG、PNG或WebP照片');const bytes=new Uint8Array(await file.arrayBuffer());const mime=bytes[0]===255&&bytes[1]===216&&bytes[2]===255?'image/jpeg':bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71?'image/png':String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP'?'image/webp':null;if(!mime||mime!==file.type)fail('文件内容与允许的照片格式不符');const kind=z.enum(['avatar','photo','racket']).parse(f.get('kind')),caption=z.string().max(300).parse(f.get('caption')??''),assetId=crypto.randomUUID();let eventId:string|null=null,matchId:string|null=null,playerIds:string[]=[];const previous=structuredClone(s);
 if(kind==='avatar'||kind==='racket'){const playerId=z.string().trim().min(1).max(100).parse(f.get('playerId')),p=s.players.find(p=>p.id===playerId);if(!p)return Response.json({error:'球友档案不存在'},{status:404});if(a.role!=='admin'&&p.id!==a.playerId)return Response.json({error:'只能上传自己的档案照片'},{status:403});playerIds=[p.id];if(kind==='avatar')p.avatarId=assetId}
 else{eventId=z.string().min(1).parse(f.get('eventId'));const e=s.events.find(e=>e.id===eventId);if(!e||e.deletedAt!==undefined||!canManageEvent(a,e)&&e.status==='draft')fail('活动不可访问');if(!canManageEvent(a,e)&&!s.attendance.some(at=>at.eventId===eventId&&at.playerId===a.playerId))return Response.json({error:'活动创建者、管理员或实际参加者才可以上传活动照片'},{status:403});const requested=String(f.get('matchId')??'');if(requested){const m=s.matches.find(m=>m.id===requested&&m.eventId===eventId);if(!m)fail('比赛不属于本次活动');matchId=m.id;playerIds=[...m.a,...m.b]}else{playerIds=[...new Set(z.array(z.string()).max(30).parse(JSON.parse(String(f.get('playerIds')??'[]'))))];if(playerIds.some(id=>!s.attendance.some(at=>at.eventId===eventId&&at.playerId===id)))fail('关联球友必须实际参加本次活动')}}
 uploadedKey='media/'+assetId;await env.BUCKET.put(uploadedKey,bytes,{httpMetadata:{contentType:mime}});s.photos.push({id:assetId,key:uploadedKey,kind,eventId,matchId,playerIds,ownerId:a.id,caption,created:Date.now(),type:mime,size:file.size});s.audits.push({id:crypto.randomUUID(),at:Date.now(),actor:a.id,action:'photoUpload',reason:kind==='avatar'?'更新头像':kind==='racket'?'上传战拍照片':'上传活动照片',changes:{assetId,eventId,matchId,playerIds}});await save(s,key,previous);uploadedKey=null;return Response.json({ok:true,id:assetId});
 }catch(e){if(uploadedKey&&env.BUCKET){try{await env.BUCKET.delete(uploadedKey)}catch{}}const {error,status}=publicApiError(e);return Response.json({error},{status})}}
