'use client';
import {useEffect,useState,useCallback,useRef} from 'react';
import {Home,CalendarDays,Swords,Trophy,User,Plus,Clock,Users,Settings,RefreshCw,Download} from 'lucide-react';
import {Toaster,toast} from 'sonner';
import {month} from '../lib/domain/types';
import {Forms,fmt,hm,euro,dt,epoch,text,timed,number,choice,why,labels,type Field,type Form} from './ui';
import EventView from './event-view';
import MatchCard from './match-card';
import SocialHub from './social-hub';
import {Avatar} from './social-hub';
const empty=(t:string)=><div className="empty"><CalendarDays size={30}/><p>{t}</p></div>;
export default function ClubApp(){
 const [year,setYear]=useState(Number(month(Date.now()).slice(0,4))),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[page,setPage]=useState('home'),[eventId,setEventId]=useState(''),[tab,setTab]=useState('overview'),[period,setPeriod]=useState(month(Date.now())),[form,setForm]=useState<Form|null>(null),[danger,setDanger]=useState<any>(null),[preview,setPreview]=useState<any>(null);
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/club?month='+period+'&year='+year,{cache:'no-store'});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('');return d}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[period,year]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer)},[refresh]);
 async function action(action:string,payload:any,close=true){setBusy(true);try{const r=await fetch('/api/club',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,payload,requestId:crypto.randomUUID(),revision:data?.revision})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);if(d.preview){setPreview(d.preview);setForm(null);toast.success('已生成重算预览，尚未保存');return d}await refresh();if(close)setForm(null);toast.success('已保存');return d}catch(e){toast.error((e as Error).message);throw e}finally{setBusy(false)}}
 const live=useRef<any>({});live.current={data,refresh,action};
 const send=(a:string,p:any)=>{void action(a,p).catch(()=>{})};
 const admin=data?.me?.role==='admin',name=(id:string)=>data?.players?.find((p:any)=>p.id===id)?.name??'未知成员';
 const open=(title:string,a:string,v:any,fields:Field[],convert?:Form['convert'],description?:string)=>setForm({title,action:a,values:v,fields,convert,description});
 const openEvent=(id:string,t='overview')=>{setEventId(id);setTab(t);setPage('events')};
 useEffect(()=>{if(data?.events&&!eventId){const id=new URLSearchParams(location.search).get('event');if(id&&data.events.some((e:any)=>e.id===id))openEvent(id)}},[data]);
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();const tools=[{name:'read_club_overview',description:'读取当前授权活动与本人报名状态',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>{const fresh=await live.current.refresh();return {events:fresh?.events??[],myPlayerId:fresh?.me?.playerId}}},{name:'register_for_event',description:'为当前登录成员报名活动，满员后进入候补',inputSchema:{type:'object',properties:{eventId:{type:'string'}},required:['eventId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(typeof input?.eventId!=='string')throw new Error('活动ID无效');const current=live.current.data;const e=current?.events.find((e:any)=>e.id===input.eventId);if(!e)throw new Error('活动不存在');return live.current.action('register',{eventId:e.id,playerId:current.me.playerId,arrival:e.start,departure:e.end,note:''},false)}}];for(const tool of tools)try{void Promise.resolve(ctx.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const regs=(ev:any)=>data.registrations.filter((r:any)=>r.eventId===ev.id&&r.status!=='cancelled').sort((a:any,b:any)=>a.sequence-b.sequence);
 const eventCard=(ev:any)=><button className="event-card" key={ev.id} onClick={()=>openEvent(ev.id)}><div className="date-box"><b>{fmt(ev.start,{day:'2-digit'})}</b><span>{fmt(ev.start,{month:'long',weekday:'short'})}</span></div><div className="event-info"><div className="row"><h3>{ev.title}</h3><span className="badge">{labels[ev.status]}</span></div><p><Clock size={15}/>{hm(ev.start)}–{hm(ev.end)} · {ev.venue}</p><div className="row"><span><Users size={15}/> {regs(ev).filter((r:any)=>r.status==='confirmed').length}/{ev.capacity} 人</span><span className="muted">我：{labels[regs(ev).find((r:any)=>r.playerId===data.me.playerId)?.status]??'尚未报名'}</span></div></div></button>;
 function newEvent(){const start=Date.now()+86400000,end=start+3*3600000;open('创建活动','event',{title:'周末双打局',venue:'',address:'',start:dt(start),end:dt(end),capacity:16,signupDeadline:dt(start-3600000),cancelDeadline:dt(start-86400000),note:'',status:'open',courtName:'1号场',courtPrice:12},[text('title','活动标题'),text('venue','球馆'),text('address','地址（可选）'),timed('start','开始 · 马德里时间'),timed('end','结束 · 马德里时间'),number('capacity','接龙人数上限（创建者设置）'),timed('signupDeadline','报名截止'),timed('cancelDeadline','自由取消截止'),text('courtName','首个场地名称'),number('courtPrice','每小时价格 · EUR'),choice('status','状态',[['open','开放报名'],['draft','草稿']]),text('note','活动备注')],v=>{const {courtName,courtPrice,...rest}=v;const start=epoch(v.start),end=epoch(v.end);return {...rest,start,end,signupDeadline:epoch(v.signupDeadline),cancelDeadline:epoch(v.cancelDeadline),bookings:[{name:courtName,start,end,pricing:'hourly',cents:Math.round(courtPrice*100)}]}},'创建后可添加不同场地及不连续预约时段。')}
 const context={data,refresh,admin,name,open,send,action,setDanger,busy,openEvent,regs};
 if(loading)return <main className="shell"><div className="brand">羽球局</div>{empty('正在读取群组数据…')}</main>;
 if(!data||error)return <main className="shell"><h1>暂时无法连接群组</h1><p className="error">{error}</p><button className="primary" onClick={()=>refresh()}>重新加载</button><a className="ghost" href="/signin-with-chatgpt?return_to=/" target="_top">重新登录</a></main>;
 return <main className="shell"><Toaster richColors position="top-center"/><header className="topbar"><button className="brand" onClick={()=>{setPage('home');setEventId('')}}>{data.settings?.name??'羽球局'}<span>PRIVATE BADMINTON CLUB</span></button><div className="actions"><span className="badge">{admin?'管理员':'私人群组'}</span><button className="icon-button" aria-label="刷新数据" onClick={()=>refresh()}><RefreshCw size={18}/></button></div></header>
 {(data.setup||data.join)?<section className="card onboarding"><p className="eyebrow">YOUR CLUB, YOUR COURT</p><h1>{data.setup?'建立你的羽球局':'加入羽毛球群'}</h1><p>{data.setup?'私有预览只对网站所有者开放。初始化后，这个已验证账号成为首位管理员。':'输入群邀请码加入，邀请码不会授予管理员权限。'}</p><p className="muted">已登录：{data.user.email}</p><button className="primary" onClick={()=>open(data.setup?'初始化管理员':'加入群组',data.setup?'initialize':'join',{name:data.user.name==='Seedy'?'本地测试管理员':'',invite:''},[text('name','我的昵称'),text('invite',data.setup?'设置至少8位群邀请码':'群邀请码')])}>{data.setup?'初始化群组':'输入邀请码加入'}</button><a href="/signout-with-chatgpt?return_to=/" className="ghost">退出登录</a></section>:<>
 {page==='home'&&<><div className="heading"><div><p className="eyebrow">LET'S PLAY</p><h1>{name(data.me.playerId)}，球场见。</h1><p className="muted">一起打球，把每一场安排得刚刚好。</p></div><div className="actions"><button className="secondary" onClick={()=>setPage('social')}>球友圈 · 档案与趣味数据</button>{admin&&<button className="primary" onClick={newEvent}><Plus size={18}/> 创建活动</button>}</div></div><div className="dashboard-grid"><section><div className="section-title"><h2>下一场活动</h2><button className="ghost" onClick={()=>{setPage('events');setEventId('')}}>全部活动</button></div>{data.events.filter((e:any)=>['open','locked','live'].includes(e.status)).sort((a:any,b:any)=>a.start-b.start).slice(0,2).map(eventCard)}{!data.events.length&&<section className="card">{empty('还没有活动，第一场从这里开始。')}{admin&&<div className="actions"><button className="primary" onClick={newEvent}>创建第一场活动</button><button className="ghost" onClick={()=>send('demo',{})}>载入虚构验收活动</button></div>}</section>}<div className="section-title"><h2>最近比赛</h2></div>{data.matches.filter((m:any)=>m.status==='complete').sort((a:any,b:any)=>b.end-a.end).slice(0,2).map((m:any)=><MatchCard key={m.id} m={m} ctx={context}/>)}{!data.matches.some((m:any)=>m.status==='complete')&&empty('第一场结束后，这里会留下比赛记录。')}</section><aside><section className="card"><div className="section-title"><h3>本月球友榜</h3><Trophy size={20}/></div>{data.leaderboard.filter((r:any)=>r.games>0).slice(0,3).map((r:any,i:number)=><div className="rank-line" key={r.playerId}><b className={'rank rank-'+i}>{r.rank}</b><div>{r.name}<small>{r.games} 场 · {r.qualified?'正式排名':'暂定榜'}</small></div><strong>{r.points}<small>积分</small></strong></div>)}{!data.leaderboard.some((r:any)=>r.games)&&<p className="muted">本月还没有有效计分赛。</p>}<button className="ghost" onClick={()=>setPage('ranking')}>查看完整排名</button></section><p className="hint">时间统一使用 Europe/Madrid。<br/>活动费用页查看每人分摊金额。</p></aside></div></>}
 {page==='events'&&(!eventId||!data.events.find((e:any)=>e.id===eventId))&&<><div className="heading"><h1>活动</h1>{admin&&<button className="primary" onClick={newEvent}><Plus size={18}/> 创建活动</button>}</div>{data.events.slice().sort((a:any,b:any)=>b.start-a.start).map(eventCard)}{!data.events.length&&empty('暂无活动')}</>}
 {page==='events'&&eventId&&data.events.find((e:any)=>e.id===eventId)&&<EventView e={data.events.find((e:any)=>e.id===eventId)} ctx={context} tab={tab} setTab={setTab} back={()=>setEventId('')}/>}
 {page==='matches'&&<><h1>比赛</h1>{data.matches.filter((m:any)=>!['draft','cancelled'].includes(m.status)).slice().reverse().map((m:any)=><section key={m.id}><button className="ghost" onClick={()=>openEvent(m.eventId,'matches')}>{data.events.find((e:any)=>e.id===m.eventId)?.title} · {m.start?fmt(m.start):'尚未开赛'}</button><MatchCard m={m} ctx={context}/></section>)}{!data.matches.length&&empty('暂无比赛记录')}</>}
 {page==='ranking'&&<><div className="heading"><div><p className="eyebrow">MONTHLY LEADERBOARD</p><h1>每一场，都算数。</h1></div><input aria-label="排名月份" type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></div><p className="hint">胜 {data.seasons.find((s:any)=>s.id===period)?.rules.win??data.settings.rules.win} 分 · 最少 {data.seasons.find((s:any)=>s.id===period)?.rules.minimum??data.settings.rules.minimum} 场入榜 · 前 {data.seasons.find((s:any)=>s.id===period)?.rules.cap||'不限'} 场计分。按实际开赛时间归属马德里自然月。</p>{[true,false].map(qualified=><section className="card" key={String(qualified)}><h2>{qualified?'正式榜':'暂定榜'} <small className="muted">{qualified?'达到最低场数':'尚未达到最低场数'}</small></h2>{data.leaderboard.filter((r:any)=>r.qualified===qualified).map((r:any)=><div className="ranking-row" key={r.playerId}><b className={'rank rank-'+(r.rank-1)}>{r.rank}</b><div><strong>{r.name}</strong><small>{r.games} 计分 / {r.total} 实际 · {r.wins} 胜 {r.losses} 负</small></div><div><strong>{r.points} 分</strong><small>{Math.round(r.rate*100)}% 胜率 · 净胜 {r.margin.toFixed(1)}</small></div></div>)}{!data.leaderboard.some((r:any)=>r.qualified===qualified)&&empty('本月暂无符合条件的成员')}</section>)}<p className="hint">同分依次比较胜率、场均净胜分；仍相同则并列。Rating 独立用于辅助排场。</p></>}
 {page==='me'&&<><section className="profile"><Avatar p={data.players.find((p:any)=>p.id===data.me.playerId)} size="large"/><div><h1>{name(data.me.playerId)}</h1><p>{data.me.email}</p></div><button className="ghost" onClick={()=>open('修改昵称','profile',{name:name(data.me.playerId)},[text('name','昵称')])}>编辑</button></section><div className="stats"><section className="card"><span>明面段位</span><strong>{data.social.stats.find((p:any)=>p.playerId===data.me.playerId)?.tier}</strong><small>{data.social.stats.find((p:any)=>p.playerId===data.me.playerId)?.provisional?'暂定 · 前10场':'内部 Elo 辅助排场'}</small></section><section className="card"><span>本月积分</span><strong>{data.leaderboard.find((r:any)=>r.playerId===data.me.playerId)?.points??0}</strong><small>{data.leaderboard.find((r:any)=>r.playerId===data.me.playerId)?.total??0} 场比赛</small></section><section className="card"><span>参加活动</span><strong>{new Set(data.attendance.filter((a:any)=>a.playerId===data.me.playerId).map((a:any)=>a.eventId)).size}</strong><small>按实际出勤统计</small></section></div><section className="card"><div className="row"><h3>我的球友卡片与年度总结</h3><button className="secondary" onClick={()=>setPage('social')}>查看档案、搭档与克制关系</button></div></section><h2>我的活动与分摊</h2>{data.settlements.filter((st:any)=>st.confirmed&&st.bills.some((b:any)=>b.playerId===data.me.playerId)&&!data.settlements.some((x:any)=>x.eventId===st.eventId&&x.confirmed&&x.version>st.version)).map((st:any)=>{const b=st.bills.find((b:any)=>b.playerId===data.me.playerId);return <section className="card" key={st.id}><div className="row"><h3>{data.events.find((e:any)=>e.id===st.eventId)?.title}</h3><strong>{euro(b.total)}</strong></div><p>场地 {euro(b.court)} · 球费 {euro(b.ball)} · 其他 {euro(b.other)}</p><button className="ghost" onClick={()=>openEvent(st.eventId,'fees')}>查看每人分摊与计算明细</button></section>})}<h2>最近比赛</h2>{data.matches.filter((m:any)=>m.status==='complete'&&[...m.a,...m.b].includes(data.me.playerId)).slice().reverse().slice(0,8).map((m:any)=><MatchCard key={m.id} m={m} ctx={context}/>)}{admin&&<section className="card"><h3>群组管理</h3><div className="actions"><button className="secondary" onClick={()=>setPage('admin')}><Settings size={17}/> 管理员设置</button><a href="/api/club?export=1" className="ghost"><Download size={17}/> 导出全部数据 JSON</a></div></section>}<a className="ghost" href="/signout-with-chatgpt?return_to=/">退出登录</a></>}
 {page==='social'&&<SocialHub ctx={context} year={year} setYear={setYear}/>}
 {page==='admin'&&admin&&<><h1>群组管理</h1><section className="card"><h3>群名、邀请与赛季规则</h3><p className="hint">已绑定月份须先预览，再显式重算。默认规则用于新的自然月。</p><button className="primary" onClick={()=>open('群组与默认规则','settings',{name:data.settings.name,invite:'',...data.settings.rules},[text('name','群名'),text('invite','新的邀请码（至少8位）'),...ruleFields()],v=>{const {name,invite,...rules}=v;return {name,invite,rules}})}>编辑群组设置</button></section><section className="card"><h3>参赛者与初始 Rating</h3>{data.players.map((p:any)=><div className="signup-line" key={p.id}><div className="grow"><strong>{p.name}</strong><p>Rating {Math.round(p.rating)} · {p.ratedGames} 场 · {p.enabled?'启用':'停用'}</p></div><button className="ghost" onClick={()=>open('调整初始实力估计','rating',{playerId:p.id,value:p.initialRating,enabled:p.enabled,reason:''},[number('value','初始 Rating'),{key:'enabled',label:'启用参赛者',type:'checkbox'},why])}>调整</button></div>)}</section><section className="card"><h3>账号权限</h3>{data.accounts.map((a:any)=><div className="row small-line" key={a.id}><span>{name(a.playerId)} · {a.role==='admin'?'管理员':'成员'}</span><button className="ghost" onClick={()=>open('调整账号角色','role',{accountId:a.id,role:a.role,reason:''},[choice('role','角色',[['member','普通成员'],['admin','管理员']]),why])}>调整</button></div>)}</section><section className="card"><h3>历史赛季规则重算</h3><button className="secondary" onClick={()=>historyForm()}>生成重算预览</button>{preview&&<><p className="warning">以下为预览，尚未保存。</p>{preview.leaderboard.map((r:any)=><div className="row" key={r.playerId}><span>{r.name}</span><span>{r.points} 分 · Rating {Math.round(r.rating)}</span></div>)}<button className="primary" onClick={()=>historyForm(true)}>确认保存新规则并重算</button></>}</section><section className="card"><h3>操作日志</h3>{data.audits.slice().reverse().slice(0,50).map((a:any)=><details className="audit" key={a.id}><summary>{fmt(a.at)} · {a.action} · {a.reason}</summary><pre>{JSON.stringify(a.changes??{},null,2)}</pre></details>)}</section></>}
 <nav className="bottom-nav">{[['home','首页',Home],['events','活动',CalendarDays],['matches','比赛',Swords],['ranking','排名',Trophy],['me','我的',User]].map(([v,l,I]:any)=><button key={v} className={page===v?'active':''} onClick={()=>{setPage(v);if(v==='events')setEventId('')}}><I size={22}/><span>{l}</span></button>)}</nav></>}
 <Forms {...{form,setForm,busy,action,danger,setDanger}}/></main>;
 function ruleFields(){return [number('win','胜利积分'),number('loss','失败积分'),number('minimum','正式榜最低场数（0关闭）'),number('cap','月计分上限（0关闭）'),number('target','目标分'),number('lead','领先分'),number('ceiling','封顶分'),number('k','Elo K值')]}
 function historyForm(confirm=false){const season=data.seasons.find((x:any)=>x.id===period)??data.seasons[0];if(!season){toast.error('尚未建立有效比赛赛季');return}open(confirm?'确认历史规则重算':'历史规则重算预览',confirm?'historyRules':'historyPreview',{season:confirm?preview.input.season:season.id,...(confirm?preview.input.rules:season.rules),reason:''},confirm?[why]:[choice('season','赛季',data.seasons.map((x:any)=>[x.id,x.id])),...ruleFields()],v=>{const {season,reason,...rules}=v;return confirm?{season,reason,rules}:{season,rules}})}
}



