'use client';
import {canManageEvent} from '../lib/domain/permissions';
import {awardNames} from '../lib/domain/social';
import {awardCandidateIds,canCastAwardVote} from '../lib/domain/activity-voting';
import {choice} from './ui';
export default function EventSocial({e,ctx}:any){const {data,name,open,send}=ctx;const manager=canManageEvent(data.me,e);const arena=data.social.arenas[e.id],board=data.social.courtBoards[e.id]??[],plan=data.rotationPlans[e.id];const now=Date.now(),candidates=awardCandidateIds(data,e.id,now),canVote=canCastAwardVote(data,e,data.me,now),cancelled=e.status==='cancelled';
 return <><section className="card"><div className="row"><h3>本场玩法</h3><span className="badge">{{balanced:'公平轮转',arena:'擂台模式',koc:'王者轮转'}[e.playMode as 'balanced']??'公平轮转'}</span></div><p className="hint">{plan?.description??'请先确认本活动正式报名名单。'}</p>{e.playMode!=='arena'&&plan?.availableCourts>plan?.usedCourts&&<p className="hint">可用{plan.availableCourts}片场，按四人一场使用{plan.usedCourts}片，避免生成不足4人的比赛。</p>}{e.identityMode&&e.identityMode!=='off'&&<p>随机身份：{{cp:'本轮随机 搭档',mentor:'随机师徒',carry:'大腿带萌新'}[e.identityMode as 'cp']}</p>}{manager&&<button className="secondary" onClick={()=>open('设置本场玩法','playSettings',{eventId:e.id,playMode:e.playMode??'balanced',identityMode:e.identityMode??'off',arenaCourtId:e.arenaCourtId??'none',handicap:e.handicap??false},[choice('playMode','赛制',[['balanced','自动公平双打轮转'],['arena','擂台：胜者留场、败者下场'],['koc','王者轮转：个人积分轮转']]),choice('identityMode','社交身份',[['off','普通分组'],['cp','本轮随机 搭档'],['mentor','随机师徒'],['carry','大腿带萌新']]),choice('arenaCourtId','擂台场地',[['none','未选择'],...data.bookings.filter((b:any)=>b.eventId===e.id).map((b:any)=>[b.id,b.name])]),{key:'handicap',label:'实力差较大时建议让分',type:'checkbox'}],(v:any)=>({...v,arenaCourtId:v.arenaCourtId==='none'?'':v.arenaCourtId}),'擂台固定赢家搭档；个人积分轮转优先换搭档。让分确认后作为友谊赛，不计月积分或实力分。')}>设置玩法与随机身份</button>}{e.playMode==='arena'&&<div className="arena-banner"><span>当前擂主</span><strong>{arena.holders.length?arena.holders.map(name).join(' / '):'等待第一场结果'}</strong><span>{arena.streak} 连胜</span></div>}{e.playMode==='koc'&&<><h3>个人轮转积分榜</h3>{board.map((r:any,i:number)=><div className="ranking-row" key={r.playerId}><b className="rank">{i+1}</b><div><strong>{name(r.playerId)}</strong><small>{r.games}场 · {r.wins}胜 · 净胜{r.margin}</small></div><strong>{r.points}分</strong></div>)}<p className="hint">各局本方实际得分累计到个人；同分依次看胜场、净胜分。每轮继续按可参与机会公平选人并优先换搭档。</p></>}</section>
 <section className="card"><h3>球友评选</h3><p className="hint">正式报名默认参与，无需签到。最佳球员、最佳防守、最佳网前和最拼命球员投票从报名起开放，也可在活动后继续评选。</p>
 {cancelled&&<p className="muted" role="status">活动已取消，投票已关闭，已有票数仍可查看。</p>}
 {!candidates.length&&<p className="muted">暂无候选球友。请先在“接龙”中正式报名；已有实际参与记录的球友也会进入评选，候补暂不参与。</p>}
 {!cancelled&&candidates.length>0&&!canVote&&<p className="muted">正式报名或实际参加本活动后即可投票；活动创建者和管理员也可以投票。</p>}
 {!cancelled&&canVote&&candidates.length===1&&candidates[0]===data.me.playerId&&<p className="muted">目前只有你一位候选球友，不能投给自己。其他球友正式报名后即可为对方投票。</p>}
 {Object.entries(awardNames).map(([category,label])=>{const votes=data.awardVotes.filter((v:any)=>v.eventId===e.id&&v.category===category),mine=votes.find((v:any)=>v.voterId===data.me.id);const counts=candidates.map(id=>({id,count:votes.filter((v:any)=>v.playerId===id).length})).sort((a,b)=>b.count-a.count||a.id.localeCompare(b.id));const max=counts[0]?.count??0;return <div className="award-group" key={category}><h4>{label}</h4><p className="hint">{max?counts.filter(r=>r.count===max).map(r=>name(r.id)).join(' / ')+' · '+max+'票领先':candidates.length?'尚未投票':'暂无候选人'}</p><div className="actions">{candidates.map(id=><button key={id} type="button" aria-pressed={mine?.playerId===id} disabled={!canVote||id===data.me.playerId||ctx.busy} className={'tag-button '+(mine?.playerId===id?'active':'')} onClick={()=>send('awardVote',{eventId:e.id,playerId:id,category})}>{name(id)} · {votes.filter((v:any)=>v.playerId===id).length}票{id===data.me.playerId?' · 自己':mine?.playerId===id?' · 已投':''}</button>)}</div></div>})}
 <p className="hint">每个账号在每次活动的每个奖项有一票，点击其他候选人可改投；不能投给自己。</p></section>
 </>}
