'use client';
import Disclosure from './disclosure';
import {useEffect,useState} from 'react';
import EventStyleVotes from './event-style-votes';
import {canManageEvent} from '../lib/domain/permissions';
import EventAwards from './event-awards';
import {canCastAwardVote,isAwardVotingOpen} from '../lib/domain/activity-voting';
import {choice} from './form-fields';
export default function EventSocial({e,ctx}:any){const {data,name,open,send}=ctx;const manager=canManageEvent(data.me,e);const arena=data.social.arenas[e.id],board=data.social.courtBoards[e.id]??[],plan=data.rotationPlans[e.id];const [now,setNow]=useState(Date.now);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer)},[e.id]);const canVote=canCastAwardVote(data,e,data.me,now),votingOpen=isAwardVotingOpen(data,e,now);
 return <>{votingOpen&&<EventAwards key={e.id+':'+data.me.id} e={e} ctx={ctx} now={now}/>}<section className="card"><div className="row"><h3>本场玩法</h3><span className="badge">{{balanced:'公平轮转',arena:'擂台模式',koc:'王者轮转'}[e.playMode as 'balanced']??'公平轮转'}</span></div><p className="hint">{plan?.description??'请先确认本活动正式报名名单。'}</p>{e.playMode!=='arena'&&plan?.availableCourts>plan?.usedCourts&&<p className="hint">可用{plan.availableCourts}片场，按四人一场使用{plan.usedCourts}片，避免生成不足4人的比赛。</p>}{e.identityMode&&e.identityMode!=='off'&&<p>随机身份：{{cp:'本轮随机 搭档',mentor:'随机师徒',carry:'大腿带萌新'}[e.identityMode as 'cp']}</p>}{manager&&<button className="secondary" onClick={()=>open('设置本场玩法','playSettings',{eventId:e.id,playMode:e.playMode??'balanced',identityMode:e.identityMode??'off',arenaCourtId:e.arenaCourtId??'none',handicap:e.handicap??false},[choice('playMode','赛制',[['balanced','自动公平双打轮转'],['arena','擂台：胜者留场、败者下场'],['koc','王者轮转：个人积分轮转']]),choice('identityMode','社交身份',[['off','普通分组'],['cp','本轮随机 搭档'],['mentor','随机师徒'],['carry','大腿带萌新']]),choice('arenaCourtId','擂台场地',[['none','未选择'],...data.bookings.filter((b:any)=>b.eventId===e.id).map((b:any)=>[b.id,b.name])]),{key:'handicap',label:'实力差较大时建议让分',type:'checkbox'}],(v:any)=>({...v,arenaCourtId:v.arenaCourtId==='none'?'':v.arenaCourtId}),'擂台固定赢家搭档；个人积分轮转优先换搭档。让分局也计排行榜积分，隐藏实力分仍保留让分保护。')}>设置玩法与随机身份</button>}{e.playMode==='arena'&&<div className="arena-banner"><span>当前擂主</span><strong>{arena.holders.length?arena.holders.map(name).join(' / '):'等待第一场结果'}</strong><span>{arena.streak} 连胜</span></div>}{e.playMode==='koc'&&<><h3>个人轮转积分榜</h3>{board.map((r:any,i:number)=><div className="ranking-row" key={r.playerId}><b className="rank">{i+1}</b><div><strong>{name(r.playerId)}</strong><small>{r.games}场 · {r.wins}胜 · 净胜{r.margin}</small></div><strong>{r.points}分</strong></div>)}<p className="hint">各局本方实际得分累计到个人；同分依次看胜场、净胜分。每轮继续按可参与机会公平选人并优先换搭档。</p></>}</section>
 {!votingOpen&&<EventAwards key={e.id+':'+data.me.id} e={e} ctx={ctx} now={now}/>}

 <Disclosure label="打法标签与投票" defaultOpen={canVote}><EventStyleVotes e={e} ctx={ctx} now={now}/></Disclosure>
 </>}
