'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {ChevronLeft,Clock,MapPin,Copy,Plus,Shuffle,Play,Check} from 'lucide-react';
import {Pick,fmt,hm,dt,epoch,euro,text,timed,number,money,choice,why,labels} from './ui';
import {bookingCents} from '../lib/domain/money';
import MatchCard from './match-card';
import Fees from './fees';
export default function EventView({e,ctx,tab,setTab,back}:any){const {data,admin,name,open,send,setDanger,regs}=ctx;const [selected,setSelected]=useState('');
const own=(id:string)=>admin||data.players.find((p:any)=>p.id===id)?.ownerId===data.me.id;const owned=data.players.filter((p:any)=>own(p.id)&&p.enabled);
const registration=(playerId=data.me.playerId)=>{const r=data.registrations.find((r:any)=>r.eventId===e.id&&r.playerId===playerId);open(r&&r.status!=='cancelled'?'修改参加时间':'参加活动','register',{eventId:e.id,playerId,arrival:dt(r?.arrival??e.start),departure:dt(r?.departure??e.end),note:r?.note??''},[choice('playerId','参赛者',owned.map((p:any)=>[p.id,p.name])),timed('arrival','预计到达'),timed('departure','预计离开'),text('note','报名备注')],(v:any)=>({...v,arrival:epoch(v.arrival),departure:epoch(v.departure)}),'满员自动候补。朋友各自有独立档案与名额。')};
const copySignup=async()=>{try{await navigator.clipboard.writeText(`${data.settings.name} · ${e.title}\n${fmt(e.start)}–${hm(e.end)}\n${e.venue}\n正式名单\n${regs(e).filter((r:any)=>r.status==='confirmed').map((r:any,i:number)=>`${i+1}. ${name(r.playerId)} ${hm(r.arrival)}–${hm(r.departure)}`).join('\n')}\n候补名单\n${regs(e).filter((r:any)=>r.status==='waitlist').map((r:any,i:number)=>`${i+1}. ${name(r.playerId)}`).join('\n')||'暂无'}\n${location.origin}/?event=${e.id}`);toast.success('已复制，可手动发到群里')}catch{toast.error('复制失败，请检查剪贴板权限')}};
const swap=(r:any,id:string)=>{if(!selected)setSelected(id);else{send('swap',{roundId:r.id,p1:selected,p2:id});setSelected('')}};
return <><button className="ghost" onClick={back}><ChevronLeft size={18}/> 全部活动</button><div className="event-heading"><p className="eyebrow">{fmt(e.start,{year:'numeric',month:'long',day:'numeric',weekday:'long'})}</p><h1>{e.title}</h1><div className="meta"><span><Clock size={17}/>{hm(e.start)}–{hm(e.end)}</span><span><MapPin size={17}/>{e.venue}</span><span className="badge">{labels[e.status]}</span></div></div><Tabs value={tab} onValueChange={setTab}><TabsList className="event-tabs" variant="line">{[['overview','概览'],['signup','接龙'],['rounds','排场'],['matches','比赛'],['fees','费用']].map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList></Tabs>
{tab==='overview'&&<div className="dashboard-grid"><section><section className="card"><div className="row"><h2>一起上场</h2><span className="big-count">{regs(e).filter((r:any)=>r.status==='confirmed').length}<small> / {e.capacity} 人</small></span></div><div className="capacity"><div style={{width:Math.min(100,regs(e).filter((r:any)=>r.status==='confirmed').length/e.capacity*100)+'%'}}/></div><p>候补 {regs(e).filter((r:any)=>r.status==='waitlist').length} 人 · 我：{labels[regs(e).find((r:any)=>r.playerId===data.me.playerId)?.status]??'尚未报名'}</p><button className="primary" onClick={()=>registration()}>参加 / 修改时间</button><p className="hint">报名截止 {fmt(e.signupDeadline)}<br/>自由取消截止 {fmt(e.cancelDeadline)}</p></section><section className="card"><div className="row"><h3>活动说明</h3>{admin&&<button className="ghost" onClick={()=>open('编辑活动','eventEdit',{eventId:e.id,title:e.title,venue:e.venue,address:e.address,capacity:e.capacity,signupDeadline:dt(e.signupDeadline),cancelDeadline:dt(e.cancelDeadline),note:e.note,reason:''},[text('title','标题'),text('venue','球馆'),text('address','地址'),number('capacity','报名上限'),timed('signupDeadline','报名截止'),timed('cancelDeadline','取消截止'),text('note','备注'),why],(v:any)=>({...v,signupDeadline:epoch(v.signupDeadline),cancelDeadline:epoch(v.cancelDeadline)}))}>编辑</button>}</div><p className="prewrap">{e.note||'一起打球，请按时到场。'}</p><p className="muted">{e.address}</p>{admin&&<Pick value={e.status} options={Object.entries(labels).filter(([k])=>['draft','open','locked','live','ended','cancelled'].includes(k))} onChange={(status:string)=>send('eventStatus',{eventId:e.id,status})}/>}</section></section><aside><section className="card"><h3>场地预约</h3>{data.bookings.filter((b:any)=>b.eventId===e.id).map((b:any)=><div className="booking" key={b.id}><strong>{b.name}</strong><span>{hm(b.start)}–{hm(b.end)}</span><small>{b.pricing==='hourly'?`${euro(b.cents)} / 小时`:'时段总价'} · {euro(bookingCents(b))}</small></div>)}{admin&&<button className="ghost" onClick={()=>open('添加场地预约','booking',{eventId:e.id,name:'2号场',start:dt(e.start),end:dt(e.end),pricing:'hourly',cents:1200,reason:'新增预约'},[text('name','场地名称'),timed('start','可用开始'),timed('end','可用结束'),choice('pricing','计价',[['hourly','每小时'],['total','时段总价']]),money('cents','金额 · EUR'),why],(v:any)=>({...v,start:epoch(v.start),end:epoch(v.end)}))}><Plus size={17}/> 添加预约时段</button>}</section><button className="secondary full" onClick={copySignup}><Copy size={17}/> 复制接龙文本</button></aside></div>}
{tab==='signup'&&<><div className="section-title"><h2>接龙名单</h2><div className="actions"><button className="ghost" onClick={copySignup}><Copy size={17}/> 复制</button><button className="primary" onClick={()=>registration()}>参加 / 代报名</button></div></div>{['confirmed','waitlist'].map(status=><section className="card" key={status}><h3>{status==='confirmed'?'正式成员':'候补名单'} <span className="muted">{regs(e).filter((r:any)=>r.status===status).length} 人</span></h3>{regs(e).filter((r:any)=>r.status===status).map((r:any,i:number)=>{const at=data.attendance.find((a:any)=>a.eventId===e.id&&a.playerId===r.playerId&&a.end===null);return <div className="signup-line" key={r.id}><span className="avatar">{i+1}</span><div className="grow"><strong>{name(r.playerId)}</strong><p>{hm(r.arrival)}–{hm(r.departure)} · {at?labels[at.state]:data.attendance.some((a:any)=>a.eventId===e.id&&a.playerId===r.playerId)?'已签退':'未到场'}</p>{r.note&&<small>{r.note}</small>}{r.cancelRequested&&<span className="warning">已申请取消，等待管理员处理</span>}</div><div className="actions compact">{admin&&status==='confirmed'&&<button className="secondary" onClick={()=>open('更新出勤状态','attendance',{eventId:e.id,playerId:r.playerId,at:dt(Math.max(e.start,Math.min(Date.now(),e.end))),state:at?.state==='ready'?'paused':'ready'},[timed('at','实际时间'),choice('state','状态',[['ready','可上场 / 恢复'],['paused','暂时休息（仍计费）'],['left','签退离场']])],(v:any)=>({...v,at:epoch(v.at)}))}>{at?'出勤状态':'签到'}</button>}{own(r.playerId)&&<><button className="ghost" onClick={()=>registration(r.playerId)}>修改</button><button className="ghost danger" onClick={()=>setDanger({action:'cancel',payload:{eventId:e.id,playerId:r.playerId},title:'取消报名',description:Date.now()>e.cancelDeadline&&!admin?'超过自由取消时间，将提交申请给管理员。':'正式名额空出后，最早的有效候补自动递补。',reason:''})}>取消</button></>}{admin&&status==='waitlist'&&i>0&&<button className="ghost" onClick={()=>open('调整候补顺序','moveQueue',{eventId:e.id,playerId:r.playerId,beforePlayerId:regs(e).filter((x:any)=>x.status==='waitlist')[0].playerId,reason:''},[why])}>移到首位</button>}</div></div>})}{!regs(e).some((r:any)=>r.status===status)&&<p className="muted">{status==='confirmed'?'还没有人报名':'暂无候补'}</p>}</section>)}<section className="card"><h3>带一位朋友</h3><p className="muted">朋友有独立档案、名额、比赛和账单。仅你与管理员可管理其报名。</p><button className="secondary" onClick={()=>open('添加朋友档案','friend',{name:''},[text('name','朋友昵称')])}>添加朋友</button></section></>}
{tab==='rounds'&&<><div className="section-title"><h2>下一轮排场</h2>{admin&&<button className="primary" onClick={()=>open('生成下一轮','generate',{eventId:e.id,at:dt(Math.max(e.start,Date.now())),duration:20,seed:Math.floor(Math.random()*1000000)+1},[timed('at','预计开赛'),number('duration','预计时长 · 分钟'),number('seed','随机种子')],(v:any)=>({...v,at:epoch(v.at)}))}><Shuffle size={17}/> 生成下一轮</button>}</div><p className="hint">先照顾上场与等待机会，再平衡实力与重复搭档。新到场者从当前轮次起累计机会。</p>{data.rounds.filter((r:any)=>r.eventId===e.id&&r.status!=='cancelled').slice().reverse().map((r:any)=><section className="card" key={r.id}><div className="row"><h3>第 {data.rounds.filter((x:any)=>x.eventId===e.id&&x.status!=='cancelled').indexOf(r)+1} 轮 <span className="badge">{labels[r.status]}</span></h3><span className="muted">{hm(r.start)} · {r.duration} 分钟</span></div>{r.status==='draft'&&<p className="hint">点选两位球友交换位置，也可与轮休成员交换。锁定分组需先解锁。</p>}<div className="courts-grid">{data.matches.filter((m:any)=>m.roundId===r.id).map((m:any)=><MatchCard key={m.id} m={m} ctx={ctx} interactive={admin&&r.status==='draft'} selected={selected} onSelect={(id:string)=>swap(r,id)}/>)}</div><div className="rest"><strong>本轮轮休 · {r.rest.length} 人</strong><div className="actions">{r.rest.map((id:string)=><button className={'player-pill '+(selected===id?'selected':'')} key={id} disabled={!admin||r.status!=='draft'} onClick={()=>swap(r,id)}>{name(id)}</button>)}</div></div><details><summary>上场与等待机会</summary>{r.eligible.map((id:string)=>{const prior=data.rounds.filter((x:any)=>x.eventId===e.id&&['published','playing','complete'].includes(x.status)&&x.eligible.includes(id));const played=prior.filter((x:any)=>data.matches.some((m:any)=>m.roundId===x.id&&m.status!=='cancelled'&&[...m.a,...m.b].includes(id)));let wait=0;for(const x of [...prior].reverse()){if(played.includes(x))break;wait++}return <div className="row small-line" key={id}><span>{name(id)}</span><span>{played.length}/{prior.length} 轮上场 · 连续等待 {wait} 轮</span></div>})}</details>{admin&&<div className="actions">{r.status==='draft'&&<button className="primary" onClick={()=>send('publish',{roundId:r.id})}><Check size={17}/> 确认发布</button>}{r.status==='published'&&<button className="primary" onClick={()=>open('开始本轮','start',{roundId:r.id,at:dt(Math.max(e.start,Date.now())),monthly:true,elo:true},[timed('at','实际开始'),{key:'monthly',label:'开赛前确定：计入月积分',type:'checkbox'},{key:'elo',label:'计入长期 Rating',type:'checkbox'}],(v:any)=>({...v,at:epoch(v.at)}))}><Play size={17}/> 开始比赛</button>}{['draft','published'].includes(r.status)&&<button className="ghost danger" onClick={()=>setDanger({action:'cancelRound',payload:{roundId:r.id},title:'取消未开始的轮次',description:'已发布但未开始的轮次，其公平性影响也会撤销。',reason:''})}>取消本轮</button>}</div>}</section>)}{!data.rounds.some((r:any)=>r.eventId===e.id)&&<div className="empty">先确认实际到场，再生成本轮分组。</div>}</>}
{tab==='matches'&&<><h2>比赛记录</h2>{data.matches.filter((m:any)=>m.eventId===e.id).slice().reverse().map((m:any)=><MatchCard key={m.id} m={m} ctx={ctx}/>)}{!data.matches.some((m:any)=>m.eventId===e.id)&&<div className="empty">排场发布并开始后，在这里录入结果。</div>}</>}
{tab==='fees'&&<Fees e={e} ctx={ctx}/>}</>}

