'use client';
import {toast} from 'sonner';
import {Plus,Copy} from 'lucide-react';
import {fmt,hm,dt,epoch,euro,text,timed,number,money,choice,why,modes} from './ui';
import FeatureGuide from './feature-guide';
import {bookingCents,ballCents} from '../lib/domain/money';
export default function Fees({e:ev,ctx}:any){const {data,admin,name,open,setDanger,regs}=ctx;const draft=data.drafts.find((x:any)=>x.eventId===ev.id);const versions=data.settlements.filter((x:any)=>x.eventId===ev.id).sort((a:any,b:any)=>b.version-a.version);const latest=versions.find((x:any)=>x.confirmed);const shown=admin?draft:latest;
const bill=(b:any)=><div className="bill-row" key={b.playerId}><div><strong>{name(b.playerId)}</strong><small>{Math.round(b.minutes)} 分钟 · 场地 {euro(b.court)} · 球 {euro(b.ball)} · 其他 {euro(b.other)}</small></div><div><strong>{euro(b.total)}</strong><small>分摊金额</small></div></div>;
return <><div className="section-title"><h2>AA 费用</h2><div className="actions"><span className="badge">费用分摊 · EUR</span><FeatureGuide topic="fees" label="费用怎么算"/></div></div><div className="stats"><section className="card"><span>场地费</span><strong>{euro(data.bookings.filter((b:any)=>b.eventId===ev.id).reduce((n:number,b:any)=>n+bookingCents(b),0))}</strong></section><section className="card"><span>实际耗球费</span><strong>{euro(data.costs.filter((c:any)=>c.eventId===ev.id&&c.type==='ball').reduce((n:number,c:any)=>n+ballCents(c),0))}</strong></section><section className="card"><span>群补贴 / 待分配</span><strong>{euro(shown?.subsidy??0)}</strong><small>待分配 {euro(shown?.unallocated??0)}</small></section></div>
<section className="card"><div className="row"><h3>分摊规则</h3>{admin&&<button className="ghost" onClick={()=>open('修改分摊模式','modes',{eventId:ev.id,courtMode:ev.courtMode,ballMode:ev.ballMode,reason:''},[choice('courtMode','场地费',modes),choice('ballMode','球费',modes),why])}>修改</button>}</div><p>场地：{modes.find(([k])=>k===ev.courtMode)?.[1]} · 球费：{modes.find(([k])=>k===ev.ballMode)?.[1]}</p><p className="hint">时段 AA：每段费用由该段实际在场的人分摊。全程时长：总费用按个人出勤分钟比例分摊。暂时休息和正常轮休仍计入出勤。</p></section>
<section className="card"><div className="row"><h3>费用项目</h3>{admin&&<div className="actions"><button className="secondary" onClick={()=>open('记录实际耗球','cost',{eventId:ev.id,type:'ball',name:'',pricing:'tube',cents:2400,tubeCount:12,tubes:0,loose:0,start:'',end:'',bearer:'members',reason:'实际耗球记录'},[text('name','型号'),choice('pricing','计价',[['tube','每筒价格'],['unit','单颗价格']]),money('cents','价格 · EUR'),number('tubeCount','每筒颗数'),number('tubes','消耗整筒数'),number('loose','另加颗数'),timed('start','消耗开始（可选）',true),timed('end','消耗结束（可选）',true),choice('bearer','承担',[['members','成员分摊'],['subsidy','群补贴']]),why],(v:any)=>{const {tubes,loose,...rest}=v;return {...rest,used:tubes*v.tubeCount+loose,start:v.start?epoch(v.start):null,end:v.end?epoch(v.end):null}})}><Plus size={16}/> 耗球</button><button className="ghost" onClick={()=>open('其他费用','cost',{eventId:ev.id,type:'other',name:'',pricing:'total',cents:0,tubeCount:12,used:0,start:null,end:null,bearer:'members',reason:''},[text('name','项目名称'),money('cents','金额 · EUR'),choice('bearer','承担',[['members','成员等额分摊'],['subsidy','群补贴']]),why])}>其他费用</button></div>}</div>
{data.bookings.filter((b:any)=>b.eventId===ev.id).map((b:any)=><div className="small-line row" key={b.id}><div><strong>{b.name} · {hm(b.start)}–{hm(b.end)}</strong><small>{b.bearer==='subsidy'?'群补贴承担':'成员分摊'}</small></div><span>{euro(bookingCents(b))}</span>{admin&&<><button className="ghost" onClick={()=>open('指定场地费用承担','bookingBearer',{bookingId:b.id,bearer:b.bearer??'members',reason:''},[choice('bearer','承担',[['members','成员分摊'],['subsidy','群补贴承担']]),why])}>承担</button><button className="ghost" onClick={()=>open('修正场地费用与时段','bookingEdit',{bookingId:b.id,name:b.name,start:dt(b.start),end:dt(b.end),pricing:b.pricing,cents:b.cents,reason:''},[text('name','场地名称'),timed('start','预约开始'),timed('end','预约结束'),choice('pricing','计价方式',[['hourly','每小时'],['total','时段总价']]),money('cents','金额 · EUR'),why],(v:any)=>({...v,start:epoch(v.start),end:epoch(v.end)}))}>修正预约</button></>}</div>)}
{data.costs.filter((c:any)=>c.eventId===ev.id).map((c:any)=><div className="small-line" key={c.id}><div className="row"><strong>{c.name}</strong><span>{euro(c.type==='ball'?ballCents(c):c.cents)}</span></div><small>{c.type==='ball'?`${c.used} 颗 · ${c.pricing==='tube'?euro(c.cents)+' / '+c.tubeCount+'颗':euro(c.cents)+' / 颗'}`:'其他费用'} · {c.start?hm(c.start)+'–'+hm(c.end):c.type==='ball'?'按时段估算（有参与者的场地分钟）':'整场'} · {c.bearer==='subsidy'?'群补贴':'成员分摊'}</small>{admin&&<div className="actions"><button className="ghost danger" onClick={()=>setDanger({action:'deleteCost',payload:{costId:c.id},title:'移除费用项目',description:'下次保存分摊结果生成新版本，旧结果仍可查看。',reason:''})}>移除</button>{c.type==='ball'&&<button className="ghost" onClick={()=>open('修正球费时段','costOverride',{costId:c.id,start1:dt(ev.start),end1:dt(ev.start+Math.floor((ev.end-ev.start)/2)),amount1:Math.floor(ballCents(c)/2),start2:dt(ev.start+Math.floor((ev.end-ev.start)/2)),end2:dt(ev.end),amount2:ballCents(c)-Math.floor(ballCents(c)/2),reason:''},[timed('start1','第一段开始'),timed('end1','第一段结束'),money('amount1','第一段球费 · EUR'),timed('start2','第二段开始'),timed('end2','第二段结束'),money('amount2','第二段球费 · EUR'),why],(v:any)=>({costId:v.costId,reason:v.reason,segments:[{start:epoch(v.start1),end:epoch(v.end1),cents:v.amount1},{start:epoch(v.start2),end:epoch(v.end2),cents:v.amount2}]}),'两段合计必须等于项目总球费，支持金额为0；更多时段可添加独立耗球记录。')}>时段调整</button>}</div>}</div>)}</section>
{admin&&<section className="card"><h3>独立费用豁免</h3>{regs(ev).filter((r:any)=>r.status==='confirmed').map((r:any)=><div className="small-line row" key={r.id}><div><strong>{name(r.playerId)}</strong><small>场地：{r.courtExempt.mode==='none'?'正常分摊':r.courtExempt.mode==='subsidy'?'群补贴':'其他成员分担'} · 球：{r.ballExempt.mode==='none'?'正常分摊':r.ballExempt.mode==='subsidy'?'群补贴':'其他成员分担'}</small></div><button className="ghost" onClick={()=>open('设置单项豁免','exemption',{eventId:ev.id,playerId:r.playerId,type:'ball',mode:r.ballExempt.mode,reason:''},[choice('type','费用类别',[['court','场地费'],['ball','球费']]),choice('mode','承担方式',[['none','正常分摊'],['redistribute','豁免，由其他成员分担'],['subsidy','豁免，由群补贴承担']]),why])}>调整</button></div>)}</section>}
<section className="card"><div className="row"><h3>{admin?'每人分摊金额 · 预览':'每人分摊金额'}</h3><strong>{euro(shown?.total??0)}</strong></div>{shown?.unallocated>0&&<p className="warning">仍有 {euro(shown.unallocated)} 待分配。核对出勤或指定群补贴承担，处理完毕才能正式结算。</p>}{shown?.bills.map(bill)}{!shown?.bills.length&&<div className="empty">尚无实际出勤或已确认分摊结果</div>}{admin&&<div className="actions"><button className="secondary" onClick={()=>open('保存分摊草稿','settle',{eventId:ev.id,confirmed:false,reason:''},[why])}>保存草稿</button><button className="primary" disabled={shown?.unallocated>0} onClick={()=>open('确认分摊结果','settle',{eventId:ev.id,confirmed:true,reason:''},[why],undefined,'核对费用、豁免及群补贴，保存每人的分摊金额。')}>确认分摊</button>{latest&&<button className="ghost" onClick={async()=>{try{await navigator.clipboard.writeText(`${data.settings.name} · ${ev.title} · 费用分摊 v${latest.version}\n总费用 ${euro(latest.total)}，群补贴 ${euro(latest.subsidy)}\n${latest.bills.map((b:any)=>`${name(b.playerId)}：${euro(b.total)}`).join('\n')}`);toast.success('已复制分摊金额')}catch{toast.error('复制失败')}}}><Copy size={16}/> 复制分摊金额</button>}</div>}</section>
{shown&&<section className="card"><h3>逐时段核对明细</h3>{shown.detail.map((d:any,i:number)=><details className="small-line" key={i}><summary>{d.name} · {hm(d.start)}–{hm(d.end)} · {euro(d.cents)} {d.estimated?'· 按时段估算':''}</summary>{Object.entries(d.shares).map(([id,c]:any)=><div className="row" key={id}><span>{name(id)}</span><span>{euro(c)}</span></div>)}<p className="hint">群补贴 {euro(d.subsidy)} · 待分配 {euro(d.unallocated)}</p></details>)}</section>}
<section className="card"><h3>分摊历史</h3>{versions.map((v:any)=><details className="small-line" key={v.id}><summary>v{v.version} · {v.confirmed?'已确认':'草稿'} · {fmt(v.created)} · {euro(v.total)}</summary><p>{v.reason}</p>{v.bills.map((b:any)=><div className="row" key={b.playerId}><span>{name(b.playerId)}</span><span>{euro(b.total)}</span></div>)}</details>)}</section>
{admin&&<section className="card"><h3>实际出勤时段</h3>{data.attendance.filter((a:any)=>a.eventId===ev.id).map((a:any)=><div className="row small-line" key={a.id}><div>{name(a.playerId)}<small>{hm(a.start)}–{a.end?hm(a.end):'尚未签退'}</small></div><button className="ghost" onClick={()=>open('修正实际出勤','attendanceEdit',{attendanceId:a.id,start:dt(a.start),end:a.end?dt(a.end):'',reason:''},[timed('start','签到'),timed('end','签退（留空表示仍在场）',true),why],(v:any)=>({...v,start:epoch(v.start),end:v.end?epoch(v.end):null}))}>修正</button></div>)}</section>}
</>}



