'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import FeatureGuide from './feature-guide';
import {Pick} from './ui';
import {canManageEvent} from '../lib/domain/permissions';
export default function PhotoGallery({ctx,eventId,playerId,avatar=false}:any){const {data,name,refresh}=ctx;const [file,setFile]=useState<File|null>(null),[matchId,setMatchId]=useState('none'),[person,setPerson]=useState('none'),[caption,setCaption]=useState(''),[busy,setBusy]=useState(false);const photos=data.photos?.filter((p:any)=>p.kind==='photo'&&(eventId?p.eventId===eventId:p.playerIds.includes(playerId)))??[];const eventMatches=data.matches.filter((m:any)=>m.eventId===eventId&&m.status!=='cancelled');const attended=data.players.filter((p:any)=>data.attendance.some((a:any)=>a.eventId===eventId&&a.playerId===p.id));const canUpload=avatar?(playerId===data.me.playerId||(ctx.admin&&(!data.players.find((p:any)=>p.id===playerId)?.protectedOwner||data.me.isOwner))):!!eventId&&(canManageEvent(data.me,data.events.find((e:any)=>e.id===eventId)??{})||data.attendance.some((a:any)=>a.eventId===eventId&&a.playerId===data.me.playerId));
 async function upload(){if(!file)return;setBusy(true);try{const f=new FormData();f.set('file',file);f.set('kind',avatar?'avatar':'photo');f.set('requestId',crypto.randomUUID());f.set('revision',String(data.revision));f.set('caption',caption);if(avatar)f.set('playerId',playerId);else{f.set('eventId',eventId);f.set('matchId',matchId==='none'?'':matchId);f.set('playerIds',JSON.stringify(person==='none'?[]:[person]))}const r=await fetch('/api/photos',{method:'POST',body:f}),d:any=await r.json();if(!r.ok)throw new Error(d.error);setFile(null);setCaption('');await refresh();toast.success(avatar?'头像已更新':'照片已关联到活动、比赛及球友主页')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <section className={avatar?'avatar-upload':'card'}>{!avatar&&<div className="section-title"><h3>{eventId?'活动相册':'球友相册'}</h3><FeatureGuide rules={data.settings.rules} topic="photos" label="照片关联说明"/></div>}{canUpload&&<div className="upload-form"><label>{avatar?'选择头像':'上传活动照片'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>{!avatar&&<><label>关联比赛<Pick value={matchId} onChange={setMatchId} options={[['none','仅关联活动'],...eventMatches.map((m:any)=>[m.id,`${m.a.map(name).join('/')} 对阵 ${m.b.map(name).join('/')}`])]}/></label>{matchId==='none'&&<label>关联球友（可选）<Pick value={person} onChange={setPerson} options={[['none','暂不关联球友'],...attended.map((p:any)=>[p.id,p.name])]}/></label>}<label>照片说明<input value={caption} maxLength={300} onChange={e=>setCaption(e.target.value)}/></label><p className="hint">选择比赛后，自动关联该场四名参赛者。支持常见照片、透明图和网页图片格式，最多5兆字节。</p></>}<button className="secondary" disabled={!file||busy} onClick={upload}>{busy?'上传中…':avatar?'保存头像':'上传并关联'}</button></div>}{!avatar&&<div className="photo-grid">{photos.map((p:any)=><figure key={p.id}><a href={'/api/photos/'+p.id} target="_blank" rel="noreferrer"><img src={'/api/photos/'+p.id} alt={p.caption||'活动照片'} loading="lazy"/></a><figcaption>{p.caption}<small>{p.playerIds.map(name).join(' · ')}</small></figcaption></figure>)}{!photos.length&&<p className="muted">还没有关联照片。</p>}</div>}</section>}
