'use client';
import {month} from '../lib/domain/types';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Pick,dt,epoch} from './ui';
export default function ScoreDialog({m,ctx,close}:any){const rules=ctx.data.seasons.find((s:any)=>s.id===month(m.start))?.rules??ctx.data.settings.rules;const signed=(n:number)=>(n>0?'+':'')+n;const [format,setFormat]=useState(m.playMode==='koc'?'single':m.games.length>1?'best3':'single'),[third,setThird]=useState(m.games.length===3),[scores,setScores]=useState([0,1,2].map(i=>m.games[i]??{a:i===1?15:21,b:i===1?21:15})),[end,setEnd]=useState(dt(m.end??Math.max(m.start+60000,Math.min(ctx.data.events.find((e:any)=>e.id===m.eventId).end,Date.now())))),[reason,setReason]=useState(m.status==='complete'?'':'接龙球友确认比赛完成');
 async function save(e:React.FormEvent){e.preventDefault();try{const games=scores.slice(0,format==='single'?1:third?3:2);await ctx.action('score',{matchId:m.id,a:games[0].a,b:games[0].b,games,end:epoch(end),reason});close()}catch{}}
 return <Dialog open historyCloseBlocked={ctx.busy} onOpenChange={v=>{if(!v&&!ctx.busy)close()}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{m.status==='complete'?'修正比赛结果':'录入比分'}</DialogTitle><DialogDescription>{format==='single'?'默认一局一轮。本局结束后录入比分，回到活动安排下一轮；每局独立计算胜负和积分。':'三局两胜是可选玩法，须有一方赢两局；修改历史结果会重新计算积分和实力分。'}</DialogDescription></DialogHeader><form onSubmit={save}><p className="hint">{m.monthly?`每胜局 ${signed(rules.win)} 分，每负局 ${signed(rules.loss)} 分；总积分允许为负。保存或修正后自动重算，不重复累计。`:'本场为自由赛，不增减榜单积分。'}</p><div className="form-fields"><details open={format==='best3'}><summary>其他比赛形式（可选）</summary><label>比赛形式<Pick value={format} onChange={setFormat} options={m.playMode==='koc'?[['single','个人轮转：一局一轮']]:[['single','一局一轮（默认）'],['best3','三局两胜（可选）']]}/></label></details>{scores.slice(0,format==='single'?1:third?3:2).map((g,i)=><div className="score-input-row" key={i}><span>{format==='single'?'本局比分':'第'+(i+1)+'局'}</span><label>{ctx.name(m.a[0])} / {ctx.name(m.a[1])}<input aria-label={'第'+(i+1)+'局甲队比分'} type="number" min={0} required value={g.a} onChange={e=>setScores(scores.map((x,j)=>j===i?{...x,a:Number(e.target.value)}:x))}/></label><label>{ctx.name(m.b[0])} / {ctx.name(m.b[1])}<input aria-label={'第'+(i+1)+'局乙队比分'} type="number" min={0} required value={g.b} onChange={e=>setScores(scores.map((x,j)=>j===i?{...x,b:Number(e.target.value)}:x))}/></label></div>)}{format==='best3'&&<label className="check-label"><Checkbox checked={third} onCheckedChange={v=>setThird(v===true)}/>打到第三局</label>}<label>实际结束 · 马德里时间<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label><label>录入 / 修改原因<input required value={reason} onChange={e=>setReason(e.target.value)}/></label></div><button className="primary full" disabled={ctx.busy}>{ctx.busy?'正在保存…':'确认结果'}</button></form></DialogContent></Dialog>}
