'use client';
import {month} from '../lib/domain/types';
import {useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Pick} from './ui';
import {initialScoreDrafts,scoreEntryPayload} from '../lib/client/score-reminder';
export default function ScoreDialog({m,ctx,close}:any){const live=ctx.data.rounds.find((r:any)=>r.id===m.roundId)?.live||(m.status==='playing'&&ctx.data.events.find((e:any)=>e.id===m.eventId)?.livePlay?.enabled);const rules=ctx.data.seasons.find((s:any)=>s.id===month(m.start))?.rules??ctx.data.settings.rules;const signed=(n:number)=>(n>0?'+':'')+n;const [format,setFormat]=useState(live||m.playMode==='koc'?'single':m.games.length>1?'best3':'single'),[third,setThird]=useState(m.games.length===3),[scores,setScores]=useState(()=>initialScoreDrafts(m)),[reason,setReason]=useState(m.status==='complete'?'':'接龙球友确认比赛完成'),[error,setError]=useState('');
 async function save(e:React.FormEvent){e.preventDefault();setError('');try{const payload=scoreEntryPayload(m,scores,format==='single'?1:third?3:2,reason);await ctx.action('score',payload);close()}catch(e){setError(e instanceof Error?e.message:'暂时未能保存比分，请重试')}}
 return <Dialog open historyCloseBlocked={ctx.busy} onOpenChange={v=>{if(!v&&!ctx.busy)close()}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{m.status==='complete'?'修正比赛结果':'录入比分'}</DialogTitle><DialogDescription>{format==='single'?'默认一局一轮。录入比分即结束本局。实时排场会自动更新场上对局；每局独立计算胜负和积分。':'三局两胜是可选玩法，须有一方赢两局；修改历史结果会重新计算积分和实力分。'}</DialogDescription></DialogHeader><form onSubmit={save}><p className="hint">{ctx.data.events.find((e:any)=>e.id===m.eventId)?.title} · {ctx.data.bookings.find((b:any)=>b.id===m.courtId)?.name??'比赛场地'}</p><p className="hint">{`每胜局 ${signed(rules.win)} 分，每负局 ${signed(rules.loss)} 分；总积分允许为负。保存或修正后自动重算，不重复累计。`}</p><div className="form-fields">{!live&&<details open={format==='best3'}><summary>其他比赛形式（可选）</summary><label>比赛形式<Pick value={format} onChange={setFormat} options={m.playMode==='koc'?[['single','个人轮转：一局一轮']]:[['single','一局一轮（默认）'],['best3','三局两胜（可选）']]}/></label></details>}{scores.slice(0,format==='single'?1:third?3:2).map((g,i)=><div className="score-input-row" key={i}><span>{format==='single'?'本局比分':'第'+(i+1)+'局'}</span><label>{m.a.includes(ctx.data.me.playerId)?'你所在队伍 · ':''}{ctx.name(m.a[0])} / {ctx.name(m.a[1])}<input aria-label={'第'+(i+1)+'局甲队比分'} type="number" inputMode="numeric" step={1} min={0} max={rules.ceiling} required value={g.a} onChange={e=>setScores(scores.map((x,j)=>j===i?{...x,a:e.target.value===''?'':Number(e.target.value)}:x))}/></label><label>{m.b.includes(ctx.data.me.playerId)?'你所在队伍 · ':''}{ctx.name(m.b[0])} / {ctx.name(m.b[1])}<input aria-label={'第'+(i+1)+'局乙队比分'} type="number" inputMode="numeric" step={1} min={0} max={rules.ceiling} required value={g.b} onChange={e=>setScores(scores.map((x,j)=>j===i?{...x,b:e.target.value===''?'':Number(e.target.value)}:x))}/></label></div>)}{format==='best3'&&<label className="check-label"><Checkbox checked={third} onCheckedChange={v=>setThird(v===true)}/>打到第三局</label>}<label>录入 / 修改原因<input required value={reason} onChange={e=>setReason(e.target.value)}/></label></div>{error&&<p className="connection-note" role="alert">{error}</p>}<button className="primary full" disabled={ctx.busy}>{ctx.busy?'正在保存…':'确认结果'}</button></form></DialogContent></Dialog>}
