'use client';
import {useState} from 'react';
import {ArrowLeft,UsersRound} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {styleTags} from '../lib/domain/social';
import {choice,fmt,Pick,labels} from './ui';
import FeatureGuide from './feature-guide';
import PlayerProfile from './player-profile';
import CultivationOrnament from './cultivation-ornament';
import './player-list.css';
import PlayerSocialCard from './player-social-card';
import {canManageEvent} from '../lib/domain/permissions';
export function Avatar({p,size=''}:any){const [failedId,setFailedId]=useState<string|null>(null);const name:string=p?.name??'球友';return p?.avatarId&&p.avatarId!==failedId?<img className={'avatar '+size} src={'/api/photos/'+p.avatarId} alt={name+'的头像'} loading="lazy" onError={()=>setFailedId(p.avatarId)}/>:<span className={'avatar '+size} aria-label={name+'的默认头像'}>{Array.from(name)[0]??'球'}</span>}
export default function SocialHub({ctx,year,initialPlayerId,activeTab='players',onTabChange,onPlayerSelect,onBackToPlayers,backLabel='返回球友列表'}:any){
 const {data,name,admin,open,send}=ctx;
 const challengeMatches=(c:any)=>data.matches.filter((m:any)=>canManageEvent(data.me,data.events.find((e:any)=>e.id===m.eventId)??{})&&['draft','published'].includes(m.status)&&((m.a.includes(c.challengerId)&&m.b.includes(c.targetId))||(m.b.includes(c.challengerId)&&m.a.includes(c.targetId))));
 const tab=activeTab==='annual'?'players':activeTab;
 const selected=initialPlayerId||null;
 const [centerId,setCenterId]=useState(data.me.playerId||data.players[0]?.id||'');
 const [relation,setRelation]=useState('partners');
 const p=selected?data.players.find((player:any)=>player.id===selected):null;
 const isOwn=!!p&&p.id===data.me.playerId;
 const perspective=isOwn?'你':'这位球友';
 const stats=data.social.stats.find((row:any)=>row.playerId===p?.id)??{partners:[],opponents:[]};
 const center=data.players.find((player:any)=>player.id===centerId)??data.players[0];
 const centerStats=data.social.stats.find((row:any)=>row.playerId===center?.id)??{partners:[],opponents:[]};
 const roster=data.players.filter((player:any)=>player.enabled);
 const openPlayer=(id:string)=>onPlayerSelect(id);
 const returnToPlayers=()=>onBackToPlayers();
 const changeTab=(value:string)=>onTabChange(value==='annual'?'players':value);
 const relationRow=(r:any,challenge=false)=><div className="relation-row" key={r.playerId}><button type="button" className="ghost pl-relation-link" onClick={()=>openPlayer(r.playerId)}>{name(r.playerId)}</button><span>{r.wins}胜 {r.losses}负 · {r.games}场 · {Math.round(r.rate*100)}%</span>{challenge&&selected===data.me.playerId&&r.losses>0&&<button className="secondary" onClick={()=>send('challenge',{targetId:r.playerId})}>发起复仇</button>}</div>; const highlight=(title:string,r:any)=><section className="mini-stat"><span>{title}</span><strong>{r?name(r.playerId):'样本不足'}</strong><small>{r?`${r.wins}胜${r.losses}负 · ${Math.round(r.rate*100)}%`:'至少3场有效交手 / 组队'}</small></section>;
 return <div className="pl-hub">
 {p?<header className="pl-detail-heading"><button type="button" className="pl-back" onClick={returnToPlayers}><ArrowLeft size={18} aria-hidden="true"/>{backLabel}</button><div><p className="eyebrow">球友档案</p><h1>球员档案</h1></div></header>:<><div className="heading"><div><p className="eyebrow">羽林同修</p><h1>球场上的故事。</h1></div><CultivationOrnament variant="hero"/></div><Tabs value={tab==='annual'?'players':tab} onValueChange={changeTab}><TabsList className="social-tabs">{[['players','球友'],['network','关系图'],['challenges','复仇局'],['funny','趣味榜']].map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList></Tabs><div className="feature-actions">{tab==='players'&&<><FeatureGuide rules={data.settings.rules} topic="rating" label="境界说明"/><FeatureGuide rules={data.settings.rules} topic="state" label="状态值"/></>}{!p&&tab==='network'&&<FeatureGuide rules={data.settings.rules} topic="partners" label="关系图说明"/>}{!p&&tab==='challenges'&&<FeatureGuide rules={data.settings.rules} topic="challenges" label="复仇规则"/>}{!p&&tab==='funny'&&<FeatureGuide rules={data.settings.rules} topic="titles" label="趣味称号规则"/>}</div></>}
 {tab==='players'&&!p&&<section className="pl-directory" aria-labelledby="pl-roster-title"><header className="pl-directory-heading"><div><h2 id="pl-roster-title"><UsersRound size={20} aria-hidden="true"/>球友列表</h2><p>轻转名帖，看本命战拍；走进档案，认识这位同修。</p></div><span className="pl-count">{roster.length} 位球友</span></header><div className="pl-player-grid">{roster.map((player:any)=>{const row=data.social.stats.find((item:any)=>item.playerId===player.id),monthly=data.leaderboard.find((item:any)=>item.playerId===player.id),photo=data.photos.filter((item:any)=>item.kind==='racket'&&item.playerIds.includes(player.id)).sort((a:any,b:any)=>b.created-a.created)[0];return <PlayerSocialCard key={player.id} player={player} stats={row} monthly={monthly} photo={photo} avatar={<Avatar p={player}/>} self={player.id===data.me.playerId} onProfile={()=>openPlayer(player.id)}/>})}</div>{!roster.length&&<p className="empty">还没有可查看的球友。</p>}</section>} {tab==='players'&&p&&<div className="pl-detail"><PlayerProfile key={p.id} p={p} stats={stats} ctx={ctx}/>
 <section className="card"><h3>球友眼中的打法</h3><div className="tag-votes">{styleTags.map(tag=>{const votes=data.tagVotes.filter((v:any)=>v.playerId===p.id&&v.tag===tag),active=votes.some((v:any)=>v.voterId===data.me.id);return <button className={'tag-button '+(active?'active':'')} key={tag} onClick={()=>send('tagVote',{playerId:p.id,tag,active:!active})}>{tag} · {votes.length}票</button>})}</div><p className="hint">每个账号每个标签一票，再次点选可撤回。</p></section><div className="highlights">{highlight('最佳搭档',stats.bestPartner)}{highlight('最坑搭档',stats.worstPartner)}{highlight(perspective+'最克谁',stats.dominates)}{highlight('谁最克'+perspective,stats.nemesis)}</div><section className="card"><h3>{isOwn?'你的搭档默契度':'这位球友的搭档默契度'}</h3>{stats.partners.map((r:any)=>relationRow(r))}{!stats.partners.length&&<p className="muted">有完整比赛后才能计算默契度。</p>}<p className="hint">按与{perspective}同队的双打比赛统计胜率；“最佳 / 最坑”至少需要3场样本。</p></section><section className="card"><h3>{isOwn?'你的对位交手战绩':'这位球友的对位交手战绩'}</h3>{stats.opponents.map((r:any)=>relationRow(r,true))}{!stats.opponents.length&&<p className="muted">还没有有效交手记录。</p>}<p className="hint">这是双方在不同双打队伍中的交手结果，包含各自搭档的影响。</p></section><div className="feature-actions"><FeatureGuide rules={data.settings.rules} topic="titles" label="称号与标签"/><FeatureGuide rules={data.settings.rules} topic="partners" label="搭档与克制"/></div></div>}
 {!p&&tab==='network'&&<section className="card"><div className="section-title"><h2>球友关系图</h2><div className="actions"><Pick value={centerId} onChange={setCenterId} options={data.players.map((p:any)=>[p.id,p.name])}/><Pick value={relation} onChange={setRelation} options={[["partners","经常搭档"],["opponents","经常交手"]]}/></div></div><p className="hint">选一位球友作为中心，点击关系节点查看其档案。线越粗，交手 / 组队次数越多。</p><Network rows={centerStats[relation]} center={center} name={name} onSelect={openPlayer}/>{centerStats[relation].map((r:any)=>relationRow(r))}</section>}
 {!p&&tab==='challenges'&&<><section className="card"><h3>复仇挑战</h3><p>在球友档案的交手战绩中，向曾击败你的球友发起挑战。双方接受后，由活动创建者或管理员安排到一场未开始的双打比赛。</p></section>{data.challenges.slice().reverse().map((c:any)=>{const m=data.matches.find((m:any)=>m.id===c.matchId),resolved=m?.status==='complete',cancelled=m&&['cancelled','forfeit'].includes(m.status),isTarget=data.players.find((p:any)=>p.id===c.targetId)?.ownerId===data.me.id;return <section className="card" key={c.id}><div className="row"><h3>{name(c.challengerId)} 对阵 {name(c.targetId)}</h3><span className="badge">{resolved?'已交手':cancelled?'比赛未完成':{pending:'待回应',accepted:'已接受',declined:'已婉拒',cancelled:'已撤回'}[c.status as 'pending']}</span></div><p className="muted">{fmt(c.created)} · {data.social.stats.find((s:any)=>s.playerId===c.challengerId)?.opponents.find((r:any)=>r.playerId===c.targetId)?.wins??0}胜 {data.social.stats.find((s:any)=>s.playerId===c.challengerId)?.opponents.find((r:any)=>r.playerId===c.targetId)?.losses??0}负</p>{resolved&&<p className="warning">{m.a.includes(c.challengerId)===(m.scoreA>m.scoreB)?'复仇成功！':'再战一场，故事继续。'}</p>}{c.status==='pending'&&(isTarget||admin)&&<div className="actions"><button className="primary" onClick={()=>send('challengeRespond',{challengeId:c.id,status:'accepted'})}>接受挑战</button><button className="ghost" onClick={()=>send('challengeRespond',{challengeId:c.id,status:'declined'})}>婉拒</button></div>}{!c.matchId&&['pending','accepted'].includes(c.status)&&(c.challengerId===data.me.playerId||admin)&&<button className="ghost" onClick={()=>send('challengeRespond',{challengeId:c.id,status:'cancelled'})}>撤回</button>}{challengeMatches(c).length>0&&c.status==='accepted'&&!c.matchId&&<button className="secondary" onClick={()=>open('安排复仇局','challengeMatch',{challengeId:c.id,matchId:''},[choice('matchId','双方分居两队的未开始比赛',challengeMatches(c).map((m:any)=>[m.id,m.a.map(name).join('/')+' 对阵 '+m.b.map(name).join('/')]))])}>关联比赛</button>}{m&&<p className="hint">已关联：{m.a.map(name).join('/')} 对阵 {m.b.map(name).join('/')} · {labels[m.status]??'比赛记录'}</p>}</section>})}{!data.challenges.length&&<section className="card"><p className="muted">还没有复仇挑战。</p></section>}</>}
 {!p&&tab==='funny'&&<><section className="card"><h2>本月搞笑数据 · {data.period}</h2><div className="highlights">{[['closeLosses','最常输21:19'],['threeGames','最爱打三局'],['maxLosses','最长连败'],['overtime','加班局之王'],['longestMinutes','最长一场（分钟）']].map(([key,label])=>{const list=[...data.social.funny].filter((r:any)=>r[key]>0).sort((a:any,b:any)=>b[key]-a[key]);return <section className="mini-stat" key={key}><span>{label}</span><strong>{list[0]?list.filter((r:any)=>r[key]===list[0][key]).map((r:any)=>name(r.playerId)).join(' / '):'暂无记录'}</strong><small>{list[0]?Number(list[0][key]).toFixed(key==='longestMinutes'?1:0):'—'}</small></section>})}</div><p className="hint">21:19按决胜局失利统计；加班局指超过21分的局。三局榜只使用实际录入的三局数据。</p></section><section className="card"><h2>活动人格 · {year}</h2><div className="highlights">{[['early','早到王'],['onTime','压线王'],['fastSignup','报名最快的人'],['promoted','候补逆袭王']].map(([key,label])=>{const rows=[...data.social.personality].filter((r:any)=>r[key]>0).sort((a:any,b:any)=>b[key]-a[key]);return <section className="mini-stat" key={key}><span>{label}</span><strong>{rows[0]?rows.filter((r:any)=>r[key]===rows[0][key]).map((r:any)=>name(r.playerId)).join(' / '):'暂无记录'}</strong><small>{rows[0]?rows[0][key]+'次':'—'}</small></section>})}</div><p className="hint">早到与压线仅使用已经发生的历史到场记录，默认参加不会凭预计时间生成称号；最快报名使用第1位报名记录。旧记录缺少时间戳时不补造统计。</p></section></>}
 </div>}
function Network({rows,center,name,onSelect}:any){const peers=rows.slice(0,6);if(!peers.length)return <p className="empty">比赛完成后自动生成关系网络。</p>;return <svg className="network" viewBox="0 0 600 470" role="img" aria-label={center.name+'的球友关系图'}><title>{center.name}的搭档或交手关系</title>{peers.map((r:any,i:number)=>{const angle=i/peers.length*2*Math.PI-Math.PI/2,x=300+200*Math.cos(angle),y=235+165*Math.sin(angle);return <g key={r.playerId}><line x1={300} y1={235} x2={x} y2={y} stroke="#b1aed4" strokeWidth={Math.min(8,1+r.games)}/><g role="button" tabIndex={0} aria-label={name(r.playerId)+' '+r.games+'场 '+r.wins+'胜'+r.losses+'负'} onClick={()=>onSelect(r.playerId)} onKeyDown={e=>{if(['Enter',' '].includes(e.key))onSelect(r.playerId)}}><circle cx={x} cy={y} r={38} fill="#e6e5f3" stroke="#4f46e5"/><text x={x} y={y+5} textAnchor="middle" fontSize={24} fill="#221e54">{name(r.playerId).slice(0,4)}</text><text x={x} y={y+57} textAnchor="middle" fontSize={23} fill="#4f4c6d">{r.games}场 · {Math.round(r.rate*100)}%</text></g></g>})}<circle cx={300} cy={235} r={48} fill="#4f46e5"/><text x={300} y={240} textAnchor="middle" fill="white" fontSize={26}>{center.name.slice(0,4)}</text></svg>}
