import {z} from 'zod';
import {fail,month,type State,type Account,type Event,type Rules,defaultRules} from './types';
import {propose,validateRound,readyIds} from './grouping';
import {calculateSettlement} from './money';
import {validScore,replayRating} from './ranking';
const id=()=>crypto.randomUUID();const text=z.string().trim().min(1).max(150),pid=z.string().min(1).max(100),time=z.number().int().min(0),cents=z.number().int().min(0).max(100000000),reason=z.string().trim().min(1).max(500),mode=z.enum(['equal','duration','interval']);
const rulesSchema=z.object({win:z.number().int().min(0).max(100),loss:z.number().int().min(0).max(100),minimum:z.number().int().min(0).max(500),cap:z.number().int().min(0).max(500),target:z.number().int().min(1).max(100),ceiling:z.number().int().min(1).max(150),lead:z.number().int().min(1).max(10),k:z.number().min(1).max(128),algorithm:z.literal('doubles-elo-v1')});
export async function digest(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
export function authorized(a:Account,action:string){if(!['register','cancel','friend','profile'].includes(action)&&a.role!=='admin')fail('403: 仅管理员可以执行此操作')}
const schemas:Record<string,z.ZodTypeAny>={
 profile:z.object({name:text}),friend:z.object({name:text}),
 event:z.object({title:text,start:time,end:time,venue:text,address:z.string().max(300),capacity:z.number().int().min(4).max(60),signupDeadline:time,cancelDeadline:time,note:z.string().max(2000),status:z.enum(['draft','open']),bookings:z.array(z.object({name:text,start:time,end:time,pricing:z.enum(['hourly','total']),cents})).min(1).max(20)}),
 eventStatus:z.object({eventId:pid,status:z.enum(['draft','open','locked','live','ended','cancelled'])}),
 eventEdit:z.object({eventId:pid,title:text,venue:text,address:z.string().max(300),capacity:z.number().int().min(4).max(60),signupDeadline:time,cancelDeadline:time,note:z.string().max(2000),reason}),
 booking:z.object({eventId:pid,name:text,start:time,end:time,pricing:z.enum(['hourly','total']),cents,reason}),bookingEdit:z.object({bookingId:pid,name:text,start:time,end:time,pricing:z.enum(['hourly','total']),cents,reason}),
 register:z.object({eventId:pid,playerId:pid,arrival:time,departure:time,note:z.string().max(500)}),cancel:z.object({eventId:pid,playerId:pid,reason}),
 moveQueue:z.object({eventId:pid,playerId:pid,beforePlayerId:pid,reason}),
 attendance:z.object({eventId:pid,playerId:pid,at:time,state:z.enum(['ready','paused','left'])}),
 attendanceEdit:z.object({attendanceId:pid,start:time,end:time.nullable(),reason}),
 generate:z.object({eventId:pid,at:time,duration:z.number().int().min(5).max(90),seed:z.number().int().min(1).max(2147483647)}),
 swap:z.object({roundId:pid,p1:pid,p2:pid}),moveCourt:z.object({matchId:pid,courtId:pid}),lock:z.object({matchId:pid,locked:z.boolean()}),publish:z.object({roundId:pid}),start:z.object({roundId:pid,at:time,monthly:z.boolean(),elo:z.boolean()}),cancelRound:z.object({roundId:pid,reason}),
 score:z.object({matchId:pid,a:z.number().int().min(0).max(150),b:z.number().int().min(0).max(150),end:time,reason}),void:z.object({matchId:pid,reason,status:z.enum(['cancelled','forfeit'])}),
 cost:z.object({eventId:pid,type:z.enum(['ball','other']),name:text,pricing:z.enum(['tube','unit','total']),cents,tubeCount:z.number().int().min(1).max(100),used:z.number().int().min(0).max(10000),start:time.nullable(),end:time.nullable(),bearer:z.enum(['members','subsidy']),reason}),
 costOverride:z.object({costId:pid,reason,segments:z.array(z.object({start:time,end:time,cents})).min(1).max(100)}),
 bookingBearer:z.object({bookingId:pid,bearer:z.enum(['members','subsidy']),reason}),deleteCost:z.object({costId:pid,reason}),modes:z.object({eventId:pid,courtMode:mode,ballMode:mode,reason}),
 exemption:z.object({eventId:pid,playerId:pid,type:z.enum(['court','ball']),mode:z.enum(['none','redistribute','subsidy']),reason}),
 settle:z.object({eventId:pid,confirmed:z.boolean(),reason}),payment:z.object({eventId:pid,playerId:pid,cents:z.number().int().min(-100000000).max(100000000),method:z.enum(['Bizum','Revolut','现金','银行转账','其他']),reason}),
 settings:z.object({name:text,invite:z.string().min(8).max(100),rules:rulesSchema}),rating:z.object({playerId:pid,value:z.number().min(0).max(4000),enabled:z.boolean(),reason}),demo:z.object({}),role:z.object({accountId:pid,role:z.enum(['admin','member']),reason}),
 historyPreview:z.object({season:z.string().regex(/^\d{4}-\d{2}$/),rules:rulesSchema}),historyRules:z.object({season:z.string().regex(/^\d{4}-\d{2}$/),rules:rulesSchema,reason}),
};
export async function apply(s:State,a:Account,action:string,input:unknown,now:number){authorized(a,action);const schema=schemas[action];if(!schema)fail('未知操作');const p=schema.parse(input) as any;const before=['score','void','historyRules','rating','attendanceEdit'].includes(action)?{matches:structuredClone(s.matches.filter(m=>m.id===p.matchId)),attendance:structuredClone(s.attendance.filter(a=>a.id===p.attendanceId)),seasons:structuredClone(s.seasons.filter(x=>x.id===p.season)),players:structuredClone(s.players.filter(x=>x.id===p.playerId))}:undefined;
 const event=(e:string)=>s.events.find(x=>x.id===e)??fail('活动不存在');const player=(p:string)=>s.players.find(x=>x.id===p)??fail('参赛者不存在');const own=(p:string)=>{if(a.role!=='admin'&&player(p).ownerId!==a.id)fail('403: 只能管理自己及自己代报的朋友')};const reg=(e:string,p:string)=>s.registrations.find(r=>r.eventId===e&&r.playerId===p)??fail('未找到报名');const round=(r:string)=>s.rounds.find(x=>x.id===r)??fail('轮次不存在');
 if(action==='profile')player(a.playerId).name=p.name;
 else if(action==='friend')s.players.push({id:id(),ownerId:a.id,name:p.name,initialRating:1000,rating:1000,ratedGames:0,enabled:true,ratingReason:'新成员默认初值'});
 else if(action==='event'){if(p.end<=p.start||p.signupDeadline>p.end||p.cancelDeadline>p.end)fail('请检查活动与截止时间');for(const b of p.bookings)checkBooking(p,b);const e={...p,id:id(),courtMode:'interval',ballMode:'interval'};delete e.bookings;s.events.push(e);for(const b of p.bookings)s.bookings.push({...b,id:id(),eventId:e.id})}
 else if(action==='eventStatus'){const e=event(p.eventId);if(p.status==='cancelled'&&s.matches.some(m=>m.eventId===e.id&&m.status==='playing'))fail('请先结束或作废进行中的比赛');e.status=p.status}
 else if(action==='eventEdit'){const e=event(p.eventId);if(p.capacity<s.registrations.filter(r=>r.eventId===e.id&&r.status==='confirmed').length)fail('上限不能低于当前正式人数，请先调整报名名单');if(p.signupDeadline>e.end||p.cancelDeadline>e.end)fail('截止时间不能晚于活动结束');Object.assign(e,{title:p.title,venue:p.venue,address:p.address,capacity:p.capacity,signupDeadline:p.signupDeadline,cancelDeadline:p.cancelDeadline,note:p.note});promote(s,e)}
 else if(action==='booking'){const e=event(p.eventId);checkBooking(e,p);if(s.bookings.some(b=>b.eventId===e.id&&b.name===p.name&&b.start<p.end&&b.end>p.start))fail('同一场地预约时段不能重叠');s.bookings.push({...p,id:id()})}
 else if(action==='bookingEdit'){const b=s.bookings.find(x=>x.id===p.bookingId)??fail('场地预约不存在');const e=event(b.eventId);checkBooking(e,p);if(s.bookings.some(x=>x.id!==b.id&&x.eventId===e.id&&x.name===p.name&&x.start<p.end&&x.end>p.start))fail('同一场地预约时段不能重叠');if(s.matches.some(m=>m.courtId===b.id&&['published','playing'].includes(m.status)&&((m.start??s.rounds.find(r=>r.id===m.roundId)!.start)<p.start||(m.start??s.rounds.find(r=>r.id===m.roundId)!.start)+s.rounds.find(r=>r.id===m.roundId)!.duration*60000>p.end)))fail('调整时段与已发布或进行中的比赛冲突');Object.assign(b,{name:p.name,start:p.start,end:p.end,pricing:p.pricing,cents:p.cents})}
 else if(action==='register'){const e=event(p.eventId);own(p.playerId);if(!player(p.playerId).enabled)fail('成员已停用');if(a.role!=='admin'&&(e.status!=='open'||now>e.signupDeadline))fail('报名已截止');if(['ended','cancelled'].includes(e.status))fail('活动已结束');if(p.arrival<e.start||p.departure>e.end||p.departure<=p.arrival)fail('参加时间应在活动时间内');const old=s.registrations.find(r=>r.eventId===e.id&&r.playerId===p.playerId);if(old&&old.status!=='cancelled'){old.arrival=p.arrival;old.departure=p.departure;old.note=p.note}else{const r={...p,id:old?.id??id(),sequence:Math.max(0,...s.registrations.filter(r=>r.eventId===e.id).map(r=>r.sequence))+1,status:'waitlist' as const,cancelRequested:false,courtExempt:{mode:'none' as const,reason:''},ballExempt:{mode:'none' as const,reason:''}};if(old)s.registrations.splice(s.registrations.indexOf(old),1,r);else s.registrations.push(r);promote(s,e)}}
 else if(action==='cancel'){const e=event(p.eventId);own(p.playerId);const r=reg(e.id,p.playerId);if(r.status==='cancelled')return;if(a.role!=='admin'&&now>e.cancelDeadline){r.cancelRequested=true}else{if(s.matches.some(m=>m.status==='playing'&&m.eventId===e.id&&[...m.a,...m.b].includes(p.playerId)))fail('成员正在比赛，请先完成比赛');r.status='cancelled';r.cancelRequested=false;for(const at of s.attendance.filter(x=>x.eventId===e.id&&x.playerId===p.playerId&&x.end===null)){at.end=now;at.state='left'}promote(s,e)}}
 else if(action==='moveQueue'){const e=event(p.eventId);const r=reg(e.id,p.playerId),before=reg(e.id,p.beforePlayerId);if(r.status!=='waitlist'||before.status!=='waitlist')fail('仅支持调整候补顺序');const queue=s.registrations.filter(r=>r.eventId===e.id&&r.status==='waitlist').sort((a,b)=>a.sequence-b.sequence).filter(x=>x!==r);queue.splice(queue.indexOf(before),0,r);const start=Math.max(0,...s.registrations.filter(x=>x.eventId===e.id&&x.status!=='waitlist').map(x=>x.sequence))+1;queue.forEach((r,i)=>r.sequence=start+i)}
 else if(action==='attendance'){const e=event(p.eventId);if(reg(e.id,p.playerId).status!=='confirmed')fail('只有正式成员可以签到');if(p.at<e.start||p.at>e.end)fail('出勤时间应在活动时段内');let active=s.attendance.find(x=>x.eventId===e.id&&x.playerId===p.playerId&&x.end===null);if(p.state==='left'){if(!active)fail('成员尚未签到');if(p.at<=active.start)fail('签退必须晚于签到');if(s.matches.some(m=>m.status==='playing'&&[...m.a,...m.b].includes(p.playerId)))fail('请先结束该成员正在进行的比赛');active.end=p.at;active.state='left'}else if(active)active.state=p.state;else{if(s.attendance.some(x=>x.eventId===e.id&&x.playerId===p.playerId&&(x.end??e.end)>p.at))fail('出勤时段不能重叠');s.attendance.push({id:id(),eventId:e.id,playerId:p.playerId,start:p.at,end:null,state:p.state})}}
 else if(action==='attendanceEdit'){const at=s.attendance.find(x=>x.id===p.attendanceId)??fail('出勤不存在');const e=event(at.eventId);if(p.start<e.start||(p.end??e.end)>e.end||(p.end??e.end)<=p.start)fail('出勤时段无效');if(s.attendance.some(x=>x.id!==at.id&&x.eventId===e.id&&x.playerId===at.playerId&&x.start<(p.end??e.end)&&(x.end??e.end)>p.start))fail('出勤时段重叠');at.start=p.start;at.end=p.end;if(p.end!==null)at.state='left'}
 else if(action==='generate'){const e=event(p.eventId);if(['cancelled','ended','draft'].includes(e.status))fail('请先开放或开始活动');const old=s.rounds.find(x=>x.eventId===e.id&&x.status==='draft');const locked=s.matches.filter(m=>m.roundId===old?.id&&m.locked);validateRound(s,e.id,p.at,p.duration,locked);const eligible=readyIds(s,e.id,p.at);if(old){s.matches=s.matches.filter(m=>m.roundId!==old.id);s.rounds=s.rounds.filter(r=>r.id!==old.id)}const copy=structuredClone(s);copy.matches.push(...locked.map(m=>({...m,status:'playing' as const})));let courts:{courtId:string;a:string[];b:string[]}[]=[];try{courts=propose(copy,e,p.at,p.duration,p.seed).courts}catch(error){if(!locked.length)throw error}const playing=[...locked.flatMap(m=>[...m.a,...m.b]),...courts.flatMap(m=>[...m.a,...m.b])];const r={id:old?.id??id(),eventId:e.id,start:p.at,duration:p.duration,status:'draft' as const,eligible,rest:eligible.filter(id=>!playing.includes(id)),seed:p.seed};s.rounds.push(r);for(const m of locked)s.matches.push({...m,roundId:r.id});for(const m of courts)s.matches.push({...m,id:id(),eventId:e.id,roundId:r.id,status:'draft',start:null,end:null,scoreA:null,scoreB:null,monthly:true,elo:true,locked:false,enteredBy:null,games:[]})}
 else if(action==='swap'){const r=round(p.roundId);if(r.status!=='draft')fail('仅可交换草稿');const ms=s.matches.filter(m=>m.roundId===r.id);const has=(m:any,p:string)=>[...m.a,...m.b].includes(p);if(ms.some(m=>m.locked&&(has(m,p.p1)||has(m,p.p2))))fail('请先解除锁定');if(!r.eligible.includes(p.p1)||!r.eligible.includes(p.p2))fail('选手不在本轮可用名单');for(const m of ms){m.a=m.a.map(x=>x===p.p1?p.p2:x===p.p2?p.p1:x);m.b=m.b.map(x=>x===p.p1?p.p2:x===p.p2?p.p1:x)}r.rest=r.rest.map(x=>x===p.p1?p.p2:x===p.p2?p.p1:x);validateRound(s,r.eventId,r.start,r.duration,ms)}
 else if(action==='lock'){const m=s.matches.find(x=>x.id===p.matchId)??fail('比赛不存在');if(round(m.roundId).status!=='draft')fail('仅可锁定草稿');m.locked=p.locked}
 else if(action==='moveCourt'){const m=s.matches.find(x=>x.id===p.matchId)??fail('比赛不存在');const r=round(m.roundId);if(r.status!=='draft'||m.locked)fail('仅可修改未锁定草稿');m.courtId=p.courtId;validateRound(s,m.eventId,r.start,r.duration,s.matches.filter(x=>x.roundId===r.id))}
 else if(action==='publish'){const r=round(p.roundId);if(r.status!=='draft')fail('轮次已发布');const ms=s.matches.filter(m=>m.roundId===r.id);validateRound(s,r.eventId,r.start,r.duration,ms);r.status='published';ms.forEach(m=>m.status='published')}
 else if(action==='start'){const r=round(p.roundId);if(r.status!=='published')fail('请先发布本轮');const ms=s.matches.filter(m=>m.roundId===r.id);validateRound(s,r.eventId,p.at,r.duration,ms);r.start=p.at;r.status='playing';const season=month(p.at);if(!s.seasons.some(x=>x.id===season))s.seasons.push({id:season,rules:{...s.settings.rules},version:1});ms.forEach(m=>{m.start=p.at;m.status='playing';m.monthly=p.monthly;m.elo=p.elo})}
 else if(action==='cancelRound'){const r=round(p.roundId);if(!['draft','published'].includes(r.status))fail('只能取消尚未开始的轮次');r.status='cancelled';s.matches.filter(m=>m.roundId===r.id).forEach(m=>m.status='cancelled')}
 else if(action==='score'){const m=s.matches.find(x=>x.id===p.matchId)??fail('比赛不存在');if(!['playing','complete'].includes(m.status)||m.start===null)fail('比赛尚未开始');const rules=s.seasons.find(x=>x.id===month(m.start!))?.rules??s.settings.rules;if(!validScore(p.a,p.b,rules))fail('终局比分不符合目标分、领先分与封顶规则');if(p.end<=m.start||p.end>event(m.eventId).end)fail('结束时间必须晚于开赛且在活动时间内');m.scoreA=p.a;m.scoreB=p.b;m.games=[{a:p.a,b:p.b}];m.end=p.end;m.status='complete';m.enteredBy=a.id;const r=round(m.roundId);if(s.matches.filter(x=>x.roundId===r.id).every(x=>['complete','cancelled','forfeit'].includes(x.status)))r.status='complete';replayRating(s)}
 else if(action==='void'){const m=s.matches.find(x=>x.id===p.matchId)??fail('比赛不存在');m.status=p.status;const r=round(m.roundId);if(s.matches.filter(x=>x.roundId===r.id).every(x=>['complete','cancelled','forfeit'].includes(x.status)))r.status='complete';replayRating(s)}
 else if(action==='cost'){const e=event(p.eventId);if((p.start===null)!==(p.end===null))fail('耗球开始与结束时间必须同时填写');if(p.start!==null&&(p.start<e.start||p.end>e.end||p.end<=p.start))fail('费用时段无效');if(p.type==='ball'&&p.pricing==='total')fail('球费请选择每筒或单颗价格');s.costs.push({...p,id:id()})}
 else if(action==='costOverride'){const c=s.costs.find(c=>c.id===p.costId)??fail('费用不存在');if(c.type!=='ball')fail('仅支持球费时段修正');const e=event(c.eventId);const sorted=[...p.segments].sort((a,b)=>a.start-b.start);for(let i=0;i<sorted.length;i++){const x=sorted[i];if(x.end<=x.start||x.start<e.start||x.end>e.end||(i>0&&x.start<sorted[i-1].end))fail('球费时段不能无效或重叠')}c.overrides=sorted;calculateSettlement(s,e,now)}
 else if(action==='bookingBearer'){const b=s.bookings.find(x=>x.id===p.bookingId)??fail('场地预约不存在');b.bearer=p.bearer}
 else if(action==='deleteCost'){s.costs=s.costs.filter(c=>c.id!==p.costId)}
 else if(action==='modes'){const e=event(p.eventId);e.courtMode=p.courtMode;e.ballMode=p.ballMode}
 else if(action==='exemption'){const r=reg(p.eventId,p.playerId);r[p.type==='court'?'courtExempt':'ballExempt']={mode:p.mode,reason:p.reason}}
 else if(action==='settle'){const e=event(p.eventId);if(p.confirmed&&s.attendance.some(x=>x.eventId===e.id&&x.end===null)&&now<e.end)fail('请先签退实际参加者，再确认正式结算');const result=calculateSettlement(s,e,now);if(p.confirmed&&result.unallocated)fail('仍有待分配费用，请通过费用承担设置指定群补贴或实际出勤');s.settlements.push({...result,id:id(),created:now,version:Math.max(0,...s.settlements.filter(x=>x.eventId===e.id).map(x=>x.version))+1,confirmed:p.confirmed,reason:p.reason})}
 else if(action==='payment'){event(p.eventId);player(p.playerId);if(!p.cents)fail('金额不能为0');if(!s.settlements.some(x=>x.eventId===p.eventId&&x.confirmed&&x.bills.some(b=>b.playerId===p.playerId)))fail('请先完成正式结算');s.payments.push({...p,id:id(),at:now,actor:a.id})}
 else if(action==='settings'){if(p.rules.ceiling<p.rules.target||p.rules.lead>p.rules.target)fail('比赛规则无效');s.settings.name=p.name;s.settings.inviteHash=await digest(p.invite);s.settings.rules=p.rules}
 else if(action==='rating'){const pl=player(p.playerId);pl.initialRating=p.value;pl.ratingReason=p.reason;pl.enabled=p.enabled;replayRating(s)}
 else if(action==='role'){const acc=s.accounts.find(x=>x.id===p.accountId)??fail('账号不存在');if(acc.role==='admin'&&p.role==='member'&&s.accounts.filter(x=>x.role==='admin').length===1)fail('至少保留一位管理员');acc.role=p.role}
 else if(action==='historyRules'){if(p.rules.ceiling<p.rules.target)fail('比赛规则无效');const season=s.seasons.find(x=>x.id===p.season)??fail('赛季不存在');season.rules=p.rules;season.version=(season.version??1)+1;replayRating(s)}
 else if(action==='historyPreview'){const copy=structuredClone(s);const season=copy.seasons.find(x=>x.id===p.season)??fail('赛季不存在');season.rules=p.rules;replayRating(copy);return copy}
 else if(action==='demo'){if(s.events.length)fail('仅能在尚无活动时创建虚构测试活动');seedDemo(s,a,now)}
 s.audits.push({id:id(),at:now,actor:a.id,action,reason:p.reason??`${action} 操作`,changes:action==='settings'?{name:p.name,rules:p.rules}:before?{before,input:p}:p});return null;
}
function checkBooking(e:{start:number;end:number},b:{start:number;end:number}){if(b.start<e.start||b.end>e.end||b.end<=b.start)fail('场地预约必须在活动时间内且结束晚于开始')}
export function promote(s:State,e:Event){let room=e.capacity-s.registrations.filter(r=>r.eventId===e.id&&r.status==='confirmed').length;for(const r of s.registrations.filter(r=>r.eventId===e.id&&r.status==='waitlist'&&s.players.some(p=>p.id===r.playerId&&p.enabled)).sort((a,b)=>a.sequence-b.sequence||a.id.localeCompare(b.id))){if(room--<=0)break;r.status='confirmed'}}
function seedDemo(s:State,a:Account,now:number){const start=now-60*60000,end=now+180*60000,e:Event={id:id(),title:'虚构测试 · 周末双打局',start,end,venue:'模拟球馆 · Madrid',address:'仅用于验收，没有真实预约',capacity:16,signupDeadline:end,cancelDeadline:end,note:'全部为虚构参赛者。删除测试环境数据后再正式使用。',status:'live',courtMode:'interval',ballMode:'interval'};s.events.push(e);s.bookings.push({id:id(),eventId:e.id,name:'1号场',start,end,pricing:'hourly',cents:1200},{id:id(),eventId:e.id,name:'2号场',start,end:start+60*60000,pricing:'hourly',cents:1200},{id:id(),eventId:e.id,name:'2号场',start:start+120*60000,end,pricing:'hourly',cents:1200});const pl=[s.players.find(p=>p.id===a.playerId)!];for(let i=1;i<18;i++){const p={id:id(),ownerId:a.id,name:`模拟球友 ${String(i).padStart(2,'0')}`,initialRating:880+i*15,rating:880+i*15,ratedGames:0,enabled:true,ratingReason:'虚构测试值'};s.players.push(p);pl.push(p)}pl.forEach((p,i)=>{s.registrations.push({id:id(),eventId:e.id,playerId:p.id,sequence:i+1,status:i<16?'confirmed':'waitlist',arrival:start,departure:end,note:'虚构验收数据',cancelRequested:false,courtExempt:{mode:'none',reason:''},ballExempt:{mode:'none',reason:''}});if(i<16)s.attendance.push({id:id(),eventId:e.id,playerId:p.id,start,end:null,state:'ready'})});s.costs.push({id:id(),eventId:e.id,type:'ball',name:'测试型号甲',pricing:'tube',cents:2400,tubeCount:12,used:6,start:null,end:null,bearer:'members'},{id:id(),eventId:e.id,type:'ball',name:'测试型号乙',pricing:'tube',cents:1800,tubeCount:12,used:4,start:null,end:null,bearer:'members'})}


