import {fail,type State,type Event,type Match} from './types';
export function readyIds(s:State,e:string,at:number){return [...new Set(s.attendance.filter(a=>a.eventId===e&&a.start<=at&&a.end===null&&a.state==='ready').map(a=>a.playerId))].filter(id=>s.players.some(p=>p.id===id&&p.enabled)&&!s.matches.some(m=>m.status==='playing'&&[...m.a,...m.b].includes(id)))}
export function propose(s:State,e:Event,at:number,duration:number,seed:number){const eligible=readyIds(s,e.id,at);const bookings=s.bookings.filter(b=>b.eventId===e.id&&b.start<=at&&b.end>=at+duration*60000&&!s.matches.some(m=>m.courtId===b.id&&m.status==='playing'));const courts=bookings.filter((b,i,arr)=>arr.findIndex(x=>x.name===b.name)===i);if(eligible.length<4)fail('目前可上场人数不足4人，无法生成双打');if(!courts.length)fail('预计比赛时段内没有完整可用的场地');
 const prior=s.rounds.filter(r=>r.eventId===e.id&&['published','playing','complete'].includes(r.status));
 const debt=(id:string)=>{let deficit=0,wait=0,games=0;for(const r of prior){if(!r.eligible.includes(id))continue;const ms=s.matches.filter(m=>m.roundId===r.id&&m.status!=='cancelled');const played=ms.some(m=>[...m.a,...m.b].includes(id));deficit+=ms.length*4/r.eligible.length-(played?1:0);if(played){wait=0;games++}else wait++}return {deficit,wait,games}};
 eligible.sort((a,b)=>{const x=debt(a),y=debt(b);return y.deficit-x.deficit||y.wait-x.wait||a.localeCompare(b)});const selected=eligible.slice(0,Math.min(courts.length,Math.floor(eligible.length/4))*4),rest=eligible.filter(id=>!selected.includes(id));
 const rating=(id:string)=>s.players.find(p=>p.id===id)!.rating;const history=s.matches.filter(m=>m.eventId===e.id&&m.status!=='draft'&&m.status!=='cancelled');
 const penalty=(list:string[])=>{let cost=0;for(let i=0;i<list.length;i+=4){const a=list.slice(i,i+2),b=list.slice(i+2,i+4);cost+=Math.abs((rating(a[0])+rating(a[1])-rating(b[0])-rating(b[1]))/2);for(const m of history){for(const team of [a,b])if([m.a,m.b].some(t=>team.every(id=>t.includes(id))))cost+=75;for(const x of a)for(const y of b)if((m.a.includes(x)&&m.b.includes(y))||(m.b.includes(x)&&m.a.includes(y)))cost+=12}}return cost};
 let rng=seed>>>0;const rand=()=>{rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng/4294967296};let best=[...selected],bestCost=penalty(best);for(let n=0;n<600;n++){const candidate=[...best];const i=Math.floor(rand()*candidate.length),j=Math.floor(rand()*candidate.length);[candidate[i],candidate[j]]=[candidate[j],candidate[i]];const cost=penalty(candidate);if(cost<bestCost||(cost===bestCost&&rand()<.1)){best=candidate;bestCost=cost}}
 return {eligible,rest,courts:courts.slice(0,best.length/4).map((court,i)=>({courtId:court.id,a:best.slice(i*4,i*4+2),b:best.slice(i*4+2,i*4+4)})),stats:Object.fromEntries(eligible.map(id=>[id,debt(id)])),penalty:bestCost};
}
export function validateRound(s:State,eventId:string,start:number,duration:number,matches:Match[]){const ids=matches.flatMap(m=>[...m.a,...m.b]);if(new Set(ids).size!==ids.length)fail('同一轮有重复选手');const ready=readyIds(s,eventId,start);const names=new Set<string>();for(const m of matches){if(m.a.length!==2||m.b.length!==2||[...m.a,...m.b].some(id=>!ready.includes(id)))fail('分组包含未到场、暂停、离场或正在比赛的成员');const b=s.bookings.find(b=>b.id===m.courtId&&b.eventId===eventId&&b.start<=start&&b.end>=start+duration*60000);if(!b||names.has(b.name))fail('场地不可用或重复');names.add(b.name)}}
