import {courtPlayers,eventFormat} from './match-format';
import {markRanked} from './all-ranked';
import {readyIds} from './grouping';
import {bookingAllowsPlayer} from './booking-signups';
import {pointsRoundWindows} from './points-phases';
import {tier,arenaStatus} from './social';
import {type State,type Event,type Match} from './types';
export function decorateMatch(s:State,e:Event,m:Match){markRanked(m);m.playMode=e.playMode??'balanced';const rating=(id:string)=>s.players.find(p=>p.id===id)?.rating??1000;const labels=(team:string[])=>{if(eventFormat(e)==='singles')return [];if(e.identityMode==='cp')return team.map(id=>({playerId:id,label:'本轮随机搭档'}));if(['mentor','carry'].includes(e.identityMode??'')){const strong=rating(team[0])>=rating(team[1])?team[0]:team[1];return team.map(id=>({playerId:id,label:e.identityMode==='mentor'?(id===strong?'师傅':'徒弟'):(id===strong?'大腿':'萌新')}))}return []};m.identity=[...labels(m.a),...labels(m.b)];const a=m.a.reduce((n,id)=>n+rating(id),0)/m.a.length,b=m.b.reduce((n,id)=>n+rating(id),0)/m.b.length,gap=Math.abs(a-b);m.handicap=e.handicap&&gap>=120?{side:a>b?'a':'b',points:Math.min(8,Math.max(1,Math.round(gap/60))),applied:false}:undefined}
export function rotationPlan(s:State,e:Event,at:number,duration=e.pointsPlan?.roundMinutes??15){const needed=courtPlayers(e),n=readyIds(s,e.id,at,duration).length;const available=new Set(s.bookings.filter(b=>b.eventId===e.id&&b.start<=at&&b.end>=at+duration*60000&&!s.matches.some(m=>m.status==='playing'&&m.courtId===b.id)).map(b=>(b.venue??e.venue)+'/'+b.name)).size;const ready=readyIds(s,e.id,at,duration),assigned=new Set<string>();let used=0;
 for(const b of s.bookings.filter(b=>b.eventId===e.id&&b.start<=at&&b.end>=at+duration*60000&&!s.matches.some(m=>m.status==='playing'&&m.courtId===b.id))){const pool=ready.filter(id=>!assigned.has(id)&&bookingAllowsPlayer(s,e.id,b.id,id,at,at+duration*60000));if(pool.length<needed)continue;pool.slice(0,needed).forEach(id=>assigned.add(id));used++}const slots=used*needed;let remaining=0;try{remaining=pointsRoundWindows(s,e,Math.max(at,e.start),e.end,duration).length}catch{}const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a;return {players:n,availableCourts:available,usedCourts:used,playing:Math.min(n,slots),rest:Math.max(0,n-slots),cycle:slots?n/gcd(n,slots):0,roundsLeft:remaining,description:n<needed?`不足${needed}人，等待更多正式球友参加`:!used?'当前没有完整可用时段的场地':`${n}人使用${used}片场，同一时段混合排场，每轮${slots}人上场、${n-slots}人轮休。${e.playMode==='arena'?'指定场地胜者留场，其余场地公平轮转。':`人数不变时，${n/gcd(n,slots)}轮构成一次均衡循环。`}`}}
