import {winner,points} from './social';
import {defaultRules,month,type State,type Rules,type Match} from './types';
export function validScore(a:number,b:number,r:Rules=defaultRules){if(!Number.isInteger(a)||!Number.isInteger(b)||a<0||b<0||a===b)return false;const hi=Math.max(a,b),lo=Math.min(a,b);return hi<=r.ceiling&&((hi===r.target&&lo<=hi-r.lead)||(hi>r.target&&hi<r.ceiling&&hi-lo===r.lead)||(hi===r.ceiling&&lo>=r.ceiling-r.lead&&lo<hi))}
export function replayRating(s:State){for(const p of s.players){p.rating=p.initialRating;p.ratedGames=0}const changes:{matchId:string;playerId:string;before:number;after:number;delta:number;algorithm:string}[]=[];
 for(const m of s.matches.filter(m=>m.status==='complete'&&m.elo).sort((a,b)=>(a.end!-b.end!)||a.id.localeCompare(b.id))){const a=m.a.map(id=>s.players.find(p=>p.id===id)!),b=m.b.map(id=>s.players.find(p=>p.id===id)!);const ra=(a[0].rating+a[1].rating)/2,rb=(b[0].rating+b[1].rating)/2;const rules=s.seasons.find(x=>x.id===month(m.start!))?.rules??s.settings.rules;const expected=1/(1+10**((rb-ra)/400)),delta=rules.k*((winner(m)==='a'?1:0)-expected);for(const [ps,d]of [[a,delta],[b,-delta]] as const)for(const p of ps){changes.push({matchId:m.id,playerId:p.id,before:p.rating,after:p.rating+d,delta:d,algorithm:rules.algorithm});p.rating+=d;p.ratedGames++}}
 s.ratingChanges=changes.map(c=>({...c,id:c.matchId+':'+c.playerId,k:s.seasons.find(x=>x.id===month(s.matches.find(m=>m.id===c.matchId)!.start!))?.rules.k??s.settings.rules.k}));return changes;
}
export function leaderboard(s:State,season:string){const rules=s.seasons.find(x=>x.id===season)?.rules??s.settings.rules;
 const rows=s.players.filter(p=>p.enabled).map(p=>{const all=s.matches.filter(m=>m.status==='complete'&&m.start&&month(m.start)===season&&[...m.a,...m.b].includes(p.id));const eligible=all.filter(m=>m.monthly).sort((a,b)=>a.start!-b.start!||a.id.localeCompare(b.id));const scored=rules.cap?eligible.slice(0,rules.cap):eligible;let wins=0,margin=0;for(const m of scored){const isA=m.a.includes(p.id);const my=points(m,isA?'a':'b'),op=points(m,isA?'b':'a');if(winner(m)===(isA?'a':'b'))wins++;margin+=my-op}return {playerId:p.id,name:p.name,rating:p.rating,provisional:p.ratedGames<10,total:all.length,games:scored.length,wins,losses:scored.length-wins,points:wins*rules.win+(scored.length-wins)*rules.loss,rate:scored.length?wins/scored.length:0,margin:scored.length?margin/scored.length:0,qualified:scored.length>=rules.minimum,rank:0}}).sort((a,b)=>b.points-a.points||b.rate-a.rate||b.margin-a.margin||a.playerId.localeCompare(b.playerId));
 for(const qualified of [true,false]){const group=rows.filter(x=>x.qualified===qualified);group.forEach((row,i)=>{const prev=group[i-1];row.rank=prev&&prev.points===row.points&&prev.rate===row.rate&&prev.margin===row.margin?prev.rank:i+1})}return rows;
}
