import {month,type State,type Match} from './types';
import {realmSnapshot,playerRealm,teamRealmLabel,realmPolicy} from './realm-rating';
import {gameFacts,gameRecord} from './game-facts';
export const awardNames={mvp:'MVP · 最佳球员'};
export function winner(m:Match){if(m.games?.length>1)return m.games.filter(g=>g.a>g.b).length>m.games.filter(g=>g.b>g.a).length?'a':'b';return m.scoreA!>m.scoreB!?'a':'b'}
export function points(m:Match,side:'a'|'b'){return m.games?.length?m.games.reduce((n,g)=>n+g[side],0):side==='a'?m.scoreA!:m.scoreB!}
export function won(m:Match,id:string){return m[winner(m)].includes(id)}
export function finished(s:State){return s.matches.filter(m=>m.status==='complete'&&m.start!==null&&m.end!==null).sort((a,b)=>a.start!-b.start!||a.id.localeCompare(b.id))}
export function relationships(s:State,id:string,matches=finished(s)){
 const partners=new Map<string,{playerId:string;games:number;wins:number;losses:number;rate:number;matches:number;matchLosses:number}>(),opponents=new Map<string,{playerId:string;games:number;wins:number;losses:number;rate:number;matches:number;matchLosses:number}>();
 for(const m of matches){const side=m.a.includes(id)?'a':m.b.includes(id)?'b':null;if(!side)continue;const facts=gameRecord(m,id);if(!facts.games)continue;for(const [map,ids]of [[partners,m[side].filter(p=>p!==id)],[opponents,m[side==='a'?'b':'a']]] as const)for(const other of ids){const row=map.get(other)??{playerId:other,games:0,wins:0,losses:0,rate:0,matches:0,matchLosses:0};row.games+=facts.games;row.wins+=facts.wins;row.losses+=facts.losses;row.matches++;row.matchLosses+=won(m,id)?0:1;row.rate=row.wins/row.games;map.set(other,row)}}
 return {partners:[...partners.values()].sort((a,b)=>b.games-a.games||a.playerId.localeCompare(b.playerId)),opponents:[...opponents.values()].sort((a,b)=>b.games-a.games||a.playerId.localeCompare(b.playerId))};
}
export function streaks(matches:Match[],id:string){let w=0,l=0,maxWins=0,maxLosses=0;for(const m of matches.filter(m=>[...m.a,...m.b].includes(id)))for(const g of gameFacts(m)){if(m[g.winner].includes(id)){w++;l=0;maxWins=Math.max(maxWins,w)}else{l++;w=0;maxLosses=Math.max(maxLosses,l)}}return {maxWins,maxLosses,currentWins:w,currentLosses:l}}
export function playerStats(s:State,id:string,growth=playerRealm(s,id)){
 const ms=finished(s).filter(m=>[...m.a,...m.b].includes(id)),facts=ms.flatMap(gameFacts),recent=facts.slice(-10),wins=facts.filter(g=>g.match[g.winner].includes(id)).length,formValue=recent.length?Math.round(recent.filter(g=>g.match[g.winner].includes(id)).length/recent.length*100):null;
 const rel=relationships(s,id,ms),best=[...rel.partners].filter(r=>r.games>=3).sort((a,b)=>b.rate-a.rate||b.games-a.games||a.playerId.localeCompare(b.playerId)),worst=[...best].sort((a,b)=>a.rate-b.rate||b.games-a.games||a.playerId.localeCompare(b.playerId)),opp=[...rel.opponents].filter(r=>r.games>=3);
 return {playerId:id,games:facts.length,matches:ms.length,wins,losses:facts.length-wins,rate:facts.length?wins/facts.length:0,tier:growth.realm,realmScore:growth,provisional:growth.placement,formValue,formGames:recent.length,form:recent.length<5?'样本不足':formValue!>=70?'🔥 火热':formValue!<=30?'低迷':'正常',...streaks(ms,id),...rel,bestPartner:best[0]??null,worstPartner:worst.length>1?worst[0]:null,dominates:[...opp].filter(r=>r.rate>.5).sort((a,b)=>b.rate-a.rate||b.games-a.games)[0]??null,nemesis:[...opp].filter(r=>r.rate<.5).sort((a,b)=>a.rate-b.rate||b.games-a.games)[0]??null};
}
export function arenaStatus(s:State,eventId:string){const e=s.events.find(e=>e.id===eventId);const ms=finished(s).filter(m=>m.eventId===eventId&&m.playMode==='arena'&&s.bookings.find(b=>b.id===m.courtId)?.name===s.bookings.find(b=>b.id===e?.arenaCourtId)?.name);const latest=ms.at(-1);if(!latest)return {holders:[],streak:0,matchId:null};const holders=latest[winner(latest)];let count=0;for(const m of [...ms].reverse()){const team=m[winner(m)];if(team.length===holders.length&&holders.every(id=>team.includes(id)))count++;else break}return {holders,streak:count,matchId:latest.id}}
export function courtLeaderboard(s:State,eventId:string){return s.players.map(p=>{const ms=finished(s).filter(m=>m.eventId===eventId&&m.playMode==='koc'&&[...m.a,...m.b].includes(p.id));return {playerId:p.id,games:ms.length,wins:ms.filter(m=>won(m,p.id)).length,points:ms.reduce((n,m)=>n+points(m,m.a.includes(p.id)?'a':'b'),0),margin:ms.reduce((n,m)=>n+(m.a.includes(p.id)?1:-1)*(points(m,'a')-points(m,'b')),0)}}).filter(r=>r.games).sort((a,b)=>b.points-a.points||b.wins-a.wins||b.margin-a.margin||a.playerId.localeCompare(b.playerId))}
export function annual(s:State,id:string,year:number){const ms=finished(s).filter(m=>[...m.a,...m.b].includes(id)&&Number(month(m.start!).slice(0,4))===year);const rel=relationships(s,id,ms);return {year,games:ms.reduce((n,m)=>n+gameRecord(m,id).games,0),wins:ms.reduce((n,m)=>n+gameRecord(m,id).wins,0),activities:new Set(ms.map(m=>m.eventId)).size,favoritePartner:rel.partners[0]??null,dominates:[...rel.opponents].filter(r=>r.games>=3).sort((a,b)=>b.rate-a.rate||b.games-a.games)[0]??null,...streaks(ms,id),minutes:ms.reduce((n,m)=>n+Math.max(0,m.end!-m.start!)/60000,0)}}
export function funnyStats(s:State,period:string){const ms=finished(s).filter(m=>month(m.start!)===period);return s.players.map(p=>{const mine=ms.filter(m=>[...m.a,...m.b].includes(p.id));return {playerId:p.id,closeLosses:mine.filter(m=>{const g=m.games.at(-1)??{a:m.scoreA!,b:m.scoreB!};return !won(m,p.id)&&Math.max(g.a,g.b)===21&&Math.min(g.a,g.b)===19}).length,threeGames:mine.filter(m=>m.games.length===3).length,overtime:mine.filter(m=>m.games.some(g=>Math.max(g.a,g.b)>21)).length,longestMinutes:mine.reduce((n,m)=>Math.max(n,(m.end!-m.start!)/60000),0),...streaks(mine,p.id)}})}
export function personality(s:State,year:number,now=Date.now()){return s.players.map(p=>{const events=s.events.filter(e=>Number(month(e.start).slice(0,4))===year);const arrivals=events.map(e=>({e,a:s.attendance.filter(a=>a.eventId===e.id&&a.playerId===p.id&&a.source!=='automatic'&&a.start<=now).sort((a,b)=>a.start-b.start)[0]})).filter(x=>x.a);const regs=s.registrations.filter(r=>r.playerId===p.id&&r.status!=='cancelled'&&events.some(e=>e.id===r.eventId));return {playerId:p.id,early:arrivals.filter(({e,a})=>a.start<e.start).length,onTime:arrivals.filter(({e,a})=>a.start>=e.start&&a.start<=e.start+5*60000).length,promoted:regs.filter(r=>r.bookingSignups?r.bookingSignups.some(x=>x.status!=='cancelled'&&x.joinedAsWaitlist&&x.promotedAt):r.joinedAsWaitlist&&r.promotedAt).length,fastSignup:regs.filter(r=>r.bookingSignups?r.bookingSignups.some(x=>x.status!=='cancelled'&&x.registeredAt&&x.sequence===1):r.registeredAt&&r.sequence===1).length,signupSamples:regs.filter(r=>r.registeredAt).length}})}
/** matchLevels: each team's realm from settled 修为 (定级中 while a player is in placement). */
export function socialSnapshot(s:State,period:string,year:number,now=Date.now(),history=s,realms=realmSnapshot(history,now)){const growth=realms,level=(team:string[])=>teamRealmLabel(team.map(id=>growth.get(id)??{score:realmPolicy.start,placement:true}));return {stats:history.players.map(p=>playerStats(history,p.id,growth.get(p.id))),funny:funnyStats(history,period),personality:personality(s,year,now),annual:history.players.map(p=>({playerId:p.id,...annual(history,p.id,year)})),arenas:Object.fromEntries(s.events.map(e=>[e.id,arenaStatus(s,e.id)])),courtBoards:Object.fromEntries(s.events.map(e=>[e.id,courtLeaderboard(s,e.id)])),matchLevels:Object.fromEntries(s.matches.map(m=>[m.id,{a:level(m.a),b:level(m.b)}]))}}
