import {env} from 'cloudflare:workers';
import {emptyState,type State} from './domain/types';
const names=['accounts','players','events','bookings','registrations','attendance','rounds','matches','costs','settlements','payments','seasons','audits','ratingChanges'] as const;
export function raw(){if(!env.DB)throw new Error('数据库暂不可用，请稍后重试');return env.DB}
export async function load():Promise<State>{const db=raw();const result:any[]=await db.batch([db.prepare('SELECT COALESCE(MAX(revision),0) AS revision FROM commits'),db.prepare('SELECT payload FROM settings WHERE id = ?').bind('club'),...names.map(n=>db.prepare(`SELECT payload FROM ${n}`))]);const s=emptyState();s.revision=Number(result[0].results[0].revision);if(result[1].results[0])s.settings=JSON.parse(String(result[1].results[0].payload));names.forEach((n,i)=>{(s[n] as unknown[])=result[i+2].results.map((row:any)=>JSON.parse(String(row.payload)))});return s}
export async function committed(key:string){return !!(await raw().prepare('SELECT revision FROM commits WHERE key = ?').bind(key).first())}
export async function save(s:State,key:string,previous:State){const db=raw();const qs=[db.prepare('INSERT INTO commits(revision,key,at) VALUES(?,?,?)').bind(s.revision+1,key,Date.now())];
 // A unique revision is the optimistic transaction gate. A losing writer's entire D1 batch rolls back.
 for(const n of [...names].reverse()){const current=new Set(s[n].map(r=>r.id));for(const row of previous[n])if(!current.has(row.id))qs.push(db.prepare(`DELETE FROM ${n} WHERE id = ?`).bind(row.id));}if(JSON.stringify(s.settings)!==JSON.stringify(previous.settings))qs.push(db.prepare('INSERT INTO settings(id,payload) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').bind('club',JSON.stringify(s.settings)));
 for(const n of names){const prior=new Map(previous[n].map(row=>[row.id,JSON.stringify(row)]));for(const row of s[n]){if(prior.get(row.id)===JSON.stringify(row))continue;const r=row as unknown as Record<string,unknown>;const columns=['id'],values:unknown[]=[r.id];if(n==='accounts'){columns.push('email','role','player_id');values.push(r.email,r.role,r.playerId)}else if(n==='players'){columns.push('owner_id');values.push(r.ownerId)}else if(!['seasons','audits','events','ratingChanges'].includes(n)){columns.push('event_id');values.push(r.eventId);if(['registrations','attendance','payments'].includes(n)){columns.push('player_id');values.push(r.playerId)}if(n==='matches'){columns.push('round_id');values.push(r.roundId)}if(n==='settlements'){columns.push('version');values.push(r.version)}}columns.push('payload');values.push(JSON.stringify(r));qs.push(db.prepare(`INSERT INTO ${n}(${columns.join(',')}) VALUES(${columns.map(()=>'?').join(',')}) ON CONFLICT(id) DO UPDATE SET ${columns.slice(1).map(c=>c+'=excluded.'+c).join(',')}`).bind(...values))}}
 await db.batch(qs);s.revision++;
}
