import {getAppUser,passwordEnabled} from '../../../lib/auth';
import {load,save,committed,raw} from '../../../lib/store';
import {apply,digest} from '../../../lib/domain/commands';
import {month,type State,type Account} from '../../../lib/domain/types';
import {leaderboard,replayRating} from '../../../lib/domain/ranking';
import {calculateSettlement} from '../../../lib/domain/money';
import {z} from 'zod';
import {socialSnapshot} from '../../../lib/domain/social';
import {rotationPlan} from '../../../lib/domain/play';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
function view(s:State,a:Account,period:string,year:number){const admin=a.role==='admin';if(!admin){s=structuredClone(s);s.events=s.events.filter(e=>e.status!=='draft');const ids=new Set(s.events.map(e=>e.id));for(const key of ['bookings','registrations','attendance','rounds','matches','costs','settlements','payments'] as const)(s[key] as unknown[])=s[key].filter(row=>ids.has(row.eventId));}const social=socialSnapshot(s,period,year);const drafts=admin?s.events.map(e=>calculateSettlement(s,e,Date.now())):[];return {revision:s.revision,settings:{name:s.settings.name,rules:s.settings.rules},me:a,players:s.players.map(p=>({...p,...(!admin?{rating:null,initialRating:null,ratingReason:''}:{}),ownerId:p.ownerId===a.id?a.id:''})),events:s.events,bookings:s.bookings,registrations:s.registrations,attendance:s.attendance,rounds:s.rounds,matches:s.matches,costs:s.costs,seasons:s.seasons,leaderboard:leaderboard(s,period).map(r=>({...r,...(!admin?{rating:null}:{})})),period,social,challenges:s.challenges,tagVotes:s.tagVotes.map(v=>({...v,voterId:v.voterId===a.id?a.id:''})),awardVotes:s.awardVotes.map(v=>({...v,voterId:v.voterId===a.id?a.id:''})),photos:s.photos.filter(p=>p.kind==='avatar'||s.events.some(e=>e.id===p.eventId)).map(({key,...p})=>p),rotationPlans:Object.fromEntries(s.events.map(e=>[e.id,rotationPlan(s,e,Date.now())])),settlements:s.settlements.map(x=>({...x,bills:x.bills,detail:x.detail})),audits:admin?s.audits:[],accounts:admin?s.accounts:[],drafts,ratingHistory:admin?replayRating(structuredClone(s)):[]}}
function error(e:unknown){const msg=e instanceof z.ZodError?'输入无效：'+e.issues.map(i=>i.path.join('.')+' '+i.message).join('；'):e instanceof Error?e.message:'服务暂不可用';return response({error:msg},msg.startsWith('403')?403:msg.startsWith('409')?409:400)}
export async function GET(req:Request){try{const user=await getAppUser();if(!user)return response({error:'请先登录羽林大会'},401);const s=await load();if(!s.settings.initialized)return response({setup:true,user:{name:user.displayName,email:user.email}});const a=s.accounts.find(a=>a.id===user.userId);if(!a){if(!['127.0.0.1','localhost','[::1]'].includes(new URL(req.url).hostname))return response({error:'请联系管理员创建登录账号'},403);return response({join:true,user:{name:user.displayName}})}const period=new URL(req.url).searchParams.get('month')??month(Date.now());if(!/^\d{4}-\d{2}$/.test(period))throw new Error('月份无效');if(new URL(req.url).searchParams.get('export')==='1'){if(a.role!=='admin')return response({error:'403: 仅管理员可以导出'},403);return new Response(JSON.stringify(s,null,2),{headers:{'Content-Type':'application/json','Content-Disposition':'attachment; filename="club-export.json"','Cache-Control':'no-store'}})}const year=Number(new URL(req.url).searchParams.get('year')??period.slice(0,4));if(!Number.isInteger(year)||year<2000||year>2100)throw new Error('年份无效');const credentials=await raw().prepare('SELECT id AS accountId,username FROM password_credentials').all<{accountId:string;username:string}>();const ownUsername=credentials.results.find(c=>c.accountId===a.id)?.username??null;return response({...view(s,a,period,year),loginAccounts:a.role==='admin'?credentials.results:[],auth:{method:user.method,username:ownUsername,passwordEnabled:!!ownUsername}})}catch(e){return error(e)}}
export async function POST(req:Request){try{const user=await getAppUser();if(!user)return response({error:'请先登录'},401);if(req.headers.get('origin')!==new URL(req.url).origin)return response({error:'403: 请求来源不允许'},403);const body=z.object({action:z.string().max(40),payload:z.unknown(),requestId:z.string().uuid(),revision:z.number().int().nonnegative().optional()}).parse(await req.json());const key=user.userId+':'+body.requestId;
 for(let attempt=0;attempt<5;attempt++){const s=await load();const previous=structuredClone(s);let a=s.accounts.find(a=>a.id===user.userId);if(await committed(key))return response({ok:true,duplicate:true});
  if(body.action==='initialize'||body.action==='join'){if(!['127.0.0.1','localhost','[::1]'].includes(new URL(req.url).hostname))throw new Error('403: 请联系管理员创建账号，网站不开放自行注册');const p=z.object({name:z.string().trim().min(1).max(150),invite:z.string().min(8).max(100)}).parse(body.payload);if(a)return response({ok:true});if(body.action==='initialize'&&!['127.0.0.1','localhost','[::1]'].includes(new URL(req.url).hostname))throw new Error('403: 请联系现有管理员开通群组');if(body.action==='initialize'&&s.settings.initialized)throw new Error('群组已初始化');if(body.action==='join'&&(!s.settings.initialized||await digest(p.invite)!==s.settings.inviteHash))throw new Error('邀请码无效');const playerId=crypto.randomUUID();a={id:user.userId,email:user.email,role:body.action==='initialize'?'admin':'member',playerId};s.accounts.push(a);s.players.push({id:playerId,ownerId:a.id,name:p.name,initialRating:1000,rating:1000,ratedGames:0,enabled:true,ratingReason:'新成员默认初值'});if(body.action==='initialize'){s.settings.initialized=true;s.settings.inviteHash=await digest(p.invite)}s.audits.push({id:crypto.randomUUID(),at:Date.now(),actor:a.id,action:body.action,reason:'ChatGPT 已验证身份'})}
  else{if(!a)return response({error:'403: 请先加入群组'},403);if(!['register','cancel','friend','profile'].includes(body.action)&&body.revision!==s.revision)throw new Error('409: 数据已更新，请刷新后重试');const preview=await apply(s,a,body.action,body.payload,Date.now());if(body.action==='historyPreview'&&preview)return response({preview:{input:body.payload,leaderboard:leaderboard(preview,(body.payload as any).season),ratingHistory:replayRating(preview)}})}
  try{await save(s,key,previous);return response({ok:true,revision:s.revision})}catch(e){if(String(e).includes('UNIQUE constraint failed: commits')&&attempt<4){if(!['register','cancel','join','initialize','friend','profile'].includes(body.action))throw new Error('409: 其他管理员刚刚保存了变更，请刷新重试');continue}throw e}
 }throw new Error('409: 同时操作较多，请稍后重试');}catch(e){return error(e)}}

